// Code generated by protoc-gen-go-grpc-locator. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-locator v1.2.0
// - protoc             v5.28.2
// source: transport/actor/actor.proto

package actor

import (
	context "context"
	rpc "github.com/2comjie/wali/rpc"
	client "github.com/2comjie/wali/rpc/client"
	rpcerr "github.com/2comjie/wali/rpc/rpcerr"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Actor_Ask_FullMethodName  = "/wali.transport.actor.Actor/Ask"
	Actor_Tell_FullMethodName = "/wali.transport.actor.Actor/Tell"
)

// ActorClient is the client API for Actor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActorClient interface {
	Ask(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err)
	Tell(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err)
}

type actorClient struct {
	cc *client.Client
}

func NewActorClient(cc *client.Client) ActorClient {
	return &actorClient{cc}
}

func (c *actorClient) Ask(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	out := new(Response)
	err = conn.Invoke(ctx, Actor_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	return out, nil
}

func (c *actorClient) Tell(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	out := new(Response)
	err = conn.Invoke(ctx, Actor_Tell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	return out, nil
}

// ActorServer is the server API for Actor service.
// All implementations must embed UnimplementedActorServer
// for forward compatibility.
type ActorServer interface {
	Ask(context.Context, *Request) (*Response, rpcerr.Err)
	Tell(context.Context, *Request) (*Response, rpcerr.Err)
	mustEmbedUnimplementedActorServer()
}

// UnimplementedActorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActorServer struct{}

func (UnimplementedActorServer) Ask(context.Context, *Request) (*Response, rpcerr.Err) {
	return nil, rpcerr.NewGRPC(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedActorServer) Tell(context.Context, *Request) (*Response, rpcerr.Err) {
	return nil, rpcerr.NewGRPC(codes.Unimplemented, "method Tell not implemented")
}
func (UnimplementedActorServer) mustEmbedUnimplementedActorServer() {}
func (UnimplementedActorServer) testEmbeddedByValue()               {}

// UnsafeActorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorServer will
// result in compilation errors.
type UnsafeActorServer interface {
	mustEmbedUnimplementedActorServer()
}

func RegisterActorServer(s grpc.ServiceRegistrar, srv ActorServer) {
	// If the following call panics, it indicates UnimplementedActorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Actor_ServiceDesc, srv)
}

func _Actor_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		response, err := srv.(ActorServer).Ask(ctx, in)
		return response, rpc.EncodeError(err)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Actor_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServer).Ask(ctx, req.(*Request))
	}
	response, err := interceptor(ctx, in, info, handler)
	return response, rpc.EncodeError(err)
}

func _Actor_Tell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		response, err := srv.(ActorServer).Tell(ctx, in)
		return response, rpc.EncodeError(err)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Actor_Tell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorServer).Tell(ctx, req.(*Request))
	}
	response, err := interceptor(ctx, in, info, handler)
	return response, rpc.EncodeError(err)
}

// Actor_ServiceDesc is the grpc.ServiceDesc for Actor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Actor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wali.transport.actor.Actor",
	HandlerType: (*ActorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _Actor_Ask_Handler,
		},
		{
			MethodName: "Tell",
			Handler:    _Actor_Tell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/actor/actor.proto",
}
