// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: transport/actor/actor.proto

package actor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorType     int32                  `protobuf:"varint,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorKey      string                 `protobuf:"bytes,2,opt,name=actor_key,json=actorKey,proto3" json:"actor_key,omitempty"`
	Activation    uint32                 `protobuf:"varint,3,opt,name=activation,proto3" json:"activation,omitempty"`
	Route         uint32                 `protobuf:"varint,4,opt,name=route,proto3" json:"route,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_transport_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_transport_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_transport_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetActorType() int32 {
	if x != nil {
		return x.ActorType
	}
	return 0
}

func (x *Request) GetActorKey() string {
	if x != nil {
		return x.ActorKey
	}
	return ""
}

func (x *Request) GetActivation() uint32 {
	if x != nil {
		return x.Activation
	}
	return 0
}

func (x *Request) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_transport_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_transport_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_transport_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_transport_actor_actor_proto protoreflect.FileDescriptor

const file_transport_actor_actor_proto_rawDesc = "" +
	"\n" +
	"\x1btransport/actor/actor.proto\x12\x14wali.transport.actor\"\x8f\x01\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x01 \x01(\x05R\tactorType\x12\x1b\n" +
	"\tactor_key\x18\x02 \x01(\tR\bactorKey\x12\x1e\n" +
	"\n" +
	"activation\x18\x03 \x01(\rR\n" +
	"activation\x12\x14\n" +
	"\x05route\x18\x04 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"8\n" +
	"\bResponse\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body2\x94\x01\n" +
	"\x05Actor\x12D\n" +
	"\x03Ask\x12\x1d.wali.transport.actor.Request\x1a\x1e.wali.transport.actor.Response\x12E\n" +
	"\x04Tell\x12\x1d.wali.transport.actor.Request\x1a\x1e.wali.transport.actor.ResponseB;Z9github.com/2comjie/wali/internal/pb/transport/actor;actorb\x06proto3"

var (
	file_transport_actor_actor_proto_rawDescOnce sync.Once
	file_transport_actor_actor_proto_rawDescData []byte
)

func file_transport_actor_actor_proto_rawDescGZIP() []byte {
	file_transport_actor_actor_proto_rawDescOnce.Do(func() {
		file_transport_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_actor_actor_proto_rawDesc), len(file_transport_actor_actor_proto_rawDesc)))
	})
	return file_transport_actor_actor_proto_rawDescData
}

var file_transport_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_actor_actor_proto_goTypes = []any{
	(*Request)(nil),  // 0: wali.transport.actor.Request
	(*Response)(nil), // 1: wali.transport.actor.Response
}
var file_transport_actor_actor_proto_depIdxs = []int32{
	0, // 0: wali.transport.actor.Actor.Ask:input_type -> wali.transport.actor.Request
	0, // 1: wali.transport.actor.Actor.Tell:input_type -> wali.transport.actor.Request
	1, // 2: wali.transport.actor.Actor.Ask:output_type -> wali.transport.actor.Response
	1, // 3: wali.transport.actor.Actor.Tell:output_type -> wali.transport.actor.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_actor_actor_proto_init() }
func file_transport_actor_actor_proto_init() {
	if File_transport_actor_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_actor_actor_proto_rawDesc), len(file_transport_actor_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_actor_actor_proto_goTypes,
		DependencyIndexes: file_transport_actor_actor_proto_depIdxs,
		MessageInfos:      file_transport_actor_actor_proto_msgTypes,
	}.Build()
	File_transport_actor_actor_proto = out.File
	file_transport_actor_actor_proto_goTypes = nil
	file_transport_actor_actor_proto_depIdxs = nil
}
