//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package main

import (
	diff "github.com/2comjie/nova/diff"
)

type Player struct {
	diff.Object
	uid          diff.Primitive[uint64]
	level        diff.Primitive[int32]
	name         diff.Primitive[string]
	bag          diff.Pointer[*Bag]
	scores       diff.PrimitiveMap[uint64, int32]
	recentLevels diff.PrimitiveSlice[int32]
}

func (value *Player) GetUid() uint64 {
	return value.uid.GetValue()
}

func (value *Player) SetUid(fieldValue uint64) bool {
	value.EnsureDiffLink()
	return value.uid.SetValue(fieldValue)
}

func (value *Player) GetLevel() int32 {
	return value.level.GetValue()
}

func (value *Player) SetLevel(fieldValue int32) bool {
	value.EnsureDiffLink()
	return value.level.SetValue(fieldValue)
}

func (value *Player) GetName() string {
	return value.name.GetValue()
}

func (value *Player) SetName(fieldValue string) bool {
	value.EnsureDiffLink()
	return value.name.SetValue(fieldValue)
}

func (value *Player) GetBag() *Bag {
	return value.bag.GetValue()
}

func (value *Player) SetBag(fieldValue *Bag) bool {
	value.EnsureDiffLink()
	return value.bag.SetValue(fieldValue)
}

func (value *Player) ClearBag() bool {
	value.EnsureDiffLink()
	return value.bag.SetValue(nil)
}

func (value *Player) Scores() *diff.PrimitiveMap[uint64, int32] {
	value.EnsureDiffLink()
	return &value.scores
}

func (value *Player) RecentLevels() *diff.PrimitiveSlice[int32] {
	value.EnsureDiffLink()
	return &value.recentLevels
}

type Bag struct {
	diff.Object
	items diff.PointerMap[uint64, *Item]
	order diff.PointerSlice[*Item]
}

func (value *Bag) Items() *diff.PointerMap[uint64, *Item] {
	value.EnsureDiffLink()
	return &value.items
}

func (value *Bag) Order() *diff.PointerSlice[*Item] {
	value.EnsureDiffLink()
	return &value.order
}

type Item struct {
	diff.Object
	itemId diff.Primitive[uint64]
	count  diff.Primitive[int32]
}

func (value *Item) GetItemId() uint64 {
	return value.itemId.GetValue()
}

func (value *Item) SetItemId(fieldValue uint64) bool {
	value.EnsureDiffLink()
	return value.itemId.SetValue(fieldValue)
}

func (value *Item) GetCount() int32 {
	return value.count.GetValue()
}

func (value *Item) SetCount(fieldValue int32) bool {
	value.EnsureDiffLink()
	return value.count.SetValue(fieldValue)
}

type PlayerDiffPath[DiffRoot any] struct {
	path diff.PathBuilder[DiffRoot]
}

func NewPlayerDiffPath[DiffRoot any](path diff.PathBuilder[DiffRoot]) PlayerDiffPath[DiffRoot] {
	return PlayerDiffPath[DiffRoot]{path: path}
}

var PlayerDiff = NewPlayerDiffPath[*Player](diff.NewPathBuilder[*Player]())

func (path PlayerDiffPath[DiffRoot]) Uid() diff.ValuePath[DiffRoot, uint64] {
	return diff.NewValuePath[DiffRoot, uint64](path.path.Field(1))
}

func (path PlayerDiffPath[DiffRoot]) Level() diff.ValuePath[DiffRoot, int32] {
	return diff.NewValuePath[DiffRoot, int32](path.path.Field(2))
}

func (path PlayerDiffPath[DiffRoot]) Name() diff.ValuePath[DiffRoot, string] {
	return diff.NewValuePath[DiffRoot, string](path.path.Field(3))
}

func (path PlayerDiffPath[DiffRoot]) Bag() PlayerBagDiffPath[DiffRoot] {
	fieldPath := path.path.Field(4)
	return PlayerBagDiffPath[DiffRoot]{
		NewBagDiffPath[DiffRoot](fieldPath),
		diff.NewValuePath[DiffRoot, *Bag](fieldPath),
	}
}

type PlayerBagDiffPath[DiffRoot any] struct {
	BagDiffPath[DiffRoot]
	value diff.ValuePath[DiffRoot, *Bag]
}

func (path PlayerBagDiffPath[DiffRoot]) Changes() diff.ValuePath[DiffRoot, *Bag] {
	return path.value
}

func (path PlayerDiffPath[DiffRoot]) Scores() diff.MapPath[DiffRoot, uint64, int32] {
	return diff.NewMapPath[DiffRoot, uint64, int32](path.path, 5)
}

func (path PlayerDiffPath[DiffRoot]) RecentLevels() diff.SlicePath[DiffRoot, int32] {
	return diff.NewSlicePath[DiffRoot, int32](path.path, 6)
}

type BagDiffPath[DiffRoot any] struct {
	path diff.PathBuilder[DiffRoot]
}

func NewBagDiffPath[DiffRoot any](path diff.PathBuilder[DiffRoot]) BagDiffPath[DiffRoot] {
	return BagDiffPath[DiffRoot]{path: path}
}

var BagDiff = NewBagDiffPath[*Bag](diff.NewPathBuilder[*Bag]())

func (path BagDiffPath[DiffRoot]) Items() BagItemsDiffPath[DiffRoot] {
	return BagItemsDiffPath[DiffRoot]{
		path: diff.NewMapPath[DiffRoot, uint64, *Item](path.path, 1),
	}
}

type BagItemsDiffPath[DiffRoot any] struct {
	path diff.MapPath[DiffRoot, uint64, *Item]
}

func (path BagItemsDiffPath[DiffRoot]) Changes() diff.MapPath[DiffRoot, uint64, *Item] {
	return path.path
}

func (path BagItemsDiffPath[DiffRoot]) Any() ItemDiffPath[DiffRoot] {
	return NewItemDiffPath[DiffRoot](path.path.AnyPath())
}

func (path BagItemsDiffPath[DiffRoot]) Key(key uint64) ItemDiffPath[DiffRoot] {
	return NewItemDiffPath[DiffRoot](path.path.KeyPath(key))
}

func (path BagDiffPath[DiffRoot]) Order() BagOrderDiffPath[DiffRoot] {
	return BagOrderDiffPath[DiffRoot]{
		path: diff.NewSlicePath[DiffRoot, *Item](path.path, 2),
	}
}

type BagOrderDiffPath[DiffRoot any] struct {
	path diff.SlicePath[DiffRoot, *Item]
}

func (path BagOrderDiffPath[DiffRoot]) Changes() diff.SlicePath[DiffRoot, *Item] {
	return path.path
}

func (path BagOrderDiffPath[DiffRoot]) Any() ItemDiffPath[DiffRoot] {
	return NewItemDiffPath[DiffRoot](path.path.AnyPath())
}

func (path BagOrderDiffPath[DiffRoot]) Index(index int) ItemDiffPath[DiffRoot] {
	return NewItemDiffPath[DiffRoot](path.path.IndexPath(index))
}

type ItemDiffPath[DiffRoot any] struct {
	path diff.PathBuilder[DiffRoot]
}

func NewItemDiffPath[DiffRoot any](path diff.PathBuilder[DiffRoot]) ItemDiffPath[DiffRoot] {
	return ItemDiffPath[DiffRoot]{path: path}
}

var ItemDiff = NewItemDiffPath[*Item](diff.NewPathBuilder[*Item]())

func (path ItemDiffPath[DiffRoot]) ItemId() diff.ValuePath[DiffRoot, uint64] {
	return diff.NewValuePath[DiffRoot, uint64](path.path.Field(1))
}

func (path ItemDiffPath[DiffRoot]) Count() diff.ValuePath[DiffRoot, int32] {
	return diff.NewValuePath[DiffRoot, int32](path.path.Field(2))
}

func (value *Player) InitLink(writer *diff.Writer) {
	if writer != nil {
		diff.BindWriter[*Player](writer)
	}
	value.InitDiffLink(writer, make(map[*diff.Object]struct{}))
}

func (value *Player) EnsureDiffLink() {
	if value == nil {
		return
	}
	if value.uid.Initialized() {
		return
	}
	value.InitDiffLink(nil, make(map[*diff.Object]struct{}))
}

func (value *Player) InitDiffLink(writer *diff.Writer, visited map[*diff.Object]struct{}) {
	if value == nil {
		return
	}
	if visited == nil {
		visited = make(map[*diff.Object]struct{})
	}
	if _, exists := visited[&value.Object]; exists {
		return
	}
	visited[&value.Object] = struct{}{}
	value.Object.Init(writer)
	value.uid.Init(&value.Object, 1)
	value.level.Init(&value.Object, 2)
	value.name.Init(&value.Object, 3)
	if child := value.bag.GetValue(); child != nil {
		child.InitDiffLink(nil, visited)
	}
	value.bag.Init(&value.Object, 4)
	value.scores.Init(&value.Object, 5)
	value.recentLevels.Init(&value.Object, 6)
}

func (value *Player) AppendDiffValue(data []byte) []byte {
	data = value.uid.AppendValue(data, 1)
	data = value.level.AppendValue(data, 2)
	data = value.name.AppendValue(data, 3)
	data = value.bag.AppendValue(data, 4)
	data = value.scores.AppendValue(data, 5)
	data = value.recentLevels.AppendValue(data, 6)
	return data
}

func (value *Bag) InitLink(writer *diff.Writer) {
	if writer != nil {
		diff.BindWriter[*Bag](writer)
	}
	value.InitDiffLink(writer, make(map[*diff.Object]struct{}))
}

func (value *Bag) EnsureDiffLink() {
	if value == nil {
		return
	}
	if value.items.Initialized() {
		return
	}
	value.InitDiffLink(nil, make(map[*diff.Object]struct{}))
}

func (value *Bag) InitDiffLink(writer *diff.Writer, visited map[*diff.Object]struct{}) {
	if value == nil {
		return
	}
	if visited == nil {
		visited = make(map[*diff.Object]struct{})
	}
	if _, exists := visited[&value.Object]; exists {
		return
	}
	visited[&value.Object] = struct{}{}
	value.Object.Init(writer)
	value.items.Range(func(_ uint64, child *Item) bool {
		if child != nil {
			child.InitDiffLink(nil, visited)
		}
		return true
	})
	value.items.Init(&value.Object, 1)
	value.order.Range(func(_ int, child *Item) bool {
		if child != nil {
			child.InitDiffLink(nil, visited)
		}
		return true
	})
	value.order.Init(&value.Object, 2)
}

func (value *Bag) AppendDiffValue(data []byte) []byte {
	data = value.items.AppendValue(data, 1)
	data = value.order.AppendValue(data, 2)
	return data
}

func (value *Item) InitLink(writer *diff.Writer) {
	if writer != nil {
		diff.BindWriter[*Item](writer)
	}
	value.InitDiffLink(writer, make(map[*diff.Object]struct{}))
}

func (value *Item) EnsureDiffLink() {
	if value == nil {
		return
	}
	if value.itemId.Initialized() {
		return
	}
	value.InitDiffLink(nil, make(map[*diff.Object]struct{}))
}

func (value *Item) InitDiffLink(writer *diff.Writer, visited map[*diff.Object]struct{}) {
	if value == nil {
		return
	}
	if visited == nil {
		visited = make(map[*diff.Object]struct{})
	}
	if _, exists := visited[&value.Object]; exists {
		return
	}
	visited[&value.Object] = struct{}{}
	value.Object.Init(writer)
	value.itemId.Init(&value.Object, 1)
	value.count.Init(&value.Object, 2)
}

func (value *Item) AppendDiffValue(data []byte) []byte {
	data = value.itemId.AppendValue(data, 1)
	data = value.count.AppendValue(data, 2)
	return data
}

func (value *Player) Commit() []byte {
	return value.Object.Commit()
}

func (value *Player) Snapshot() []byte {
	return value.AppendDiffValue(nil)
}

func (value *Player) LoadSnapshot(data []byte) error {
	value.InitLink(nil)
	var zeroUid uint64
	value.uid.SetValue(zeroUid)
	var zeroLevel int32
	value.level.SetValue(zeroLevel)
	var zeroName string
	value.name.SetValue(zeroName)
	value.bag.SetValue(nil)
	value.scores.Clear()
	value.recentLevels.Clear()
	fields, err := diff.DecodeFields(data)
	if err != nil {
		return err
	}
	for _, field := range fields {
		if err := value.loadDiffField(field); err != nil {
			return err
		}
	}
	return nil
}

func (value *Player) Merge(data []byte) error {
	value.InitLink(nil)
	patches, err := diff.DecodePatches(data)
	if err != nil {
		return err
	}
	for _, patch := range patches {
		if err := value.MergeDiffPatch(patch.Path, patch.Operation, patch.Value); err != nil {
			return err
		}
	}
	return nil
}

func (value *Player) loadDiffField(field diff.EncodedField) error {
	switch field.FieldIndex {
	case 1:
		{
			fieldValue, err := diff.DecodePrimitive[uint64](field.Value)
			if err != nil {
				return err
			}
			value.uid.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			fieldValue, err := diff.DecodePrimitive[int32](field.Value)
			if err != nil {
				return err
			}
			value.level.SetValue(fieldValue)
			return nil
		}
	case 3:
		{
			fieldValue, err := diff.DecodePrimitive[string](field.Value)
			if err != nil {
				return err
			}
			value.name.SetValue(fieldValue)
			return nil
		}
	case 4:
		{
			fieldValue := new(Bag)
			if err := fieldValue.LoadSnapshot(field.Value); err != nil {
				return err
			}
			value.bag.SetValue(fieldValue)
			return nil
		}
	case 5:
		{
			entries, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			if len(entries)%2 != 0 {
				return diff.ErrInvalidData
			}
			for index := 0; index < len(entries); index += 2 {
				mapKey, err := diff.DecodePrimitive[uint64](entries[index])
				if err != nil {
					return err
				}
				mapValue, err := diff.DecodePrimitive[int32](entries[index+1])
				if err != nil {
					return err
				}
				value.scores.Store(mapKey, mapValue)
			}
			return nil
		}
	case 6:
		{
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				sliceValue, err := diff.DecodePrimitive[int32](element)
				if err != nil {
					return err
				}
				value.recentLevels.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}

func (value *Player) MergeDiffPatch(path []diff.EncodedPathNode, operation diff.Operation, data []byte) error {
	if len(path) == 0 {
		return diff.ErrInvalidData
	}
	node := path[0]
	switch node.FieldIndex {
	case 1:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[uint64](data)
			if err != nil {
				return err
			}
			value.uid.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[int32](data)
			if err != nil {
				return err
			}
			value.level.SetValue(fieldValue)
			return nil
		}
	case 3:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[string](data)
			if err != nil {
				return err
			}
			value.name.SetValue(fieldValue)
			return nil
		}
	case 4:
		{
			if node.KeyType != diff.PathField {
				return diff.ErrInvalidData
			}
			if len(path) == 1 {
				switch operation {
				case diff.PointerSet:
					fieldValue := new(Bag)
					if err := fieldValue.LoadSnapshot(data); err != nil {
						return err
					}
					value.bag.SetValue(fieldValue)
				case diff.PointerClear:
					value.bag.SetValue(nil)
				default:
					return diff.ErrInvalidData
				}
				return nil
			}
			fieldValue := value.bag.GetValue()
			if fieldValue == nil {
				return diff.ErrInvalidData
			}
			return fieldValue.MergeDiffPatch(path[1:], operation, data)
		}
	case 5:
		{
			if node.KeyType == diff.PathField {
				if len(path) != 1 || operation != diff.MapClear {
					return diff.ErrInvalidData
				}
				value.scores.Clear()
				return nil
			}
			if node.KeyType != diff.PathMap {
				return diff.ErrInvalidData
			}
			mapKey, err := diff.DecodePrimitive[uint64](node.MapKey)
			if err != nil {
				return err
			}
			if len(path) != 1 {
				return diff.ErrInvalidData
			}
			switch operation {
			case diff.MapSet:
				mapValue, err := diff.DecodePrimitive[int32](data)
				if err != nil {
					return err
				}
				value.scores.Store(mapKey, mapValue)
			case diff.MapDelete:
				value.scores.Delete(mapKey)
			default:
				return diff.ErrInvalidData
			}
			return nil
		}
	case 6:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.SliceReplace {
				return diff.ErrInvalidData
			}
			value.recentLevels.Clear()
			field := diff.EncodedField{FieldIndex: 6, Value: data}
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				sliceValue, err := diff.DecodePrimitive[int32](element)
				if err != nil {
					return err
				}
				value.recentLevels.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}

func (value *Bag) Commit() []byte {
	return value.Object.Commit()
}

func (value *Bag) Snapshot() []byte {
	return value.AppendDiffValue(nil)
}

func (value *Bag) LoadSnapshot(data []byte) error {
	value.InitLink(nil)
	value.items.Clear()
	value.order.Clear()
	fields, err := diff.DecodeFields(data)
	if err != nil {
		return err
	}
	for _, field := range fields {
		if err := value.loadDiffField(field); err != nil {
			return err
		}
	}
	return nil
}

func (value *Bag) Merge(data []byte) error {
	value.InitLink(nil)
	patches, err := diff.DecodePatches(data)
	if err != nil {
		return err
	}
	for _, patch := range patches {
		if err := value.MergeDiffPatch(patch.Path, patch.Operation, patch.Value); err != nil {
			return err
		}
	}
	return nil
}

func (value *Bag) loadDiffField(field diff.EncodedField) error {
	switch field.FieldIndex {
	case 1:
		{
			entries, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			if len(entries)%2 != 0 {
				return diff.ErrInvalidData
			}
			for index := 0; index < len(entries); index += 2 {
				mapKey, err := diff.DecodePrimitive[uint64](entries[index])
				if err != nil {
					return err
				}
				mapValue := new(Item)
				if err := mapValue.LoadSnapshot(entries[index+1]); err != nil {
					return err
				}
				value.items.Store(mapKey, mapValue)
			}
			return nil
		}
	case 2:
		{
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				elementData, exists, err := diff.DecodePointerElement(element)
				if err != nil {
					return err
				}
				if !exists {
					value.order.Append(nil)
					continue
				}
				sliceValue := new(Item)
				if err := sliceValue.LoadSnapshot(elementData); err != nil {
					return err
				}
				value.order.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}

func (value *Bag) MergeDiffPatch(path []diff.EncodedPathNode, operation diff.Operation, data []byte) error {
	if len(path) == 0 {
		return diff.ErrInvalidData
	}
	node := path[0]
	switch node.FieldIndex {
	case 1:
		{
			if node.KeyType == diff.PathField {
				if len(path) != 1 || operation != diff.MapClear {
					return diff.ErrInvalidData
				}
				value.items.Clear()
				return nil
			}
			if node.KeyType != diff.PathMap {
				return diff.ErrInvalidData
			}
			mapKey, err := diff.DecodePrimitive[uint64](node.MapKey)
			if err != nil {
				return err
			}
			if len(path) == 1 {
				switch operation {
				case diff.MapSet:
					mapValue := new(Item)
					if err := mapValue.LoadSnapshot(data); err != nil {
						return err
					}
					value.items.Store(mapKey, mapValue)
				case diff.MapDelete:
					value.items.Delete(mapKey)
				default:
					return diff.ErrInvalidData
				}
				return nil
			}
			mapValue, exists := value.items.Load(mapKey)
			if !exists {
				return diff.ErrInvalidData
			}
			return mapValue.MergeDiffPatch(path[1:], operation, data)
		}
	case 2:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.SliceReplace {
				return diff.ErrInvalidData
			}
			value.order.Clear()
			field := diff.EncodedField{FieldIndex: 2, Value: data}
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				elementData, exists, err := diff.DecodePointerElement(element)
				if err != nil {
					return err
				}
				if !exists {
					value.order.Append(nil)
					continue
				}
				sliceValue := new(Item)
				if err := sliceValue.LoadSnapshot(elementData); err != nil {
					return err
				}
				value.order.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}

func (value *Item) Commit() []byte {
	return value.Object.Commit()
}

func (value *Item) Snapshot() []byte {
	return value.AppendDiffValue(nil)
}

func (value *Item) LoadSnapshot(data []byte) error {
	value.InitLink(nil)
	var zeroItemId uint64
	value.itemId.SetValue(zeroItemId)
	var zeroCount int32
	value.count.SetValue(zeroCount)
	fields, err := diff.DecodeFields(data)
	if err != nil {
		return err
	}
	for _, field := range fields {
		if err := value.loadDiffField(field); err != nil {
			return err
		}
	}
	return nil
}

func (value *Item) Merge(data []byte) error {
	value.InitLink(nil)
	patches, err := diff.DecodePatches(data)
	if err != nil {
		return err
	}
	for _, patch := range patches {
		if err := value.MergeDiffPatch(patch.Path, patch.Operation, patch.Value); err != nil {
			return err
		}
	}
	return nil
}

func (value *Item) loadDiffField(field diff.EncodedField) error {
	switch field.FieldIndex {
	case 1:
		{
			fieldValue, err := diff.DecodePrimitive[uint64](field.Value)
			if err != nil {
				return err
			}
			value.itemId.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			fieldValue, err := diff.DecodePrimitive[int32](field.Value)
			if err != nil {
				return err
			}
			value.count.SetValue(fieldValue)
			return nil
		}
	}
	return nil
}

func (value *Item) MergeDiffPatch(path []diff.EncodedPathNode, operation diff.Operation, data []byte) error {
	if len(path) == 0 {
		return diff.ErrInvalidData
	}
	node := path[0]
	switch node.FieldIndex {
	case 1:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[uint64](data)
			if err != nil {
				return err
			}
			value.itemId.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[int32](data)
			if err != nil {
				return err
			}
			value.count.SetValue(fieldValue)
			return nil
		}
	}
	return nil
}
