// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: demo.proto

package pbDemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HayService_SayHay_FullMethodName = "/HayService/SayHay"
)

// HayServiceClient is the client API for HayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HayServiceClient interface {
	SayHay(ctx context.Context, in *HayRequest, opts ...grpc.CallOption) (*HayResponse, error)
}

type hayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHayServiceClient(cc grpc.ClientConnInterface) HayServiceClient {
	return &hayServiceClient{cc}
}

func (c *hayServiceClient) SayHay(ctx context.Context, in *HayRequest, opts ...grpc.CallOption) (*HayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HayResponse)
	err := c.cc.Invoke(ctx, HayService_SayHay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HayServiceServer is the server API for HayService service.
// All implementations must embed UnimplementedHayServiceServer
// for forward compatibility.
type HayServiceServer interface {
	SayHay(context.Context, *HayRequest) (*HayResponse, error)
	mustEmbedUnimplementedHayServiceServer()
}

// UnimplementedHayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHayServiceServer struct{}

func (UnimplementedHayServiceServer) SayHay(context.Context, *HayRequest) (*HayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHay not implemented")
}
func (UnimplementedHayServiceServer) mustEmbedUnimplementedHayServiceServer() {}
func (UnimplementedHayServiceServer) testEmbeddedByValue()                    {}

// UnsafeHayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HayServiceServer will
// result in compilation errors.
type UnsafeHayServiceServer interface {
	mustEmbedUnimplementedHayServiceServer()
}

func RegisterHayServiceServer(s grpc.ServiceRegistrar, srv HayServiceServer) {
	// If the following call panics, it indicates UnimplementedHayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HayService_ServiceDesc, srv)
}

func _HayService_SayHay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HayServiceServer).SayHay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HayService_SayHay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HayServiceServer).SayHay(ctx, req.(*HayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HayService_ServiceDesc is the grpc.ServiceDesc for HayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HayService",
	HandlerType: (*HayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHay",
			Handler:    _HayService_SayHay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
