// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player/a_data_player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Nova.Generated.Player {

  /// <summary>Holder for reflection information generated from player/a_data_player.proto</summary>
  public static partial class ADataPlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for player/a_data_player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ADataPlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpwbGF5ZXIvYV9kYXRhX3BsYXllci5wcm90bxIGcGxheWVyGhRiYWcvYV9k",
            "YXRhX2JhZy5wcm90byLxBAoGUGxheWVyEgsKA3VpZBgBIAEoBBINCgVsZXZl",
            "bBgCIAEoBRIMCgRuYW1lGAMgASgJEhUKA2JhZxgEIAEoCzIILmJhZy5CYWcS",
            "KgoGc2NvcmVzGAUgAygLMhoucGxheWVyLlBsYXllci5TY29yZXNFbnRyeRIV",
            "Cg1yZWNlbnRfbGV2ZWxzGAYgAygFEhgKCnVpZF91cGRhdGUY6QcgASgESAGI",
            "AQESGgoMbGV2ZWxfdXBkYXRlGOoHIAEoBUgCiAEBEhkKC25hbWVfdXBkYXRl",
            "GOsHIAEoCUgDiAEBEhwKB2JhZ19zZXQY7AcgASgLMgguYmFnLkJhZ0gAEhQK",
            "CWJhZ19jbGVhchjUDyABKAhIABIfCgpiYWdfdXBkYXRlGLwXIAEoCzIILmJh",
            "Zy5CYWdIABIVCgxzY29yZXNfY2xlYXIY7QcgASgIEjIKCnNjb3Jlc19zZXQY",
            "1Q8gAygLMh0ucGxheWVyLlBsYXllci5TY29yZXNTZXRFbnRyeRIWCg1zY29y",
            "ZXNfZGVsZXRlGL0XIAMoBBIeChVyZWNlbnRfbGV2ZWxzX3VwZGF0ZWQY7gcg",
            "ASgIEh0KFHJlY2VudF9sZXZlbHNfdXBkYXRlGNYPIAMoBRotCgtTY29yZXNF",
            "bnRyeRILCgNrZXkYASABKAQSDQoFdmFsdWUYAiABKAU6AjgBGjAKDlNjb3Jl",
            "c1NldEVudHJ5EgsKA2tleRgBIAEoBBINCgV2YWx1ZRgCIAEoBToCOAFCCgoI",
            "YmFnX2RpZmZCDQoLX3VpZF91cGRhdGVCDwoNX2xldmVsX3VwZGF0ZUIOCgxf",
            "bmFtZV91cGRhdGVCRFoqZ2l0aHViLmNvbS8yY29tamllL25vdmEvZXhhbXBs",
            "ZXMvcGIvcGxheWVyqgIVTm92YS5HZW5lcmF0ZWQuUGxheWVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Nova.Generated.Bag.ADataBagReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Nova.Generated.Player.Player), global::Nova.Generated.Player.Player.Parser, new[]{ "Uid", "Level", "Name", "Bag", "Scores", "RecentLevels", "UidUpdate", "LevelUpdate", "NameUpdate", "BagSet", "BagClear", "BagUpdate", "ScoresClear", "ScoresSet", "ScoresDelete", "RecentLevelsUpdated", "RecentLevelsUpdate" }, new[]{ "BagDiff", "UidUpdate", "LevelUpdate", "NameUpdate" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Player : pb::IMessage<Player>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Player> _parser = new pb::MessageParser<Player>(() => new Player());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Player> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Nova.Generated.Player.ADataPlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player(Player other) : this() {
      _hasBits0 = other._hasBits0;
      uid_ = other.uid_;
      level_ = other.level_;
      name_ = other.name_;
      bag_ = other.bag_ != null ? other.bag_.Clone() : null;
      scores_ = other.scores_.Clone();
      recentLevels_ = other.recentLevels_.Clone();
      uidUpdate_ = other.uidUpdate_;
      levelUpdate_ = other.levelUpdate_;
      nameUpdate_ = other.nameUpdate_;
      scoresClear_ = other.scoresClear_;
      scoresSet_ = other.scoresSet_.Clone();
      scoresDelete_ = other.scoresDelete_.Clone();
      recentLevelsUpdated_ = other.recentLevelsUpdated_;
      recentLevelsUpdate_ = other.recentLevelsUpdate_.Clone();
      switch (other.BagDiffCase) {
        case BagDiffOneofCase.BagSet:
          BagSet = other.BagSet.Clone();
          break;
        case BagDiffOneofCase.BagClear:
          BagClear = other.BagClear;
          break;
        case BagDiffOneofCase.BagUpdate:
          BagUpdate = other.BagUpdate.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Player Clone() {
      return new Player(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private ulong uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bag" field.</summary>
    public const int BagFieldNumber = 4;
    private global::Nova.Generated.Bag.Bag bag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nova.Generated.Bag.Bag Bag {
      get { return bag_; }
      set {
        bag_ = value;
      }
    }

    /// <summary>Field number for the "scores" field.</summary>
    public const int ScoresFieldNumber = 5;
    private static readonly pbc::MapField<ulong, int>.Codec _map_scores_codec
        = new pbc::MapField<ulong, int>.Codec(pb::FieldCodec.ForUInt64(8, 0UL), pb::FieldCodec.ForInt32(16, 0), 42);
    private readonly pbc::MapField<ulong, int> scores_ = new pbc::MapField<ulong, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<ulong, int> Scores {
      get { return scores_; }
    }

    /// <summary>Field number for the "recent_levels" field.</summary>
    public const int RecentLevelsFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_recentLevels_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> recentLevels_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RecentLevels {
      get { return recentLevels_; }
    }

    /// <summary>Field number for the "uid_update" field.</summary>
    public const int UidUpdateFieldNumber = 1001;
    private readonly static ulong UidUpdateDefaultValue = 0UL;

    private ulong uidUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UidUpdate {
      get { if ((_hasBits0 & 1) != 0) { return uidUpdate_; } else { return UidUpdateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        uidUpdate_ = value;
      }
    }
    /// <summary>Gets whether the "uid_update" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUidUpdate {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "uid_update" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUidUpdate() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "level_update" field.</summary>
    public const int LevelUpdateFieldNumber = 1002;
    private readonly static int LevelUpdateDefaultValue = 0;

    private int levelUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LevelUpdate {
      get { if ((_hasBits0 & 2) != 0) { return levelUpdate_; } else { return LevelUpdateDefaultValue; } }
      set {
        _hasBits0 |= 2;
        levelUpdate_ = value;
      }
    }
    /// <summary>Gets whether the "level_update" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLevelUpdate {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "level_update" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLevelUpdate() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "name_update" field.</summary>
    public const int NameUpdateFieldNumber = 1003;
    private readonly static string NameUpdateDefaultValue = "";

    private string nameUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NameUpdate {
      get { return nameUpdate_ ?? NameUpdateDefaultValue; }
      set {
        nameUpdate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name_update" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNameUpdate {
      get { return nameUpdate_ != null; }
    }
    /// <summary>Clears the value of the "name_update" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNameUpdate() {
      nameUpdate_ = null;
    }

    /// <summary>Field number for the "bag_set" field.</summary>
    public const int BagSetFieldNumber = 1004;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nova.Generated.Bag.Bag BagSet {
      get { return bagDiffCase_ == BagDiffOneofCase.BagSet ? (global::Nova.Generated.Bag.Bag) bagDiff_ : null; }
      set {
        bagDiff_ = value;
        bagDiffCase_ = value == null ? BagDiffOneofCase.None : BagDiffOneofCase.BagSet;
      }
    }

    /// <summary>Field number for the "bag_clear" field.</summary>
    public const int BagClearFieldNumber = 2004;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BagClear {
      get { return HasBagClear ? (bool) bagDiff_ : false; }
      set {
        bagDiff_ = value;
        bagDiffCase_ = BagDiffOneofCase.BagClear;
      }
    }
    /// <summary>Gets whether the "bag_clear" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBagClear {
      get { return bagDiffCase_ == BagDiffOneofCase.BagClear; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "bag_clear" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBagClear() {
      if (HasBagClear) {
        ClearBagDiff();
      }
    }

    /// <summary>Field number for the "bag_update" field.</summary>
    public const int BagUpdateFieldNumber = 3004;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Nova.Generated.Bag.Bag BagUpdate {
      get { return bagDiffCase_ == BagDiffOneofCase.BagUpdate ? (global::Nova.Generated.Bag.Bag) bagDiff_ : null; }
      set {
        bagDiff_ = value;
        bagDiffCase_ = value == null ? BagDiffOneofCase.None : BagDiffOneofCase.BagUpdate;
      }
    }

    /// <summary>Field number for the "scores_clear" field.</summary>
    public const int ScoresClearFieldNumber = 1005;
    private bool scoresClear_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ScoresClear {
      get { return scoresClear_; }
      set {
        scoresClear_ = value;
      }
    }

    /// <summary>Field number for the "scores_set" field.</summary>
    public const int ScoresSetFieldNumber = 2005;
    private static readonly pbc::MapField<ulong, int>.Codec _map_scoresSet_codec
        = new pbc::MapField<ulong, int>.Codec(pb::FieldCodec.ForUInt64(8, 0UL), pb::FieldCodec.ForInt32(16, 0), 16042);
    private readonly pbc::MapField<ulong, int> scoresSet_ = new pbc::MapField<ulong, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<ulong, int> ScoresSet {
      get { return scoresSet_; }
    }

    /// <summary>Field number for the "scores_delete" field.</summary>
    public const int ScoresDeleteFieldNumber = 3005;
    private static readonly pb::FieldCodec<ulong> _repeated_scoresDelete_codec
        = pb::FieldCodec.ForUInt64(24042);
    private readonly pbc::RepeatedField<ulong> scoresDelete_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> ScoresDelete {
      get { return scoresDelete_; }
    }

    /// <summary>Field number for the "recent_levels_updated" field.</summary>
    public const int RecentLevelsUpdatedFieldNumber = 1006;
    private bool recentLevelsUpdated_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RecentLevelsUpdated {
      get { return recentLevelsUpdated_; }
      set {
        recentLevelsUpdated_ = value;
      }
    }

    /// <summary>Field number for the "recent_levels_update" field.</summary>
    public const int RecentLevelsUpdateFieldNumber = 2006;
    private static readonly pb::FieldCodec<int> _repeated_recentLevelsUpdate_codec
        = pb::FieldCodec.ForInt32(16050);
    private readonly pbc::RepeatedField<int> recentLevelsUpdate_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RecentLevelsUpdate {
      get { return recentLevelsUpdate_; }
    }

    private object bagDiff_;
    /// <summary>Enum of possible cases for the "bag_diff" oneof.</summary>
    public enum BagDiffOneofCase {
      None = 0,
      BagSet = 1004,
      BagClear = 2004,
      BagUpdate = 3004,
    }
    private BagDiffOneofCase bagDiffCase_ = BagDiffOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BagDiffOneofCase BagDiffCase {
      get { return bagDiffCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBagDiff() {
      bagDiffCase_ = BagDiffOneofCase.None;
      bagDiff_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Player);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Player other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (Level != other.Level) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Bag, other.Bag)) return false;
      if (!Scores.Equals(other.Scores)) return false;
      if(!recentLevels_.Equals(other.recentLevels_)) return false;
      if (UidUpdate != other.UidUpdate) return false;
      if (LevelUpdate != other.LevelUpdate) return false;
      if (NameUpdate != other.NameUpdate) return false;
      if (!object.Equals(BagSet, other.BagSet)) return false;
      if (BagClear != other.BagClear) return false;
      if (!object.Equals(BagUpdate, other.BagUpdate)) return false;
      if (ScoresClear != other.ScoresClear) return false;
      if (!ScoresSet.Equals(other.ScoresSet)) return false;
      if(!scoresDelete_.Equals(other.scoresDelete_)) return false;
      if (RecentLevelsUpdated != other.RecentLevelsUpdated) return false;
      if(!recentLevelsUpdate_.Equals(other.recentLevelsUpdate_)) return false;
      if (BagDiffCase != other.BagDiffCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0UL) hash ^= Uid.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (bag_ != null) hash ^= Bag.GetHashCode();
      hash ^= Scores.GetHashCode();
      hash ^= recentLevels_.GetHashCode();
      if (HasUidUpdate) hash ^= UidUpdate.GetHashCode();
      if (HasLevelUpdate) hash ^= LevelUpdate.GetHashCode();
      if (HasNameUpdate) hash ^= NameUpdate.GetHashCode();
      if (bagDiffCase_ == BagDiffOneofCase.BagSet) hash ^= BagSet.GetHashCode();
      if (HasBagClear) hash ^= BagClear.GetHashCode();
      if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) hash ^= BagUpdate.GetHashCode();
      if (ScoresClear != false) hash ^= ScoresClear.GetHashCode();
      hash ^= ScoresSet.GetHashCode();
      hash ^= scoresDelete_.GetHashCode();
      if (RecentLevelsUpdated != false) hash ^= RecentLevelsUpdated.GetHashCode();
      hash ^= recentLevelsUpdate_.GetHashCode();
      hash ^= (int) bagDiffCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (bag_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bag);
      }
      scores_.WriteTo(output, _map_scores_codec);
      recentLevels_.WriteTo(output, _repeated_recentLevels_codec);
      if (HasUidUpdate) {
        output.WriteRawTag(200, 62);
        output.WriteUInt64(UidUpdate);
      }
      if (HasLevelUpdate) {
        output.WriteRawTag(208, 62);
        output.WriteInt32(LevelUpdate);
      }
      if (HasNameUpdate) {
        output.WriteRawTag(218, 62);
        output.WriteString(NameUpdate);
      }
      if (bagDiffCase_ == BagDiffOneofCase.BagSet) {
        output.WriteRawTag(226, 62);
        output.WriteMessage(BagSet);
      }
      if (ScoresClear != false) {
        output.WriteRawTag(232, 62);
        output.WriteBool(ScoresClear);
      }
      if (RecentLevelsUpdated != false) {
        output.WriteRawTag(240, 62);
        output.WriteBool(RecentLevelsUpdated);
      }
      if (HasBagClear) {
        output.WriteRawTag(160, 125);
        output.WriteBool(BagClear);
      }
      scoresSet_.WriteTo(output, _map_scoresSet_codec);
      recentLevelsUpdate_.WriteTo(output, _repeated_recentLevelsUpdate_codec);
      if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) {
        output.WriteRawTag(226, 187, 1);
        output.WriteMessage(BagUpdate);
      }
      scoresDelete_.WriteTo(output, _repeated_scoresDelete_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Uid);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (bag_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bag);
      }
      scores_.WriteTo(ref output, _map_scores_codec);
      recentLevels_.WriteTo(ref output, _repeated_recentLevels_codec);
      if (HasUidUpdate) {
        output.WriteRawTag(200, 62);
        output.WriteUInt64(UidUpdate);
      }
      if (HasLevelUpdate) {
        output.WriteRawTag(208, 62);
        output.WriteInt32(LevelUpdate);
      }
      if (HasNameUpdate) {
        output.WriteRawTag(218, 62);
        output.WriteString(NameUpdate);
      }
      if (bagDiffCase_ == BagDiffOneofCase.BagSet) {
        output.WriteRawTag(226, 62);
        output.WriteMessage(BagSet);
      }
      if (ScoresClear != false) {
        output.WriteRawTag(232, 62);
        output.WriteBool(ScoresClear);
      }
      if (RecentLevelsUpdated != false) {
        output.WriteRawTag(240, 62);
        output.WriteBool(RecentLevelsUpdated);
      }
      if (HasBagClear) {
        output.WriteRawTag(160, 125);
        output.WriteBool(BagClear);
      }
      scoresSet_.WriteTo(ref output, _map_scoresSet_codec);
      recentLevelsUpdate_.WriteTo(ref output, _repeated_recentLevelsUpdate_codec);
      if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) {
        output.WriteRawTag(226, 187, 1);
        output.WriteMessage(BagUpdate);
      }
      scoresDelete_.WriteTo(ref output, _repeated_scoresDelete_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Uid);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (bag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bag);
      }
      size += scores_.CalculateSize(_map_scores_codec);
      size += recentLevels_.CalculateSize(_repeated_recentLevels_codec);
      if (HasUidUpdate) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(UidUpdate);
      }
      if (HasLevelUpdate) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(LevelUpdate);
      }
      if (HasNameUpdate) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(NameUpdate);
      }
      if (bagDiffCase_ == BagDiffOneofCase.BagSet) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(BagSet);
      }
      if (HasBagClear) {
        size += 2 + 1;
      }
      if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) {
        size += 3 + pb::CodedOutputStream.ComputeMessageSize(BagUpdate);
      }
      if (ScoresClear != false) {
        size += 2 + 1;
      }
      size += scoresSet_.CalculateSize(_map_scoresSet_codec);
      size += scoresDelete_.CalculateSize(_repeated_scoresDelete_codec);
      if (RecentLevelsUpdated != false) {
        size += 2 + 1;
      }
      size += recentLevelsUpdate_.CalculateSize(_repeated_recentLevelsUpdate_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Player other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0UL) {
        Uid = other.Uid;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.bag_ != null) {
        if (bag_ == null) {
          Bag = new global::Nova.Generated.Bag.Bag();
        }
        Bag.MergeFrom(other.Bag);
      }
      scores_.MergeFrom(other.scores_);
      recentLevels_.Add(other.recentLevels_);
      if (other.HasUidUpdate) {
        UidUpdate = other.UidUpdate;
      }
      if (other.HasLevelUpdate) {
        LevelUpdate = other.LevelUpdate;
      }
      if (other.HasNameUpdate) {
        NameUpdate = other.NameUpdate;
      }
      if (other.ScoresClear != false) {
        ScoresClear = other.ScoresClear;
      }
      scoresSet_.MergeFrom(other.scoresSet_);
      scoresDelete_.Add(other.scoresDelete_);
      if (other.RecentLevelsUpdated != false) {
        RecentLevelsUpdated = other.RecentLevelsUpdated;
      }
      recentLevelsUpdate_.Add(other.recentLevelsUpdate_);
      switch (other.BagDiffCase) {
        case BagDiffOneofCase.BagSet:
          if (BagSet == null) {
            BagSet = new global::Nova.Generated.Bag.Bag();
          }
          BagSet.MergeFrom(other.BagSet);
          break;
        case BagDiffOneofCase.BagClear:
          BagClear = other.BagClear;
          break;
        case BagDiffOneofCase.BagUpdate:
          if (BagUpdate == null) {
            BagUpdate = new global::Nova.Generated.Bag.Bag();
          }
          BagUpdate.MergeFrom(other.BagUpdate);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (bag_ == null) {
              Bag = new global::Nova.Generated.Bag.Bag();
            }
            input.ReadMessage(Bag);
            break;
          }
          case 42: {
            scores_.AddEntriesFrom(input, _map_scores_codec);
            break;
          }
          case 50:
          case 48: {
            recentLevels_.AddEntriesFrom(input, _repeated_recentLevels_codec);
            break;
          }
          case 8008: {
            UidUpdate = input.ReadUInt64();
            break;
          }
          case 8016: {
            LevelUpdate = input.ReadInt32();
            break;
          }
          case 8026: {
            NameUpdate = input.ReadString();
            break;
          }
          case 8034: {
            global::Nova.Generated.Bag.Bag subBuilder = new global::Nova.Generated.Bag.Bag();
            if (bagDiffCase_ == BagDiffOneofCase.BagSet) {
              subBuilder.MergeFrom(BagSet);
            }
            input.ReadMessage(subBuilder);
            BagSet = subBuilder;
            break;
          }
          case 8040: {
            ScoresClear = input.ReadBool();
            break;
          }
          case 8048: {
            RecentLevelsUpdated = input.ReadBool();
            break;
          }
          case 16032: {
            BagClear = input.ReadBool();
            break;
          }
          case 16042: {
            scoresSet_.AddEntriesFrom(input, _map_scoresSet_codec);
            break;
          }
          case 16050:
          case 16048: {
            recentLevelsUpdate_.AddEntriesFrom(input, _repeated_recentLevelsUpdate_codec);
            break;
          }
          case 24034: {
            global::Nova.Generated.Bag.Bag subBuilder = new global::Nova.Generated.Bag.Bag();
            if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) {
              subBuilder.MergeFrom(BagUpdate);
            }
            input.ReadMessage(subBuilder);
            BagUpdate = subBuilder;
            break;
          }
          case 24042:
          case 24040: {
            scoresDelete_.AddEntriesFrom(input, _repeated_scoresDelete_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadUInt64();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (bag_ == null) {
              Bag = new global::Nova.Generated.Bag.Bag();
            }
            input.ReadMessage(Bag);
            break;
          }
          case 42: {
            scores_.AddEntriesFrom(ref input, _map_scores_codec);
            break;
          }
          case 50:
          case 48: {
            recentLevels_.AddEntriesFrom(ref input, _repeated_recentLevels_codec);
            break;
          }
          case 8008: {
            UidUpdate = input.ReadUInt64();
            break;
          }
          case 8016: {
            LevelUpdate = input.ReadInt32();
            break;
          }
          case 8026: {
            NameUpdate = input.ReadString();
            break;
          }
          case 8034: {
            global::Nova.Generated.Bag.Bag subBuilder = new global::Nova.Generated.Bag.Bag();
            if (bagDiffCase_ == BagDiffOneofCase.BagSet) {
              subBuilder.MergeFrom(BagSet);
            }
            input.ReadMessage(subBuilder);
            BagSet = subBuilder;
            break;
          }
          case 8040: {
            ScoresClear = input.ReadBool();
            break;
          }
          case 8048: {
            RecentLevelsUpdated = input.ReadBool();
            break;
          }
          case 16032: {
            BagClear = input.ReadBool();
            break;
          }
          case 16042: {
            scoresSet_.AddEntriesFrom(ref input, _map_scoresSet_codec);
            break;
          }
          case 16050:
          case 16048: {
            recentLevelsUpdate_.AddEntriesFrom(ref input, _repeated_recentLevelsUpdate_codec);
            break;
          }
          case 24034: {
            global::Nova.Generated.Bag.Bag subBuilder = new global::Nova.Generated.Bag.Bag();
            if (bagDiffCase_ == BagDiffOneofCase.BagUpdate) {
              subBuilder.MergeFrom(BagUpdate);
            }
            input.ReadMessage(subBuilder);
            BagUpdate = subBuilder;
            break;
          }
          case 24042:
          case 24040: {
            scoresDelete_.AddEntriesFrom(ref input, _repeated_scoresDelete_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
