syntax = "proto3";

package transport.gate;

option go_package = "github.com/2comjie/wali/pb/transport/gate;pbGate";

message BindUidRequest {
  string uid = 1;
  int64 conn_id = 2;
}
message BindUidResponse {
}

message UnbindUidRequest {
  int64 conn_id = 1;
}
message UnbindUidResponse {
  string uid = 1;
}

message PushRequest {
  string uid = 1;
  int64 conn_id = 2;
  bytes message = 3;
}
message PushMessageResponse {
}

message BroadCastRequest {
  bytes message = 1;
}
message BroadCastResponse {
  int64 count = 1;
  int64 total = 2;
}

message MultiCastRequest {
  repeated string  uids = 1;
  repeated int64 conn_ids = 2;
  bytes message = 3;
}
message MultiCastResponse {
  int64 count = 1;
  int64 total = 2;
}

message KickRequest {
  int64 conn_id = 1;
  string uid = 2;
  string reason = 3;
}
message KickResponse {
}

message StatRequest {
}
message StatResponse {
  int64 total = 1;
}

message GetIPRequest{
  int64 conn_id = 1;
  string uid = 2;
}
message GetIPResponse{
  string ip = 1;
}

message IsOnlineRequest{
  int64 conn_id = 1;
  string uid = 2;
}
message IsOnlineResponse{
  bool online = 1;
}

service GateService {
  rpc BindUid(BindUidRequest) returns (BindUidResponse);
  rpc UnbindUid(UnbindUidRequest) returns (UnbindUidResponse);
  rpc Push(PushRequest) returns (PushMessageResponse);
  rpc BroadCast(BroadCastRequest) returns (BroadCastResponse);
  rpc MultiCast(MultiCastRequest) returns (MultiCastResponse);
  rpc Kick(KickRequest) returns (KickResponse);
  rpc Stat(StatRequest) returns (StatResponse);
  rpc GetIP(GetIPRequest) returns (GetIPResponse);
  rpc IsOnline(IsOnlineRequest) returns (IsOnlineResponse);
}
