// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: proto/network/control.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindCode int32

const (
	BindCode_BIND_OK           BindCode = 0
	BindCode_BIND_UNAUTHORIZED BindCode = 1
)

// Enum value maps for BindCode.
var (
	BindCode_name = map[int32]string{
		0: "BIND_OK",
		1: "BIND_UNAUTHORIZED",
	}
	BindCode_value = map[string]int32{
		"BIND_OK":           0,
		"BIND_UNAUTHORIZED": 1,
	}
)

func (x BindCode) Enum() *BindCode {
	p := new(BindCode)
	*p = x
	return p
}

func (x BindCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_network_control_proto_enumTypes[0].Descriptor()
}

func (BindCode) Type() protoreflect.EnumType {
	return &file_proto_network_control_proto_enumTypes[0]
}

func (x BindCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindCode.Descriptor instead.
func (BindCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_network_control_proto_rawDescGZIP(), []int{0}
}

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_proto_network_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_control_proto_rawDescGZIP(), []int{0}
}

func (x *BindRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type BindResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Code                   BindCode               `protobuf:"varint,1,opt,name=code,proto3,enum=wali.network.BindCode" json:"code,omitempty"`
	HeartbeatIntervalMilli uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_milli,json=heartbeatIntervalMilli,proto3" json:"heartbeat_interval_milli,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_proto_network_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_control_proto_rawDescGZIP(), []int{1}
}

func (x *BindResponse) GetCode() BindCode {
	if x != nil {
		return x.Code
	}
	return BindCode_BIND_OK
}

func (x *BindResponse) GetHeartbeatIntervalMilli() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMilli
	}
	return 0
}

var File_proto_network_control_proto protoreflect.FileDescriptor

const file_proto_network_control_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/network/control.proto\x12\fwali.network\"#\n" +
	"\vBindRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"t\n" +
	"\fBindResponse\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.wali.network.BindCodeR\x04code\x128\n" +
	"\x18heartbeat_interval_milli\x18\x02 \x01(\rR\x16heartbeatIntervalMilli*.\n" +
	"\bBindCode\x12\v\n" +
	"\aBIND_OK\x10\x00\x12\x15\n" +
	"\x11BIND_UNAUTHORIZED\x10\x01B3Z1github.com/2comjie/wali/network/protocol;protocolb\x06proto3"

var (
	file_proto_network_control_proto_rawDescOnce sync.Once
	file_proto_network_control_proto_rawDescData []byte
)

func file_proto_network_control_proto_rawDescGZIP() []byte {
	file_proto_network_control_proto_rawDescOnce.Do(func() {
		file_proto_network_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_control_proto_rawDesc), len(file_proto_network_control_proto_rawDesc)))
	})
	return file_proto_network_control_proto_rawDescData
}

var file_proto_network_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_network_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_network_control_proto_goTypes = []any{
	(BindCode)(0),        // 0: wali.network.BindCode
	(*BindRequest)(nil),  // 1: wali.network.BindRequest
	(*BindResponse)(nil), // 2: wali.network.BindResponse
}
var file_proto_network_control_proto_depIdxs = []int32{
	0, // 0: wali.network.BindResponse.code:type_name -> wali.network.BindCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_network_control_proto_init() }
func file_proto_network_control_proto_init() {
	if File_proto_network_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_control_proto_rawDesc), len(file_proto_network_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_network_control_proto_goTypes,
		DependencyIndexes: file_proto_network_control_proto_depIdxs,
		EnumInfos:         file_proto_network_control_proto_enumTypes,
		MessageInfos:      file_proto_network_control_proto_msgTypes,
	}.Build()
	File_proto_network_control_proto = out.File
	file_proto_network_control_proto_goTypes = nil
	file_proto_network_control_proto_depIdxs = nil
}
