// Code generated by diff-gen. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: item/a_data_item.proto

package item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint64                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ItemIdUpdate  *uint64                `protobuf:"varint,1001,opt,name=item_id_update,json=itemIdUpdate,proto3,oneof" json:"item_id_update,omitempty"`
	CountUpdate   *int32                 `protobuf:"varint,1002,opt,name=count_update,json=countUpdate,proto3,oneof" json:"count_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_a_data_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_a_data_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_a_data_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetItemIdUpdate() uint64 {
	if x != nil && x.ItemIdUpdate != nil {
		return *x.ItemIdUpdate
	}
	return 0
}

func (x *Item) GetCountUpdate() int32 {
	if x != nil && x.CountUpdate != nil {
		return *x.CountUpdate
	}
	return 0
}

var File_item_a_data_item_proto protoreflect.FileDescriptor

const file_item_a_data_item_proto_rawDesc = "" +
	"\n" +
	"\x16item/a_data_item.proto\x12\x04item\"\xae\x01\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x04R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12*\n" +
	"\x0eitem_id_update\x18\xe9\a \x01(\x04H\x00R\fitemIdUpdate\x88\x01\x01\x12'\n" +
	"\fcount_update\x18\xea\a \x01(\x05H\x01R\vcountUpdate\x88\x01\x01B\x11\n" +
	"\x0f_item_id_updateB\x0f\n" +
	"\r_count_updateB@Z(github.com/2comjie/nova/examples/pb/item\xaa\x02\x13Nova.Generated.Itemb\x06proto3"

var (
	file_item_a_data_item_proto_rawDescOnce sync.Once
	file_item_a_data_item_proto_rawDescData []byte
)

func file_item_a_data_item_proto_rawDescGZIP() []byte {
	file_item_a_data_item_proto_rawDescOnce.Do(func() {
		file_item_a_data_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_a_data_item_proto_rawDesc), len(file_item_a_data_item_proto_rawDesc)))
	})
	return file_item_a_data_item_proto_rawDescData
}

var file_item_a_data_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_item_a_data_item_proto_goTypes = []any{
	(*Item)(nil), // 0: item.Item
}
var file_item_a_data_item_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_item_a_data_item_proto_init() }
func file_item_a_data_item_proto_init() {
	if File_item_a_data_item_proto != nil {
		return
	}
	file_item_a_data_item_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_a_data_item_proto_rawDesc), len(file_item_a_data_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_a_data_item_proto_goTypes,
		DependencyIndexes: file_item_a_data_item_proto_depIdxs,
		MessageInfos:      file_item_a_data_item_proto_msgTypes,
	}.Build()
	File_item_a_data_item_proto = out.File
	file_item_a_data_item_proto_goTypes = nil
	file_item_a_data_item_proto_depIdxs = nil
}
