// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: transport/node/node.proto

package pbNode

import (
	request "github.com/2comjie/wali/pb/transport/request"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleClientMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *request.Request       `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleClientMessageRequest) Reset() {
	*x = HandleClientMessageRequest{}
	mi := &file_transport_node_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleClientMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleClientMessageRequest) ProtoMessage() {}

func (x *HandleClientMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_node_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleClientMessageRequest.ProtoReflect.Descriptor instead.
func (*HandleClientMessageRequest) Descriptor() ([]byte, []int) {
	return file_transport_node_node_proto_rawDescGZIP(), []int{0}
}

func (x *HandleClientMessageRequest) GetRequest() *request.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type HandleClientMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *request.Response      `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleClientMessageResponse) Reset() {
	*x = HandleClientMessageResponse{}
	mi := &file_transport_node_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleClientMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleClientMessageResponse) ProtoMessage() {}

func (x *HandleClientMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_node_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleClientMessageResponse.ProtoReflect.Descriptor instead.
func (*HandleClientMessageResponse) Descriptor() ([]byte, []int) {
	return file_transport_node_node_proto_rawDescGZIP(), []int{1}
}

func (x *HandleClientMessageResponse) GetResponse() *request.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_transport_node_node_proto protoreflect.FileDescriptor

const file_transport_node_node_proto_rawDesc = "" +
	"\n" +
	"\x19transport/node/node.proto\x12\x0etransport.node\x1a\x1ftransport/request/request.proto\"R\n" +
	"\x1aHandleClientMessageRequest\x124\n" +
	"\arequest\x18\x01 \x01(\v2\x1a.transport.request.RequestR\arequest\"V\n" +
	"\x1bHandleClientMessageResponse\x127\n" +
	"\bresponse\x18\x01 \x01(\v2\x1b.transport.request.ResponseR\bresponse2}\n" +
	"\vNodeService\x12n\n" +
	"\x13HandleClientMessage\x12*.transport.node.HandleClientMessageRequest\x1a+.transport.node.HandleClientMessageResponseB2Z0github.com/2comjie/wali/pb/transport/node;pbNodeb\x06proto3"

var (
	file_transport_node_node_proto_rawDescOnce sync.Once
	file_transport_node_node_proto_rawDescData []byte
)

func file_transport_node_node_proto_rawDescGZIP() []byte {
	file_transport_node_node_proto_rawDescOnce.Do(func() {
		file_transport_node_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_node_node_proto_rawDesc), len(file_transport_node_node_proto_rawDesc)))
	})
	return file_transport_node_node_proto_rawDescData
}

var file_transport_node_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_node_node_proto_goTypes = []any{
	(*HandleClientMessageRequest)(nil),  // 0: transport.node.HandleClientMessageRequest
	(*HandleClientMessageResponse)(nil), // 1: transport.node.HandleClientMessageResponse
	(*request.Request)(nil),             // 2: transport.request.Request
	(*request.Response)(nil),            // 3: transport.request.Response
}
var file_transport_node_node_proto_depIdxs = []int32{
	2, // 0: transport.node.HandleClientMessageRequest.request:type_name -> transport.request.Request
	3, // 1: transport.node.HandleClientMessageResponse.response:type_name -> transport.request.Response
	0, // 2: transport.node.NodeService.HandleClientMessage:input_type -> transport.node.HandleClientMessageRequest
	1, // 3: transport.node.NodeService.HandleClientMessage:output_type -> transport.node.HandleClientMessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transport_node_node_proto_init() }
func file_transport_node_node_proto_init() {
	if File_transport_node_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_node_node_proto_rawDesc), len(file_transport_node_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_node_node_proto_goTypes,
		DependencyIndexes: file_transport_node_node_proto_depIdxs,
		MessageInfos:      file_transport_node_node_proto_msgTypes,
	}.Build()
	File_transport_node_node_proto = out.File
	file_transport_node_node_proto_goTypes = nil
	file_transport_node_node_proto_depIdxs = nil
}
