// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: transport/node/node.proto

package pbNode

import (
	context "context"
	app "github.com/2comjie/wali/app"
	endpoint "github.com/2comjie/wali/core/endpoint"
	client "github.com/2comjie/wali/rpc/client"
	lx "github.com/2comjie/wali/rpc/lx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_ServiceName                        = "transport.node.NodeService"
	NodeService_HandleClientMessage_FullMethodName = "/transport.node.NodeService/HandleClientMessage"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	HandleClientMessage(ctx context.Context, in *HandleClientMessageRequest, opts ...grpc.CallOption) (*HandleClientMessageResponse, error)
}

type nodeServiceClient struct {
	cc *client.Client
}

func NewNodeServiceClient(cc *client.Client) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) conn(ctx context.Context) (*grpc.ClientConn, error) {
	if cfg := lx.FromContext(ctx); cfg != nil {
		switch cfg.Mode {
		case lx.ModeDirect:
			return c.cc.Direct(ctx, cfg.Target)
		case lx.ModeNode:
			return c.cc.Node(ctx, NodeService_ServiceName, cfg.Target)
		case lx.ModeKey:
			return c.cc.Route(ctx, cfg.Name, cfg.Key, NodeService_ServiceName)
		}
	}
	return c.cc.Service(ctx, NodeService_ServiceName)
}

func (c *nodeServiceClient) HandleClientMessage(ctx context.Context, in *HandleClientMessageRequest, opts ...grpc.CallOption) (*HandleClientMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleClientMessageResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, NodeService_HandleClientMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	HandleClientMessage(context.Context, *HandleClientMessageRequest) (*HandleClientMessageResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) HandleClientMessage(context.Context, *HandleClientMessageRequest) (*HandleClientMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleClientMessage not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func NewNodeServiceRpcService(desc string) endpoint.RpcService {
	return endpoint.RpcService{
		Name: NodeService_ServiceName,
		Desc: desc,
	}
}

func RegisterNodeServiceRpcService(app app.App, srv NodeServiceServer, host string, port int, desc string) {
	app.RegisterRpcService(host, port, NewNodeServiceRpcService(desc), func(registrar grpc.ServiceRegistrar) {
		RegisterNodeServiceServer(registrar, srv)
	})
}

func _NodeService_HandleClientMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleClientMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandleClientMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_HandleClientMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandleClientMessage(ctx, req.(*HandleClientMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleClientMessage",
			Handler:    _NodeService_HandleClientMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/node/node.proto",
}
