//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package basic

import (
	diff "github.com/2comjie/nova/diff"
)

type Child struct {
	diff.Object

	count diff.Primitive[int32] `diff:"1"`
}

func (value *Child) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}

	value.Object.Init(writer)

	value.count.Init(&value.Object, 1)

}

func (value *Child) GetCount() int32 {
	return value.count.GetValue()
}

func (value *Child) SetCount(fieldValue int32) bool {
	value.InitLink(nil)
	return value.count.SetValue(fieldValue)
}
