// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: diff/testdata/bag.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bag           *Bag                   `protobuf:"bytes,1,opt,name=bag,proto3" json:"bag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_diff_testdata_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_diff_testdata_bag_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetBag() *Bag {
	if x != nil {
		return x.Bag
	}
	return nil
}

type Bag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      int32                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Items         map[uint64]*Item       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Order         []uint64               `protobuf:"varint,3,rep,packed,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bag) Reset() {
	*x = Bag{}
	mi := &file_diff_testdata_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bag) ProtoMessage() {}

func (x *Bag) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bag.ProtoReflect.Descriptor instead.
func (*Bag) Descriptor() ([]byte, []int) {
	return file_diff_testdata_bag_proto_rawDescGZIP(), []int{1}
}

func (x *Bag) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Bag) GetItems() map[uint64]*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Bag) GetOrder() []uint64 {
	if x != nil {
		return x.Order
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_diff_testdata_bag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_bag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_diff_testdata_bag_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_diff_testdata_bag_proto protoreflect.FileDescriptor

const file_diff_testdata_bag_proto_rawDesc = "" +
	"\n" +
	"\x17diff/testdata/bag.proto\x12\x12nova.diff.testdata\"3\n" +
	"\x06Player\x12)\n" +
	"\x03bag\x18\x01 \x01(\v2\x17.nova.diff.testdata.BagR\x03bag\"\xc5\x01\n" +
	"\x03Bag\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x05R\bcapacity\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".nova.diff.testdata.Bag.ItemsEntryR\x05items\x12\x14\n" +
	"\x05order\x18\x03 \x03(\x04R\x05order\x1aR\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.nova.diff.testdata.ItemR\x05value:\x028\x01\"B\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05levelB0Z.github.com/2comjie/nova/diff/testdata;testdatab\x06proto3"

var (
	file_diff_testdata_bag_proto_rawDescOnce sync.Once
	file_diff_testdata_bag_proto_rawDescData []byte
)

func file_diff_testdata_bag_proto_rawDescGZIP() []byte {
	file_diff_testdata_bag_proto_rawDescOnce.Do(func() {
		file_diff_testdata_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diff_testdata_bag_proto_rawDesc), len(file_diff_testdata_bag_proto_rawDesc)))
	})
	return file_diff_testdata_bag_proto_rawDescData
}

var file_diff_testdata_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_diff_testdata_bag_proto_goTypes = []any{
	(*Player)(nil), // 0: nova.diff.testdata.Player
	(*Bag)(nil),    // 1: nova.diff.testdata.Bag
	(*Item)(nil),   // 2: nova.diff.testdata.Item
	nil,            // 3: nova.diff.testdata.Bag.ItemsEntry
}
var file_diff_testdata_bag_proto_depIdxs = []int32{
	1, // 0: nova.diff.testdata.Player.bag:type_name -> nova.diff.testdata.Bag
	3, // 1: nova.diff.testdata.Bag.items:type_name -> nova.diff.testdata.Bag.ItemsEntry
	2, // 2: nova.diff.testdata.Bag.ItemsEntry.value:type_name -> nova.diff.testdata.Item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_diff_testdata_bag_proto_init() }
func file_diff_testdata_bag_proto_init() {
	if File_diff_testdata_bag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_testdata_bag_proto_rawDesc), len(file_diff_testdata_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_testdata_bag_proto_goTypes,
		DependencyIndexes: file_diff_testdata_bag_proto_depIdxs,
		MessageInfos:      file_diff_testdata_bag_proto_msgTypes,
	}.Build()
	File_diff_testdata_bag_proto = out.File
	file_diff_testdata_bag_proto_goTypes = nil
	file_diff_testdata_bag_proto_depIdxs = nil
}
