// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: diff/testdata/complex.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemQuality int32

const (
	ItemQuality_ITEM_QUALITY_UNKNOWN ItemQuality = 0
	ItemQuality_ITEM_QUALITY_COMMON  ItemQuality = 1
	ItemQuality_ITEM_QUALITY_RARE    ItemQuality = 2
	ItemQuality_ITEM_QUALITY_EPIC    ItemQuality = 3
)

// Enum value maps for ItemQuality.
var (
	ItemQuality_name = map[int32]string{
		0: "ITEM_QUALITY_UNKNOWN",
		1: "ITEM_QUALITY_COMMON",
		2: "ITEM_QUALITY_RARE",
		3: "ITEM_QUALITY_EPIC",
	}
	ItemQuality_value = map[string]int32{
		"ITEM_QUALITY_UNKNOWN": 0,
		"ITEM_QUALITY_COMMON":  1,
		"ITEM_QUALITY_RARE":    2,
		"ITEM_QUALITY_EPIC":    3,
	}
)

func (x ItemQuality) Enum() *ItemQuality {
	p := new(ItemQuality)
	*p = x
	return p
}

func (x ItemQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_diff_testdata_complex_proto_enumTypes[0].Descriptor()
}

func (ItemQuality) Type() protoreflect.EnumType {
	return &file_diff_testdata_complex_proto_enumTypes[0]
}

func (x ItemQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemQuality.Descriptor instead.
func (ItemQuality) EnumDescriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{0}
}

type GameData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Scalars       *ScalarValues             `protobuf:"bytes,1,opt,name=scalars,proto3" json:"scalars,omitempty"`
	Profile       *Profile                  `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Items         map[uint64]*InventoryItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Currencies    map[string]int64          `protobuf:"bytes,4,rep,name=currencies,proto3" json:"currencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Snapshots     map[int32][]byte          `protobuf:"bytes,5,rep,name=snapshots,proto3" json:"snapshots,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FeatureFlags  map[bool]string           `protobuf:"bytes,6,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Checkpoints   []int64                   `protobuf:"varint,7,rep,packed,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	Labels        []string                  `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	Packets       [][]byte                  `protobuf:"bytes,9,rep,name=packets,proto3" json:"packets,omitempty"`
	Lineup        []*InventoryItem          `protobuf:"bytes,10,rep,name=lineup,proto3" json:"lineup,omitempty"`
	Qualities     []ItemQuality             `protobuf:"varint,11,rep,packed,name=qualities,proto3,enum=nova.diff.testdata.ItemQuality" json:"qualities,omitempty"`
	Wide          *WideState                `protobuf:"bytes,12,opt,name=wide,proto3" json:"wide,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameData) Reset() {
	*x = GameData{}
	mi := &file_diff_testdata_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameData) ProtoMessage() {}

func (x *GameData) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameData.ProtoReflect.Descriptor instead.
func (*GameData) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{0}
}

func (x *GameData) GetScalars() *ScalarValues {
	if x != nil {
		return x.Scalars
	}
	return nil
}

func (x *GameData) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GameData) GetItems() map[uint64]*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GameData) GetCurrencies() map[string]int64 {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *GameData) GetSnapshots() map[int32][]byte {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *GameData) GetFeatureFlags() map[bool]string {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

func (x *GameData) GetCheckpoints() []int64 {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *GameData) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GameData) GetPackets() [][]byte {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *GameData) GetLineup() []*InventoryItem {
	if x != nil {
		return x.Lineup
	}
	return nil
}

func (x *GameData) GetQualities() []ItemQuality {
	if x != nil {
		return x.Qualities
	}
	return nil
}

func (x *GameData) GetWide() *WideState {
	if x != nil {
		return x.Wide
	}
	return nil
}

type ScalarValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Quality       ItemQuality            `protobuf:"varint,2,opt,name=quality,proto3,enum=nova.diff.testdata.ItemQuality" json:"quality,omitempty"`
	Int32Value    int32                  `protobuf:"varint,3,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Sint32Value   int32                  `protobuf:"zigzag32,4,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sfixed32Value int32                  `protobuf:"fixed32,5,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Uint32Value   uint32                 `protobuf:"varint,6,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Fixed32Value  uint32                 `protobuf:"fixed32,7,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	Int64Value    int64                  `protobuf:"varint,8,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Sint64Value   int64                  `protobuf:"zigzag64,9,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	Sfixed64Value int64                  `protobuf:"fixed64,10,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Uint64Value   uint64                 `protobuf:"varint,11,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Fixed64Value  uint64                 `protobuf:"fixed64,12,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	FloatValue    float32                `protobuf:"fixed32,13,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue   float64                `protobuf:"fixed64,14,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	StringValue   string                 `protobuf:"bytes,15,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    []byte                 `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarValues) Reset() {
	*x = ScalarValues{}
	mi := &file_diff_testdata_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarValues) ProtoMessage() {}

func (x *ScalarValues) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarValues.ProtoReflect.Descriptor instead.
func (*ScalarValues) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{1}
}

func (x *ScalarValues) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScalarValues) GetQuality() ItemQuality {
	if x != nil {
		return x.Quality
	}
	return ItemQuality_ITEM_QUALITY_UNKNOWN
}

func (x *ScalarValues) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *ScalarValues) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *ScalarValues) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *ScalarValues) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *ScalarValues) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *ScalarValues) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *ScalarValues) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *ScalarValues) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *ScalarValues) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *ScalarValues) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *ScalarValues) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *ScalarValues) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *ScalarValues) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ScalarValues) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_diff_testdata_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{2}
}

func (x *Profile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Profile) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Profile) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	ZipCode       uint32                 `protobuf:"varint,3,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_diff_testdata_complex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZipCode() uint32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Quality       ItemQuality            `protobuf:"varint,3,opt,name=quality,proto3,enum=nova.diff.testdata.ItemQuality" json:"quality,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Attr          *ItemAttr              `protobuf:"bytes,6,opt,name=attr,proto3" json:"attr,omitempty"`
	Effects       map[int32]*ItemEffect  `protobuf:"bytes,7,rep,name=effects,proto3" json:"effects,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Gems          []*ItemGem             `protobuf:"bytes,8,rep,name=gems,proto3" json:"gems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_diff_testdata_complex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InventoryItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InventoryItem) GetQuality() ItemQuality {
	if x != nil {
		return x.Quality
	}
	return ItemQuality_ITEM_QUALITY_UNKNOWN
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InventoryItem) GetAttr() *ItemAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *InventoryItem) GetEffects() map[int32]*ItemEffect {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *InventoryItem) GetGems() []*ItemGem {
	if x != nil {
		return x.Gems
	}
	return nil
}

type ItemAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Durability    int32                  `protobuf:"varint,2,opt,name=durability,proto3" json:"durability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAttr) Reset() {
	*x = ItemAttr{}
	mi := &file_diff_testdata_complex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAttr) ProtoMessage() {}

func (x *ItemAttr) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAttr.ProtoReflect.Descriptor instead.
func (*ItemAttr) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{5}
}

func (x *ItemAttr) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ItemAttr) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

type ItemEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Power         int32                  `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEffect) Reset() {
	*x = ItemEffect{}
	mi := &file_diff_testdata_complex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEffect) ProtoMessage() {}

func (x *ItemEffect) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEffect.ProtoReflect.Descriptor instead.
func (*ItemEffect) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{6}
}

func (x *ItemEffect) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemEffect) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

type ItemGem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemGem) Reset() {
	*x = ItemGem{}
	mi := &file_diff_testdata_complex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemGem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemGem) ProtoMessage() {}

func (x *ItemGem) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemGem.ProtoReflect.Descriptor instead.
func (*ItemGem) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{7}
}

func (x *ItemGem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemGem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type WideState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V1            int32                  `protobuf:"varint,1,opt,name=v1,proto3" json:"v1,omitempty"`
	V2            int32                  `protobuf:"varint,2,opt,name=v2,proto3" json:"v2,omitempty"`
	V3            int32                  `protobuf:"varint,3,opt,name=v3,proto3" json:"v3,omitempty"`
	V4            int32                  `protobuf:"varint,4,opt,name=v4,proto3" json:"v4,omitempty"`
	V5            int32                  `protobuf:"varint,5,opt,name=v5,proto3" json:"v5,omitempty"`
	V6            int32                  `protobuf:"varint,6,opt,name=v6,proto3" json:"v6,omitempty"`
	V7            int32                  `protobuf:"varint,7,opt,name=v7,proto3" json:"v7,omitempty"`
	V8            int32                  `protobuf:"varint,8,opt,name=v8,proto3" json:"v8,omitempty"`
	V9            int32                  `protobuf:"varint,9,opt,name=v9,proto3" json:"v9,omitempty"`
	V10           int32                  `protobuf:"varint,10,opt,name=v10,proto3" json:"v10,omitempty"`
	V11           int32                  `protobuf:"varint,11,opt,name=v11,proto3" json:"v11,omitempty"`
	V12           int32                  `protobuf:"varint,12,opt,name=v12,proto3" json:"v12,omitempty"`
	V13           int32                  `protobuf:"varint,13,opt,name=v13,proto3" json:"v13,omitempty"`
	V14           int32                  `protobuf:"varint,14,opt,name=v14,proto3" json:"v14,omitempty"`
	V15           int32                  `protobuf:"varint,15,opt,name=v15,proto3" json:"v15,omitempty"`
	V16           int32                  `protobuf:"varint,16,opt,name=v16,proto3" json:"v16,omitempty"`
	V17           int32                  `protobuf:"varint,17,opt,name=v17,proto3" json:"v17,omitempty"`
	V18           int32                  `protobuf:"varint,18,opt,name=v18,proto3" json:"v18,omitempty"`
	V19           int32                  `protobuf:"varint,19,opt,name=v19,proto3" json:"v19,omitempty"`
	V20           int32                  `protobuf:"varint,20,opt,name=v20,proto3" json:"v20,omitempty"`
	V21           int32                  `protobuf:"varint,21,opt,name=v21,proto3" json:"v21,omitempty"`
	V22           int32                  `protobuf:"varint,22,opt,name=v22,proto3" json:"v22,omitempty"`
	V23           int32                  `protobuf:"varint,23,opt,name=v23,proto3" json:"v23,omitempty"`
	V24           int32                  `protobuf:"varint,24,opt,name=v24,proto3" json:"v24,omitempty"`
	V25           int32                  `protobuf:"varint,25,opt,name=v25,proto3" json:"v25,omitempty"`
	V26           int32                  `protobuf:"varint,26,opt,name=v26,proto3" json:"v26,omitempty"`
	V27           int32                  `protobuf:"varint,27,opt,name=v27,proto3" json:"v27,omitempty"`
	V28           int32                  `protobuf:"varint,28,opt,name=v28,proto3" json:"v28,omitempty"`
	V29           int32                  `protobuf:"varint,29,opt,name=v29,proto3" json:"v29,omitempty"`
	V30           int32                  `protobuf:"varint,30,opt,name=v30,proto3" json:"v30,omitempty"`
	V31           int32                  `protobuf:"varint,31,opt,name=v31,proto3" json:"v31,omitempty"`
	V32           int32                  `protobuf:"varint,32,opt,name=v32,proto3" json:"v32,omitempty"`
	V33           int32                  `protobuf:"varint,33,opt,name=v33,proto3" json:"v33,omitempty"`
	V34           int32                  `protobuf:"varint,34,opt,name=v34,proto3" json:"v34,omitempty"`
	V35           int32                  `protobuf:"varint,35,opt,name=v35,proto3" json:"v35,omitempty"`
	V36           int32                  `protobuf:"varint,36,opt,name=v36,proto3" json:"v36,omitempty"`
	V37           int32                  `protobuf:"varint,37,opt,name=v37,proto3" json:"v37,omitempty"`
	V38           int32                  `protobuf:"varint,38,opt,name=v38,proto3" json:"v38,omitempty"`
	V39           int32                  `protobuf:"varint,39,opt,name=v39,proto3" json:"v39,omitempty"`
	V40           int32                  `protobuf:"varint,40,opt,name=v40,proto3" json:"v40,omitempty"`
	V41           int32                  `protobuf:"varint,41,opt,name=v41,proto3" json:"v41,omitempty"`
	V42           int32                  `protobuf:"varint,42,opt,name=v42,proto3" json:"v42,omitempty"`
	V43           int32                  `protobuf:"varint,43,opt,name=v43,proto3" json:"v43,omitempty"`
	V44           int32                  `protobuf:"varint,44,opt,name=v44,proto3" json:"v44,omitempty"`
	V45           int32                  `protobuf:"varint,45,opt,name=v45,proto3" json:"v45,omitempty"`
	V46           int32                  `protobuf:"varint,46,opt,name=v46,proto3" json:"v46,omitempty"`
	V47           int32                  `protobuf:"varint,47,opt,name=v47,proto3" json:"v47,omitempty"`
	V48           int32                  `protobuf:"varint,48,opt,name=v48,proto3" json:"v48,omitempty"`
	V49           int32                  `protobuf:"varint,49,opt,name=v49,proto3" json:"v49,omitempty"`
	V50           int32                  `protobuf:"varint,50,opt,name=v50,proto3" json:"v50,omitempty"`
	V51           int32                  `protobuf:"varint,51,opt,name=v51,proto3" json:"v51,omitempty"`
	V52           int32                  `protobuf:"varint,52,opt,name=v52,proto3" json:"v52,omitempty"`
	V53           int32                  `protobuf:"varint,53,opt,name=v53,proto3" json:"v53,omitempty"`
	V54           int32                  `protobuf:"varint,54,opt,name=v54,proto3" json:"v54,omitempty"`
	V55           int32                  `protobuf:"varint,55,opt,name=v55,proto3" json:"v55,omitempty"`
	V56           int32                  `protobuf:"varint,56,opt,name=v56,proto3" json:"v56,omitempty"`
	V57           int32                  `protobuf:"varint,57,opt,name=v57,proto3" json:"v57,omitempty"`
	V58           int32                  `protobuf:"varint,58,opt,name=v58,proto3" json:"v58,omitempty"`
	V59           int32                  `protobuf:"varint,59,opt,name=v59,proto3" json:"v59,omitempty"`
	V60           int32                  `protobuf:"varint,60,opt,name=v60,proto3" json:"v60,omitempty"`
	V61           int32                  `protobuf:"varint,61,opt,name=v61,proto3" json:"v61,omitempty"`
	V62           int32                  `protobuf:"varint,62,opt,name=v62,proto3" json:"v62,omitempty"`
	V63           int32                  `protobuf:"varint,63,opt,name=v63,proto3" json:"v63,omitempty"`
	V64           int32                  `protobuf:"varint,64,opt,name=v64,proto3" json:"v64,omitempty"`
	V65           int32                  `protobuf:"varint,65,opt,name=v65,proto3" json:"v65,omitempty"`
	V66           int32                  `protobuf:"varint,66,opt,name=v66,proto3" json:"v66,omitempty"`
	V67           int32                  `protobuf:"varint,67,opt,name=v67,proto3" json:"v67,omitempty"`
	V68           int32                  `protobuf:"varint,68,opt,name=v68,proto3" json:"v68,omitempty"`
	V69           int32                  `protobuf:"varint,69,opt,name=v69,proto3" json:"v69,omitempty"`
	V70           int32                  `protobuf:"varint,70,opt,name=v70,proto3" json:"v70,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WideState) Reset() {
	*x = WideState{}
	mi := &file_diff_testdata_complex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WideState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WideState) ProtoMessage() {}

func (x *WideState) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_complex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WideState.ProtoReflect.Descriptor instead.
func (*WideState) Descriptor() ([]byte, []int) {
	return file_diff_testdata_complex_proto_rawDescGZIP(), []int{8}
}

func (x *WideState) GetV1() int32 {
	if x != nil {
		return x.V1
	}
	return 0
}

func (x *WideState) GetV2() int32 {
	if x != nil {
		return x.V2
	}
	return 0
}

func (x *WideState) GetV3() int32 {
	if x != nil {
		return x.V3
	}
	return 0
}

func (x *WideState) GetV4() int32 {
	if x != nil {
		return x.V4
	}
	return 0
}

func (x *WideState) GetV5() int32 {
	if x != nil {
		return x.V5
	}
	return 0
}

func (x *WideState) GetV6() int32 {
	if x != nil {
		return x.V6
	}
	return 0
}

func (x *WideState) GetV7() int32 {
	if x != nil {
		return x.V7
	}
	return 0
}

func (x *WideState) GetV8() int32 {
	if x != nil {
		return x.V8
	}
	return 0
}

func (x *WideState) GetV9() int32 {
	if x != nil {
		return x.V9
	}
	return 0
}

func (x *WideState) GetV10() int32 {
	if x != nil {
		return x.V10
	}
	return 0
}

func (x *WideState) GetV11() int32 {
	if x != nil {
		return x.V11
	}
	return 0
}

func (x *WideState) GetV12() int32 {
	if x != nil {
		return x.V12
	}
	return 0
}

func (x *WideState) GetV13() int32 {
	if x != nil {
		return x.V13
	}
	return 0
}

func (x *WideState) GetV14() int32 {
	if x != nil {
		return x.V14
	}
	return 0
}

func (x *WideState) GetV15() int32 {
	if x != nil {
		return x.V15
	}
	return 0
}

func (x *WideState) GetV16() int32 {
	if x != nil {
		return x.V16
	}
	return 0
}

func (x *WideState) GetV17() int32 {
	if x != nil {
		return x.V17
	}
	return 0
}

func (x *WideState) GetV18() int32 {
	if x != nil {
		return x.V18
	}
	return 0
}

func (x *WideState) GetV19() int32 {
	if x != nil {
		return x.V19
	}
	return 0
}

func (x *WideState) GetV20() int32 {
	if x != nil {
		return x.V20
	}
	return 0
}

func (x *WideState) GetV21() int32 {
	if x != nil {
		return x.V21
	}
	return 0
}

func (x *WideState) GetV22() int32 {
	if x != nil {
		return x.V22
	}
	return 0
}

func (x *WideState) GetV23() int32 {
	if x != nil {
		return x.V23
	}
	return 0
}

func (x *WideState) GetV24() int32 {
	if x != nil {
		return x.V24
	}
	return 0
}

func (x *WideState) GetV25() int32 {
	if x != nil {
		return x.V25
	}
	return 0
}

func (x *WideState) GetV26() int32 {
	if x != nil {
		return x.V26
	}
	return 0
}

func (x *WideState) GetV27() int32 {
	if x != nil {
		return x.V27
	}
	return 0
}

func (x *WideState) GetV28() int32 {
	if x != nil {
		return x.V28
	}
	return 0
}

func (x *WideState) GetV29() int32 {
	if x != nil {
		return x.V29
	}
	return 0
}

func (x *WideState) GetV30() int32 {
	if x != nil {
		return x.V30
	}
	return 0
}

func (x *WideState) GetV31() int32 {
	if x != nil {
		return x.V31
	}
	return 0
}

func (x *WideState) GetV32() int32 {
	if x != nil {
		return x.V32
	}
	return 0
}

func (x *WideState) GetV33() int32 {
	if x != nil {
		return x.V33
	}
	return 0
}

func (x *WideState) GetV34() int32 {
	if x != nil {
		return x.V34
	}
	return 0
}

func (x *WideState) GetV35() int32 {
	if x != nil {
		return x.V35
	}
	return 0
}

func (x *WideState) GetV36() int32 {
	if x != nil {
		return x.V36
	}
	return 0
}

func (x *WideState) GetV37() int32 {
	if x != nil {
		return x.V37
	}
	return 0
}

func (x *WideState) GetV38() int32 {
	if x != nil {
		return x.V38
	}
	return 0
}

func (x *WideState) GetV39() int32 {
	if x != nil {
		return x.V39
	}
	return 0
}

func (x *WideState) GetV40() int32 {
	if x != nil {
		return x.V40
	}
	return 0
}

func (x *WideState) GetV41() int32 {
	if x != nil {
		return x.V41
	}
	return 0
}

func (x *WideState) GetV42() int32 {
	if x != nil {
		return x.V42
	}
	return 0
}

func (x *WideState) GetV43() int32 {
	if x != nil {
		return x.V43
	}
	return 0
}

func (x *WideState) GetV44() int32 {
	if x != nil {
		return x.V44
	}
	return 0
}

func (x *WideState) GetV45() int32 {
	if x != nil {
		return x.V45
	}
	return 0
}

func (x *WideState) GetV46() int32 {
	if x != nil {
		return x.V46
	}
	return 0
}

func (x *WideState) GetV47() int32 {
	if x != nil {
		return x.V47
	}
	return 0
}

func (x *WideState) GetV48() int32 {
	if x != nil {
		return x.V48
	}
	return 0
}

func (x *WideState) GetV49() int32 {
	if x != nil {
		return x.V49
	}
	return 0
}

func (x *WideState) GetV50() int32 {
	if x != nil {
		return x.V50
	}
	return 0
}

func (x *WideState) GetV51() int32 {
	if x != nil {
		return x.V51
	}
	return 0
}

func (x *WideState) GetV52() int32 {
	if x != nil {
		return x.V52
	}
	return 0
}

func (x *WideState) GetV53() int32 {
	if x != nil {
		return x.V53
	}
	return 0
}

func (x *WideState) GetV54() int32 {
	if x != nil {
		return x.V54
	}
	return 0
}

func (x *WideState) GetV55() int32 {
	if x != nil {
		return x.V55
	}
	return 0
}

func (x *WideState) GetV56() int32 {
	if x != nil {
		return x.V56
	}
	return 0
}

func (x *WideState) GetV57() int32 {
	if x != nil {
		return x.V57
	}
	return 0
}

func (x *WideState) GetV58() int32 {
	if x != nil {
		return x.V58
	}
	return 0
}

func (x *WideState) GetV59() int32 {
	if x != nil {
		return x.V59
	}
	return 0
}

func (x *WideState) GetV60() int32 {
	if x != nil {
		return x.V60
	}
	return 0
}

func (x *WideState) GetV61() int32 {
	if x != nil {
		return x.V61
	}
	return 0
}

func (x *WideState) GetV62() int32 {
	if x != nil {
		return x.V62
	}
	return 0
}

func (x *WideState) GetV63() int32 {
	if x != nil {
		return x.V63
	}
	return 0
}

func (x *WideState) GetV64() int32 {
	if x != nil {
		return x.V64
	}
	return 0
}

func (x *WideState) GetV65() int32 {
	if x != nil {
		return x.V65
	}
	return 0
}

func (x *WideState) GetV66() int32 {
	if x != nil {
		return x.V66
	}
	return 0
}

func (x *WideState) GetV67() int32 {
	if x != nil {
		return x.V67
	}
	return 0
}

func (x *WideState) GetV68() int32 {
	if x != nil {
		return x.V68
	}
	return 0
}

func (x *WideState) GetV69() int32 {
	if x != nil {
		return x.V69
	}
	return 0
}

func (x *WideState) GetV70() int32 {
	if x != nil {
		return x.V70
	}
	return 0
}

var File_diff_testdata_complex_proto protoreflect.FileDescriptor

const file_diff_testdata_complex_proto_rawDesc = "" +
	"\n" +
	"\x1bdiff/testdata/complex.proto\x12\x12nova.diff.testdata\"\xc6\a\n" +
	"\bGameData\x12:\n" +
	"\ascalars\x18\x01 \x01(\v2 .nova.diff.testdata.ScalarValuesR\ascalars\x125\n" +
	"\aprofile\x18\x02 \x01(\v2\x1b.nova.diff.testdata.ProfileR\aprofile\x12=\n" +
	"\x05items\x18\x03 \x03(\v2'.nova.diff.testdata.GameData.ItemsEntryR\x05items\x12L\n" +
	"\n" +
	"currencies\x18\x04 \x03(\v2,.nova.diff.testdata.GameData.CurrenciesEntryR\n" +
	"currencies\x12I\n" +
	"\tsnapshots\x18\x05 \x03(\v2+.nova.diff.testdata.GameData.SnapshotsEntryR\tsnapshots\x12S\n" +
	"\rfeature_flags\x18\x06 \x03(\v2..nova.diff.testdata.GameData.FeatureFlagsEntryR\ffeatureFlags\x12 \n" +
	"\vcheckpoints\x18\a \x03(\x03R\vcheckpoints\x12\x16\n" +
	"\x06labels\x18\b \x03(\tR\x06labels\x12\x18\n" +
	"\apackets\x18\t \x03(\fR\apackets\x129\n" +
	"\x06lineup\x18\n" +
	" \x03(\v2!.nova.diff.testdata.InventoryItemR\x06lineup\x12=\n" +
	"\tqualities\x18\v \x03(\x0e2\x1f.nova.diff.testdata.ItemQualityR\tqualities\x121\n" +
	"\x04wide\x18\f \x01(\v2\x1d.nova.diff.testdata.WideStateR\x04wide\x1a[\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.nova.diff.testdata.InventoryItemR\x05value:\x028\x01\x1a=\n" +
	"\x0fCurrenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eSnapshotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x04\n" +
	"\fScalarValues\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\aquality\x18\x02 \x01(\x0e2\x1f.nova.diff.testdata.ItemQualityR\aquality\x12\x1f\n" +
	"\vint32_value\x18\x03 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fsint32_value\x18\x04 \x01(\x11R\vsint32Value\x12%\n" +
	"\x0esfixed32_value\x18\x05 \x01(\x0fR\rsfixed32Value\x12!\n" +
	"\fuint32_value\x18\x06 \x01(\rR\vuint32Value\x12#\n" +
	"\rfixed32_value\x18\a \x01(\aR\ffixed32Value\x12\x1f\n" +
	"\vint64_value\x18\b \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fsint64_value\x18\t \x01(\x12R\vsint64Value\x12%\n" +
	"\x0esfixed64_value\x18\n" +
	" \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fuint64_value\x18\v \x01(\x04R\vuint64Value\x12#\n" +
	"\rfixed64_value\x18\f \x01(\x06R\ffixed64Value\x12\x1f\n" +
	"\vfloat_value\x18\r \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x0e \x01(\x01R\vdoubleValue\x12!\n" +
	"\fstring_value\x18\x0f \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x10 \x01(\fR\n" +
	"bytesValue\"p\n" +
	"\aProfile\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x125\n" +
	"\aaddress\x18\x02 \x01(\v2\x1b.nova.diff.testdata.AddressR\aaddress\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"R\n" +
	"\aAddress\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x19\n" +
	"\bzip_code\x18\x03 \x01(\rR\azipCode\"\xa7\x03\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x129\n" +
	"\aquality\x18\x03 \x01(\x0e2\x1f.nova.diff.testdata.ItemQualityR\aquality\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x120\n" +
	"\x04attr\x18\x06 \x01(\v2\x1c.nova.diff.testdata.ItemAttrR\x04attr\x12H\n" +
	"\aeffects\x18\a \x03(\v2..nova.diff.testdata.InventoryItem.EffectsEntryR\aeffects\x12/\n" +
	"\x04gems\x18\b \x03(\v2\x1b.nova.diff.testdata.ItemGemR\x04gems\x1aZ\n" +
	"\fEffectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.nova.diff.testdata.ItemEffectR\x05value:\x028\x01\"@\n" +
	"\bItemAttr\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"durability\x18\x02 \x01(\x05R\n" +
	"durability\"2\n" +
	"\n" +
	"ItemEffect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05power\x18\x02 \x01(\x05R\x05power\"/\n" +
	"\aItemGem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xe5\t\n" +
	"\tWideState\x12\x0e\n" +
	"\x02v1\x18\x01 \x01(\x05R\x02v1\x12\x0e\n" +
	"\x02v2\x18\x02 \x01(\x05R\x02v2\x12\x0e\n" +
	"\x02v3\x18\x03 \x01(\x05R\x02v3\x12\x0e\n" +
	"\x02v4\x18\x04 \x01(\x05R\x02v4\x12\x0e\n" +
	"\x02v5\x18\x05 \x01(\x05R\x02v5\x12\x0e\n" +
	"\x02v6\x18\x06 \x01(\x05R\x02v6\x12\x0e\n" +
	"\x02v7\x18\a \x01(\x05R\x02v7\x12\x0e\n" +
	"\x02v8\x18\b \x01(\x05R\x02v8\x12\x0e\n" +
	"\x02v9\x18\t \x01(\x05R\x02v9\x12\x10\n" +
	"\x03v10\x18\n" +
	" \x01(\x05R\x03v10\x12\x10\n" +
	"\x03v11\x18\v \x01(\x05R\x03v11\x12\x10\n" +
	"\x03v12\x18\f \x01(\x05R\x03v12\x12\x10\n" +
	"\x03v13\x18\r \x01(\x05R\x03v13\x12\x10\n" +
	"\x03v14\x18\x0e \x01(\x05R\x03v14\x12\x10\n" +
	"\x03v15\x18\x0f \x01(\x05R\x03v15\x12\x10\n" +
	"\x03v16\x18\x10 \x01(\x05R\x03v16\x12\x10\n" +
	"\x03v17\x18\x11 \x01(\x05R\x03v17\x12\x10\n" +
	"\x03v18\x18\x12 \x01(\x05R\x03v18\x12\x10\n" +
	"\x03v19\x18\x13 \x01(\x05R\x03v19\x12\x10\n" +
	"\x03v20\x18\x14 \x01(\x05R\x03v20\x12\x10\n" +
	"\x03v21\x18\x15 \x01(\x05R\x03v21\x12\x10\n" +
	"\x03v22\x18\x16 \x01(\x05R\x03v22\x12\x10\n" +
	"\x03v23\x18\x17 \x01(\x05R\x03v23\x12\x10\n" +
	"\x03v24\x18\x18 \x01(\x05R\x03v24\x12\x10\n" +
	"\x03v25\x18\x19 \x01(\x05R\x03v25\x12\x10\n" +
	"\x03v26\x18\x1a \x01(\x05R\x03v26\x12\x10\n" +
	"\x03v27\x18\x1b \x01(\x05R\x03v27\x12\x10\n" +
	"\x03v28\x18\x1c \x01(\x05R\x03v28\x12\x10\n" +
	"\x03v29\x18\x1d \x01(\x05R\x03v29\x12\x10\n" +
	"\x03v30\x18\x1e \x01(\x05R\x03v30\x12\x10\n" +
	"\x03v31\x18\x1f \x01(\x05R\x03v31\x12\x10\n" +
	"\x03v32\x18  \x01(\x05R\x03v32\x12\x10\n" +
	"\x03v33\x18! \x01(\x05R\x03v33\x12\x10\n" +
	"\x03v34\x18\" \x01(\x05R\x03v34\x12\x10\n" +
	"\x03v35\x18# \x01(\x05R\x03v35\x12\x10\n" +
	"\x03v36\x18$ \x01(\x05R\x03v36\x12\x10\n" +
	"\x03v37\x18% \x01(\x05R\x03v37\x12\x10\n" +
	"\x03v38\x18& \x01(\x05R\x03v38\x12\x10\n" +
	"\x03v39\x18' \x01(\x05R\x03v39\x12\x10\n" +
	"\x03v40\x18( \x01(\x05R\x03v40\x12\x10\n" +
	"\x03v41\x18) \x01(\x05R\x03v41\x12\x10\n" +
	"\x03v42\x18* \x01(\x05R\x03v42\x12\x10\n" +
	"\x03v43\x18+ \x01(\x05R\x03v43\x12\x10\n" +
	"\x03v44\x18, \x01(\x05R\x03v44\x12\x10\n" +
	"\x03v45\x18- \x01(\x05R\x03v45\x12\x10\n" +
	"\x03v46\x18. \x01(\x05R\x03v46\x12\x10\n" +
	"\x03v47\x18/ \x01(\x05R\x03v47\x12\x10\n" +
	"\x03v48\x180 \x01(\x05R\x03v48\x12\x10\n" +
	"\x03v49\x181 \x01(\x05R\x03v49\x12\x10\n" +
	"\x03v50\x182 \x01(\x05R\x03v50\x12\x10\n" +
	"\x03v51\x183 \x01(\x05R\x03v51\x12\x10\n" +
	"\x03v52\x184 \x01(\x05R\x03v52\x12\x10\n" +
	"\x03v53\x185 \x01(\x05R\x03v53\x12\x10\n" +
	"\x03v54\x186 \x01(\x05R\x03v54\x12\x10\n" +
	"\x03v55\x187 \x01(\x05R\x03v55\x12\x10\n" +
	"\x03v56\x188 \x01(\x05R\x03v56\x12\x10\n" +
	"\x03v57\x189 \x01(\x05R\x03v57\x12\x10\n" +
	"\x03v58\x18: \x01(\x05R\x03v58\x12\x10\n" +
	"\x03v59\x18; \x01(\x05R\x03v59\x12\x10\n" +
	"\x03v60\x18< \x01(\x05R\x03v60\x12\x10\n" +
	"\x03v61\x18= \x01(\x05R\x03v61\x12\x10\n" +
	"\x03v62\x18> \x01(\x05R\x03v62\x12\x10\n" +
	"\x03v63\x18? \x01(\x05R\x03v63\x12\x10\n" +
	"\x03v64\x18@ \x01(\x05R\x03v64\x12\x10\n" +
	"\x03v65\x18A \x01(\x05R\x03v65\x12\x10\n" +
	"\x03v66\x18B \x01(\x05R\x03v66\x12\x10\n" +
	"\x03v67\x18C \x01(\x05R\x03v67\x12\x10\n" +
	"\x03v68\x18D \x01(\x05R\x03v68\x12\x10\n" +
	"\x03v69\x18E \x01(\x05R\x03v69\x12\x10\n" +
	"\x03v70\x18F \x01(\x05R\x03v70*n\n" +
	"\vItemQuality\x12\x18\n" +
	"\x14ITEM_QUALITY_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13ITEM_QUALITY_COMMON\x10\x01\x12\x15\n" +
	"\x11ITEM_QUALITY_RARE\x10\x02\x12\x15\n" +
	"\x11ITEM_QUALITY_EPIC\x10\x03B0Z.github.com/2comjie/nova/diff/testdata;testdatab\x06proto3"

var (
	file_diff_testdata_complex_proto_rawDescOnce sync.Once
	file_diff_testdata_complex_proto_rawDescData []byte
)

func file_diff_testdata_complex_proto_rawDescGZIP() []byte {
	file_diff_testdata_complex_proto_rawDescOnce.Do(func() {
		file_diff_testdata_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diff_testdata_complex_proto_rawDesc), len(file_diff_testdata_complex_proto_rawDesc)))
	})
	return file_diff_testdata_complex_proto_rawDescData
}

var file_diff_testdata_complex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_diff_testdata_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_diff_testdata_complex_proto_goTypes = []any{
	(ItemQuality)(0),      // 0: nova.diff.testdata.ItemQuality
	(*GameData)(nil),      // 1: nova.diff.testdata.GameData
	(*ScalarValues)(nil),  // 2: nova.diff.testdata.ScalarValues
	(*Profile)(nil),       // 3: nova.diff.testdata.Profile
	(*Address)(nil),       // 4: nova.diff.testdata.Address
	(*InventoryItem)(nil), // 5: nova.diff.testdata.InventoryItem
	(*ItemAttr)(nil),      // 6: nova.diff.testdata.ItemAttr
	(*ItemEffect)(nil),    // 7: nova.diff.testdata.ItemEffect
	(*ItemGem)(nil),       // 8: nova.diff.testdata.ItemGem
	(*WideState)(nil),     // 9: nova.diff.testdata.WideState
	nil,                   // 10: nova.diff.testdata.GameData.ItemsEntry
	nil,                   // 11: nova.diff.testdata.GameData.CurrenciesEntry
	nil,                   // 12: nova.diff.testdata.GameData.SnapshotsEntry
	nil,                   // 13: nova.diff.testdata.GameData.FeatureFlagsEntry
	nil,                   // 14: nova.diff.testdata.InventoryItem.EffectsEntry
}
var file_diff_testdata_complex_proto_depIdxs = []int32{
	2,  // 0: nova.diff.testdata.GameData.scalars:type_name -> nova.diff.testdata.ScalarValues
	3,  // 1: nova.diff.testdata.GameData.profile:type_name -> nova.diff.testdata.Profile
	10, // 2: nova.diff.testdata.GameData.items:type_name -> nova.diff.testdata.GameData.ItemsEntry
	11, // 3: nova.diff.testdata.GameData.currencies:type_name -> nova.diff.testdata.GameData.CurrenciesEntry
	12, // 4: nova.diff.testdata.GameData.snapshots:type_name -> nova.diff.testdata.GameData.SnapshotsEntry
	13, // 5: nova.diff.testdata.GameData.feature_flags:type_name -> nova.diff.testdata.GameData.FeatureFlagsEntry
	5,  // 6: nova.diff.testdata.GameData.lineup:type_name -> nova.diff.testdata.InventoryItem
	0,  // 7: nova.diff.testdata.GameData.qualities:type_name -> nova.diff.testdata.ItemQuality
	9,  // 8: nova.diff.testdata.GameData.wide:type_name -> nova.diff.testdata.WideState
	0,  // 9: nova.diff.testdata.ScalarValues.quality:type_name -> nova.diff.testdata.ItemQuality
	4,  // 10: nova.diff.testdata.Profile.address:type_name -> nova.diff.testdata.Address
	0,  // 11: nova.diff.testdata.InventoryItem.quality:type_name -> nova.diff.testdata.ItemQuality
	6,  // 12: nova.diff.testdata.InventoryItem.attr:type_name -> nova.diff.testdata.ItemAttr
	14, // 13: nova.diff.testdata.InventoryItem.effects:type_name -> nova.diff.testdata.InventoryItem.EffectsEntry
	8,  // 14: nova.diff.testdata.InventoryItem.gems:type_name -> nova.diff.testdata.ItemGem
	5,  // 15: nova.diff.testdata.GameData.ItemsEntry.value:type_name -> nova.diff.testdata.InventoryItem
	7,  // 16: nova.diff.testdata.InventoryItem.EffectsEntry.value:type_name -> nova.diff.testdata.ItemEffect
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_diff_testdata_complex_proto_init() }
func file_diff_testdata_complex_proto_init() {
	if File_diff_testdata_complex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_testdata_complex_proto_rawDesc), len(file_diff_testdata_complex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_testdata_complex_proto_goTypes,
		DependencyIndexes: file_diff_testdata_complex_proto_depIdxs,
		EnumInfos:         file_diff_testdata_complex_proto_enumTypes,
		MessageInfos:      file_diff_testdata_complex_proto_msgTypes,
	}.Build()
	File_diff_testdata_complex_proto = out.File
	file_diff_testdata_complex_proto_goTypes = nil
	file_diff_testdata_complex_proto_depIdxs = nil
}
