//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package profile

import (
	bson "go.mongodb.org/mongo-driver/v2/bson"

	diff "github.com/2comjie/nova/diff"

	json "encoding/json"

	pbData "github.com/2comjie/nova/examples/pb/profile"

	time "time"
)

type State int32

type StateAlias = State

type PlayerId = uint64

const (
	Offline State = 0
	Online  State = 1
)

type Profile struct {
	diff.Object

	id diff.Primitive[PlayerId] `diff:"1" json:"id" bson:"_id"`

	state diff.Primitive[StateAlias] `diff:"2" json:"state" bson:"state"`

	loginAt diff.Primitive[time.Time] `diff:"3" json:"login_at" bson:"login_at"`

	cooldown diff.Primitive[time.Duration] `diff:"4" json:"cooldown" bson:"cooldown"`

	history diff.PrimitiveSlice[State] `diff:"5" json:"history" bson:"history"`

	rewardsAt diff.PrimitiveMap[string, time.Time] `diff:"6" json:"rewards_at" bson:"rewards_at"`
}

func (value *Profile) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}

	value.Object.Init(writer)

	value.id.Init(&value.Object, 1)

	value.state.Init(&value.Object, 2)

	value.loginAt.Init(&value.Object, 3)

	value.cooldown.Init(&value.Object, 4)

	value.history.Init(&value.Object, 5)

	value.rewardsAt.Init(&value.Object, 6)

}

func (value *Profile) GetId() PlayerId {
	return value.id.GetValue()
}

func (value *Profile) SetId(fieldValue PlayerId) bool {
	value.InitLink(nil)
	return value.id.SetValue(fieldValue)
}

func (value *Profile) GetState() StateAlias {
	return value.state.GetValue()
}

func (value *Profile) SetState(fieldValue StateAlias) bool {
	value.InitLink(nil)
	return value.state.SetValue(fieldValue)
}

func (value *Profile) GetLoginAt() time.Time {
	return value.loginAt.GetValue()
}

func (value *Profile) SetLoginAt(fieldValue time.Time) bool {
	value.InitLink(nil)
	return value.loginAt.SetValue(fieldValue)
}

func (value *Profile) GetCooldown() time.Duration {
	return value.cooldown.GetValue()
}

func (value *Profile) SetCooldown(fieldValue time.Duration) bool {
	value.InitLink(nil)
	return value.cooldown.SetValue(fieldValue)
}

func (value *Profile) History() *diff.PrimitiveSlice[State] {
	value.InitLink(nil)
	return &value.history
}

func (value *Profile) RewardsAt() *diff.PrimitiveMap[string, time.Time] {
	value.InitLink(nil)
	return &value.rewardsAt
}

// Snapshot 导出独立的全量 Proto，不修改对象和变更记录。
func (value *Profile) Snapshot() *pbData.Profile {
	snapshot := &pbData.Profile{

		Id: uint64(value.id.GetValue()),

		State: int32(value.state.GetValue()),

		LoginAt: value.loginAt.GetValue().UnixMilli(),

		Cooldown: int64(value.cooldown.GetValue()),
	}

	if value.history.Len() != 0 {
		snapshot.History = make([]int32, value.history.Len())
		for index := range snapshot.History {
			fieldValue := value.history.GetValue(index)
			snapshot.History[index] = int32(fieldValue)
		}
	}

	if value.rewardsAt.Len() != 0 {
		snapshot.RewardsAt = make(map[string]int64, value.rewardsAt.Len())
		value.rewardsAt.Range(func(key string, fieldValue time.Time) bool {
			snapshot.RewardsAt[key] = fieldValue.UnixMilli()
			return true
		})
	}

	return snapshot
}

// LoadSnapshot 加载全量基线并恢复父子链接，不记录增量。
// snapshot 必须非空；已有待提交变化由调用方在重置基线前处理。
func (value *Profile) LoadSnapshot(snapshot *pbData.Profile) {
	value.InitLink(nil)

	value.id.LoadSnapshot(PlayerId(snapshot.Id))

	value.state.LoadSnapshot(StateAlias(snapshot.State))

	value.loginAt.LoadSnapshot(time.UnixMilli(snapshot.LoginAt).UTC())

	value.cooldown.LoadSnapshot(time.Duration(snapshot.Cooldown))

	{
		var values []State
		if len(snapshot.History) != 0 {
			values = make([]State, len(snapshot.History))
			for index, fieldValue := range snapshot.History {
				values[index] = State(fieldValue)
			}
		}
		value.history.LoadSnapshot(values)
	}

	{
		var values map[string]time.Time
		if len(snapshot.RewardsAt) != 0 {
			values = make(map[string]time.Time, len(snapshot.RewardsAt))
			for key, fieldValue := range snapshot.RewardsAt {
				values[key] = time.UnixMilli(fieldValue).UTC()
			}
		}
		value.rewardsAt.LoadSnapshot(values)
	}

}

// Commit 导出本轮增量并清空 Writer；返回值独立于运行时对象。
func (value *Profile) Commit() *pbData.Profile {
	return value.Object.Commit(new(pbData.Profile), value.WriteUpdate)
}

// WriteUpdate 将 Writer 的内部变更转换为有类型的 Proto 字段。
func (value *Profile) WriteUpdate(update *pbData.Profile, path diff.Path, operation diff.Operation, data any) {
	node := path[0]
	switch node.FieldIndex {

	case 1:
		fieldValue := uint64(data.(PlayerId))
		update.IdUpdate = &fieldValue

	case 2:
		fieldValue := int32(data.(StateAlias))
		update.StateUpdate = &fieldValue

	case 3:
		fieldValue := data.(time.Time).UnixMilli()
		update.LoginAtUpdate = &fieldValue

	case 4:
		fieldValue := int64(data.(time.Duration))
		update.CooldownUpdate = &fieldValue

	case 5:
		update.HistoryUpdated = true
		values := data.([]State)
		update.HistoryUpdate = make([]int32, len(values))
		for index, fieldValue := range values {
			update.HistoryUpdate[index] = int32(fieldValue)
		}

	case 6:
		if node.KeyType == diff.PathField {
			update.RewardsAtClear = true
			return
		}
		key := node.MapKey.(string)
		if operation == diff.MapSet {
			diff.SetMap(&update.RewardsAtSet, key, data.(time.Time).UnixMilli())
		} else {
			update.RewardsAtDelete = append(update.RewardsAtDelete, key)
		}

	}
}

// Merge 按序应用增量。对象必须已加载对应基线；绑定 Writer 时会记录本地变化。
func (value *Profile) Merge(update *pbData.Profile) {
	value.InitLink(nil)

	if update.IdUpdate != nil {
		value.id.SetValue(PlayerId(*update.IdUpdate))
	}

	if update.StateUpdate != nil {
		value.state.SetValue(StateAlias(*update.StateUpdate))
	}

	if update.LoginAtUpdate != nil {
		value.loginAt.SetValue(time.UnixMilli(*update.LoginAtUpdate).UTC())
	}

	if update.CooldownUpdate != nil {
		value.cooldown.SetValue(time.Duration(*update.CooldownUpdate))
	}

	if update.HistoryUpdated {
		value.history.Clear()
		for _, fieldValue := range update.HistoryUpdate {
			value.history.Append(State(fieldValue))
		}
	}

	if update.RewardsAtClear {
		value.rewardsAt.Clear()
	}
	for key, fieldValue := range update.RewardsAtSet {
		value.rewardsAt.Store(key, time.UnixMilli(fieldValue).UTC())
	}
	for _, key := range update.RewardsAtDelete {
		value.rewardsAt.Delete(key)
	}

}

// _diffProfileData 仅包含业务数据；子对象使用自己的编解码方法。
type _diffProfileData struct {
	Id PlayerId `diff:"1" json:"id" bson:"_id"`

	State StateAlias `diff:"2" json:"state" bson:"state"`

	LoginAt int64 `diff:"3" json:"login_at" bson:"login_at"`

	Cooldown time.Duration `diff:"4" json:"cooldown" bson:"cooldown"`

	History []State `diff:"5" json:"history" bson:"history"`

	RewardsAt map[string]int64 `diff:"6" json:"rewards_at" bson:"rewards_at"`
}

func (value *Profile) exportData() _diffProfileData {
	data := _diffProfileData{

		Id: value.id.GetValue(),

		State: value.state.GetValue(),

		LoginAt: value.loginAt.GetValue().UnixMilli(),

		Cooldown: value.cooldown.GetValue(),
	}

	if value.history.Len() != 0 {
		data.History = make([]State, value.history.Len())
		for index := range data.History {
			data.History[index] = value.history.GetValue(index)
		}
	}

	if value.rewardsAt.Len() != 0 {
		data.RewardsAt = make(map[string]int64, value.rewardsAt.Len())
		value.rewardsAt.Range(func(key string, fieldValue time.Time) bool {
			data.RewardsAt[key] = fieldValue.UnixMilli()
			return true
		})
	}

	return data
}

// loadData 接管完整解码成功的数据，不记录增量。
func (value *Profile) loadData(data _diffProfileData) {
	value.InitLink(nil)

	value.id.LoadSnapshot(data.Id)

	value.state.LoadSnapshot(data.State)

	value.loginAt.LoadSnapshot(time.UnixMilli(data.LoginAt).UTC())

	value.cooldown.LoadSnapshot(data.Cooldown)

	value.history.LoadSnapshot(data.History)

	{
		var values map[string]time.Time
		if len(data.RewardsAt) != 0 {
			values = make(map[string]time.Time, len(data.RewardsAt))
			for key, fieldValue := range data.RewardsAt {
				values[string(key)] = time.UnixMilli(fieldValue).UTC()
			}
		}
		value.rewardsAt.LoadSnapshot(values)
	}

}

func (value *Profile) MarshalJSON() ([]byte, error) {
	return json.Marshal(value.exportData())
}

func (value *Profile) UnmarshalJSON(data []byte) error {
	var decoded _diffProfileData
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	value.loadData(decoded)
	return nil
}

func (value *Profile) MarshalBSON() ([]byte, error) {
	return bson.Marshal(value.exportData())
}

// MarshalBSONValue 保留嵌套对象和对象 Slice 中的 null。
func (value *Profile) MarshalBSONValue() (byte, []byte, error) {
	if value == nil {
		return byte(bson.TypeNull), nil, nil
	}
	data, err := value.MarshalBSON()
	return byte(bson.TypeEmbeddedDocument), data, err
}

func (value *Profile) UnmarshalBSON(data []byte) error {
	var decoded _diffProfileData
	if err := bson.Unmarshal(data, &decoded); err != nil {
		return err
	}
	value.loadData(decoded)
	return nil
}
