syntax = "proto3";

package transport.node;

option go_package = "github.com/2comjie/wali/pb/transport/node;pbNode";

import "transport/request/request.proto";


message HandleClientMessageRequest {
  request.Request request = 1;
}

message HandleClientMessageResponse {
  request.Response response = 1;
}

message HandleRpcRequest {
  string method = 1;
  string nonce = 2;
  map<string, bytes> meta = 3;
  bytes data = 4;
}
message HandleRpcResponse {
  bytes data = 1;
}

service Node {
  rpc HandleClientMessage(HandleClientMessageRequest) returns (HandleClientMessageResponse);
  rpc HandleRpc(HandleRpcRequest) returns (HandleRpcResponse);
}

