//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package item

import (
	"github.com/2comjie/nova/diff"
	_pbData "github.com/2comjie/nova/examples/diff_app/item/pb"
)

type Item struct {
	diff.Object
	itemId diff.Primitive[uint64]
	count  diff.Primitive[int32]
}

func (value *Item) GetItemId() uint64 {
	return value.itemId.GetValue()
}

func (value *Item) SetItemId(fieldValue uint64) bool {
	value.InitLink(nil)
	return value.itemId.SetValue(fieldValue)
}

func (value *Item) GetCount() int32 {
	return value.count.GetValue()
}

func (value *Item) SetCount(fieldValue int32) bool {
	value.InitLink(nil)
	return value.count.SetValue(fieldValue)
}

func (value *Item) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}
	value.Object.Init(writer)
	value.itemId.Init(&value.Object, 1)
	value.count.Init(&value.Object, 2)
}

func (value *Item) Snapshot() *_pbData.Item {
	snapshot := new(_pbData.Item)
	snapshot.ItemId = value.itemId.GetValue()
	snapshot.Count = value.count.GetValue()
	return snapshot
}

func (value *Item) LoadSnapshot(snapshot *_pbData.Item) {
	value.InitLink(nil)
	value.itemId.SetValue(snapshot.GetItemId())
	value.count.SetValue(snapshot.GetCount())
}

func (value *Item) NewUpdate() *_pbData.Item {
	return new(_pbData.Item)
}

func (value *Item) Commit() *_pbData.Item {
	return value.Object.Commit(value.NewUpdate(), value.WriteUpdate)
}

func (value *Item) WriteUpdate(update *_pbData.Item, path diff.Path, operation diff.Operation, data any) {
	node := path[0]
	switch node.FieldIndex {
	case 1:
		fieldValue := data.(uint64)
		update.ItemIdUpdate = &fieldValue
		return

	case 2:
		fieldValue := data.(int32)
		update.CountUpdate = &fieldValue
		return

	}
}

func (value *Item) Merge(update *_pbData.Item) {
	value.InitLink(nil)
	if update.ItemIdUpdate != nil {
		value.itemId.SetValue(update.GetItemIdUpdate())
	}
	if update.CountUpdate != nil {
		value.count.SetValue(update.GetCountUpdate())
	}
}
