//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package item

import (
	diff "github.com/2comjie/nova/diff"
)

type Item[Count ~int32 | ~int64] struct {
	diff.Object
	itemId diff.Primitive[uint64]
	count  diff.Primitive[Count]
}

func (value *Item[Count]) GetItemId() uint64 {
	return value.itemId.GetValue()
}

func (value *Item[Count]) SetItemId(fieldValue uint64) bool {
	value.EnsureDiffLink()
	return value.itemId.SetValue(fieldValue)
}

func (value *Item[Count]) GetCount() Count {
	return value.count.GetValue()
}

func (value *Item[Count]) SetCount(fieldValue Count) bool {
	value.EnsureDiffLink()
	return value.count.SetValue(fieldValue)
}

type ItemDiffPath[DiffRoot any, Count ~int32 | ~int64] struct {
	path diff.PathBuilder[DiffRoot]
}

func NewItemDiffPath[DiffRoot any, Count ~int32 | ~int64](path diff.PathBuilder[DiffRoot]) ItemDiffPath[DiffRoot, Count] {
	return ItemDiffPath[DiffRoot, Count]{path: path}
}

func ItemDiff[Count ~int32 | ~int64]() ItemDiffPath[*Item[Count], Count] {
	return NewItemDiffPath[*Item[Count], Count](diff.NewPathBuilder[*Item[Count]]())
}

func (path ItemDiffPath[DiffRoot, Count]) ItemId() diff.ValuePath[DiffRoot, uint64] {
	return diff.NewValuePath[DiffRoot, uint64](path.path.Field(1))
}

func (path ItemDiffPath[DiffRoot, Count]) Count() diff.ValuePath[DiffRoot, Count] {
	return diff.NewValuePath[DiffRoot, Count](path.path.Field(2))
}

func (value *Item[Count]) InitLink(writer *diff.Writer) {
	if writer != nil {
		diff.BindWriter[*Item[Count]](writer)
	}
	value.InitDiffLink(writer, make(map[*diff.Object]struct{}))
}

func (value *Item[Count]) EnsureDiffLink() {
	if value == nil {
		return
	}
	if value.itemId.Initialized() {
		return
	}
	value.InitDiffLink(nil, make(map[*diff.Object]struct{}))
}

func (value *Item[Count]) InitDiffLink(writer *diff.Writer, visited map[*diff.Object]struct{}) {
	if value == nil {
		return
	}
	if visited == nil {
		visited = make(map[*diff.Object]struct{})
	}
	if _, exists := visited[&value.Object]; exists {
		return
	}
	visited[&value.Object] = struct{}{}
	value.Object.Init(writer)
	value.itemId.Init(&value.Object, 1)
	value.count.Init(&value.Object, 2)
}

func (value *Item[Count]) AppendDiffValue(data []byte) []byte {
	data = value.itemId.AppendValue(data, 1)
	data = value.count.AppendValue(data, 2)
	return data
}

func (value *Item[Count]) Commit() []byte {
	return value.Object.Commit()
}

func (value *Item[Count]) Snapshot() []byte {
	return value.AppendDiffValue(nil)
}

func (value *Item[Count]) LoadSnapshot(data []byte) error {
	value.InitLink(nil)
	var zeroItemId uint64
	value.itemId.SetValue(zeroItemId)
	var zeroCount Count
	value.count.SetValue(zeroCount)
	fields, err := diff.DecodeFields(data)
	if err != nil {
		return err
	}
	for _, field := range fields {
		if err := value.loadDiffField(field); err != nil {
			return err
		}
	}
	return nil
}

func (value *Item[Count]) Merge(data []byte) error {
	value.InitLink(nil)
	patches, err := diff.DecodePatches(data)
	if err != nil {
		return err
	}
	for _, patch := range patches {
		if err := value.MergeDiffPatch(patch.Path, patch.Operation, patch.Value); err != nil {
			return err
		}
	}
	return nil
}

func (value *Item[Count]) loadDiffField(field diff.EncodedField) error {
	switch field.FieldIndex {
	case 1:
		{
			fieldValue, err := diff.DecodePrimitive[uint64](field.Value)
			if err != nil {
				return err
			}
			value.itemId.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			fieldValue, err := diff.DecodePrimitive[Count](field.Value)
			if err != nil {
				return err
			}
			value.count.SetValue(fieldValue)
			return nil
		}
	}
	return nil
}

func (value *Item[Count]) MergeDiffPatch(path []diff.EncodedPathNode, operation diff.Operation, data []byte) error {
	if len(path) == 0 {
		return diff.ErrInvalidData
	}
	node := path[0]
	switch node.FieldIndex {
	case 1:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[uint64](data)
			if err != nil {
				return err
			}
			value.itemId.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[Count](data)
			if err != nil {
				return err
			}
			value.count.SetValue(fieldValue)
			return nil
		}
	}
	return nil
}
