//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package item

import (
	diff "github.com/2comjie/nova/diff"

	pbData "github.com/2comjie/nova/examples/pb/item"
)

type Item struct {
	diff.Object

	itemId diff.Primitive[uint64] `diff:"1"`

	count diff.Primitive[int32] `diff:"2"`
}

func (value *Item) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}

	value.Object.Init(writer)

	value.itemId.Init(&value.Object, 1)

	value.count.Init(&value.Object, 2)

}

func (value *Item) GetItemId() uint64 {
	return value.itemId.GetValue()
}

func (value *Item) SetItemId(fieldValue uint64) bool {
	value.InitLink(nil)
	return value.itemId.SetValue(fieldValue)
}

func (value *Item) GetCount() int32 {
	return value.count.GetValue()
}

func (value *Item) SetCount(fieldValue int32) bool {
	value.InitLink(nil)
	return value.count.SetValue(fieldValue)
}

// Snapshot 导出独立的全量 Proto，不修改对象和变更记录。
func (value *Item) Snapshot() *pbData.Item {
	snapshot := &pbData.Item{

		ItemId: value.itemId.GetValue(),

		Count: value.count.GetValue(),
	}

	return snapshot
}

// LoadSnapshot 加载全量基线并恢复父子链接，不记录增量。
// snapshot 必须非空；已有待提交变化由调用方在重置基线前处理。
func (value *Item) LoadSnapshot(snapshot *pbData.Item) {
	value.InitLink(nil)

	value.itemId.LoadSnapshot(snapshot.ItemId)

	value.count.LoadSnapshot(snapshot.Count)

}

// Commit 导出本轮增量并清空 Writer；返回值独立于运行时对象。
func (value *Item) Commit() *pbData.Item {
	return value.Object.Commit(new(pbData.Item), value.WriteUpdate)
}

// WriteUpdate 将 Writer 的内部变更转换为有类型的 Proto 字段。
func (value *Item) WriteUpdate(update *pbData.Item, path diff.Path, operation diff.Operation, data any) {
	node := path[0]
	switch node.FieldIndex {

	case 1:
		fieldValue := data.(uint64)
		update.ItemIdUpdate = &fieldValue

	case 2:
		fieldValue := data.(int32)
		update.CountUpdate = &fieldValue

	}
}

// Merge 按序应用增量。对象必须已加载对应基线；绑定 Writer 时会记录本地变化。
func (value *Item) Merge(update *pbData.Item) {
	value.InitLink(nil)

	if update.ItemIdUpdate != nil {
		value.itemId.SetValue(*update.ItemIdUpdate)
	}

	if update.CountUpdate != nil {
		value.count.SetValue(*update.CountUpdate)
	}

}
