// Code generated by diff-gen. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: diff_app/bag/a_data_bag.proto

package pbBag

import (
	pb "github.com/2comjie/nova/examples/diff_app/item/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[uint64]*pb.Item    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Order         []*pb.Item             `protobuf:"bytes,2,rep,name=order,proto3" json:"order,omitempty"`
	ItemsClear    bool                   `protobuf:"varint,1001,opt,name=items_clear,json=itemsClear,proto3" json:"items_clear,omitempty"`
	ItemsSet      map[uint64]*pb.Item    `protobuf:"bytes,2001,rep,name=items_set,json=itemsSet,proto3" json:"items_set,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ItemsDelete   []uint64               `protobuf:"varint,3001,rep,packed,name=items_delete,json=itemsDelete,proto3" json:"items_delete,omitempty"`
	ItemsUpdate   map[uint64]*pb.Item    `protobuf:"bytes,4001,rep,name=items_update,json=itemsUpdate,proto3" json:"items_update,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrderUpdated  bool                   `protobuf:"varint,1002,opt,name=order_updated,json=orderUpdated,proto3" json:"order_updated,omitempty"`
	OrderUpdate   []*pb.Item             `protobuf:"bytes,2002,rep,name=order_update,json=orderUpdate,proto3" json:"order_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bag) Reset() {
	*x = Bag{}
	mi := &file_diff_app_bag_a_data_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bag) ProtoMessage() {}

func (x *Bag) ProtoReflect() protoreflect.Message {
	mi := &file_diff_app_bag_a_data_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bag.ProtoReflect.Descriptor instead.
func (*Bag) Descriptor() ([]byte, []int) {
	return file_diff_app_bag_a_data_bag_proto_rawDescGZIP(), []int{0}
}

func (x *Bag) GetItems() map[uint64]*pb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Bag) GetOrder() []*pb.Item {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *Bag) GetItemsClear() bool {
	if x != nil {
		return x.ItemsClear
	}
	return false
}

func (x *Bag) GetItemsSet() map[uint64]*pb.Item {
	if x != nil {
		return x.ItemsSet
	}
	return nil
}

func (x *Bag) GetItemsDelete() []uint64 {
	if x != nil {
		return x.ItemsDelete
	}
	return nil
}

func (x *Bag) GetItemsUpdate() map[uint64]*pb.Item {
	if x != nil {
		return x.ItemsUpdate
	}
	return nil
}

func (x *Bag) GetOrderUpdated() bool {
	if x != nil {
		return x.OrderUpdated
	}
	return false
}

func (x *Bag) GetOrderUpdate() []*pb.Item {
	if x != nil {
		return x.OrderUpdate
	}
	return nil
}

type BagSyncPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	BaseVersion   uint64                 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BagSyncPush_Full
	//	*BagSyncPush_Update
	Payload       isBagSyncPush_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagSyncPush) Reset() {
	*x = BagSyncPush{}
	mi := &file_diff_app_bag_a_data_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagSyncPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagSyncPush) ProtoMessage() {}

func (x *BagSyncPush) ProtoReflect() protoreflect.Message {
	mi := &file_diff_app_bag_a_data_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagSyncPush.ProtoReflect.Descriptor instead.
func (*BagSyncPush) Descriptor() ([]byte, []int) {
	return file_diff_app_bag_a_data_bag_proto_rawDescGZIP(), []int{1}
}

func (x *BagSyncPush) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *BagSyncPush) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *BagSyncPush) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BagSyncPush) GetPayload() isBagSyncPush_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BagSyncPush) GetFull() *Bag {
	if x != nil {
		if x, ok := x.Payload.(*BagSyncPush_Full); ok {
			return x.Full
		}
	}
	return nil
}

func (x *BagSyncPush) GetUpdate() *Bag {
	if x != nil {
		if x, ok := x.Payload.(*BagSyncPush_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isBagSyncPush_Payload interface {
	isBagSyncPush_Payload()
}

type BagSyncPush_Full struct {
	Full *Bag `protobuf:"bytes,10,opt,name=full,proto3,oneof"`
}

type BagSyncPush_Update struct {
	Update *Bag `protobuf:"bytes,11,opt,name=update,proto3,oneof"`
}

func (*BagSyncPush_Full) isBagSyncPush_Payload() {}

func (*BagSyncPush_Update) isBagSyncPush_Payload() {}

var File_diff_app_bag_a_data_bag_proto protoreflect.FileDescriptor

const file_diff_app_bag_a_data_bag_proto_rawDesc = "" +
	"\n" +
	"\x1ddiff_app/bag/a_data_bag.proto\x12\x03bag\x1a\x1fdiff_app/item/a_data_item.proto\"\xbe\x04\n" +
	"\x03Bag\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.bag.Bag.ItemsEntryR\x05items\x12 \n" +
	"\x05order\x18\x02 \x03(\v2\n" +
	".item.ItemR\x05order\x12 \n" +
	"\vitems_clear\x18\xe9\a \x01(\bR\n" +
	"itemsClear\x124\n" +
	"\titems_set\x18\xd1\x0f \x03(\v2\x16.bag.Bag.ItemsSetEntryR\bitemsSet\x12\"\n" +
	"\fitems_delete\x18\xb9\x17 \x03(\x04R\vitemsDelete\x12=\n" +
	"\fitems_update\x18\xa1\x1f \x03(\v2\x19.bag.Bag.ItemsUpdateEntryR\vitemsUpdate\x12$\n" +
	"\rorder_updated\x18\xea\a \x01(\bR\forderUpdated\x12.\n" +
	"\forder_update\x18\xd2\x0f \x03(\v2\n" +
	".item.ItemR\vorderUpdate\x1aD\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".item.ItemR\x05value:\x028\x01\x1aG\n" +
	"\rItemsSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".item.ItemR\x05value:\x028\x01\x1aJ\n" +
	"\x10ItemsUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".item.ItemR\x05value:\x028\x01\"\xc0\x01\n" +
	"\vBagSyncPush\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12!\n" +
	"\fbase_version\x18\x02 \x01(\x04R\vbaseVersion\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1e\n" +
	"\x04full\x18\n" +
	" \x01(\v2\b.bag.BagH\x00R\x04full\x12\"\n" +
	"\x06update\x18\v \x01(\v2\b.bag.BagH\x00R\x06updateB\t\n" +
	"\apayloadBMZ6github.com/2comjie/nova/examples/diff_app/bag/pb;pbBag\xaa\x02\x12Nova.Generated.Bagb\x06proto3"

var (
	file_diff_app_bag_a_data_bag_proto_rawDescOnce sync.Once
	file_diff_app_bag_a_data_bag_proto_rawDescData []byte
)

func file_diff_app_bag_a_data_bag_proto_rawDescGZIP() []byte {
	file_diff_app_bag_a_data_bag_proto_rawDescOnce.Do(func() {
		file_diff_app_bag_a_data_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diff_app_bag_a_data_bag_proto_rawDesc), len(file_diff_app_bag_a_data_bag_proto_rawDesc)))
	})
	return file_diff_app_bag_a_data_bag_proto_rawDescData
}

var file_diff_app_bag_a_data_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_diff_app_bag_a_data_bag_proto_goTypes = []any{
	(*Bag)(nil),         // 0: bag.Bag
	(*BagSyncPush)(nil), // 1: bag.BagSyncPush
	nil,                 // 2: bag.Bag.ItemsEntry
	nil,                 // 3: bag.Bag.ItemsSetEntry
	nil,                 // 4: bag.Bag.ItemsUpdateEntry
	(*pb.Item)(nil),     // 5: item.Item
}
var file_diff_app_bag_a_data_bag_proto_depIdxs = []int32{
	2,  // 0: bag.Bag.items:type_name -> bag.Bag.ItemsEntry
	5,  // 1: bag.Bag.order:type_name -> item.Item
	3,  // 2: bag.Bag.items_set:type_name -> bag.Bag.ItemsSetEntry
	4,  // 3: bag.Bag.items_update:type_name -> bag.Bag.ItemsUpdateEntry
	5,  // 4: bag.Bag.order_update:type_name -> item.Item
	0,  // 5: bag.BagSyncPush.full:type_name -> bag.Bag
	0,  // 6: bag.BagSyncPush.update:type_name -> bag.Bag
	5,  // 7: bag.Bag.ItemsEntry.value:type_name -> item.Item
	5,  // 8: bag.Bag.ItemsSetEntry.value:type_name -> item.Item
	5,  // 9: bag.Bag.ItemsUpdateEntry.value:type_name -> item.Item
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_diff_app_bag_a_data_bag_proto_init() }
func file_diff_app_bag_a_data_bag_proto_init() {
	if File_diff_app_bag_a_data_bag_proto != nil {
		return
	}
	file_diff_app_bag_a_data_bag_proto_msgTypes[1].OneofWrappers = []any{
		(*BagSyncPush_Full)(nil),
		(*BagSyncPush_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_app_bag_a_data_bag_proto_rawDesc), len(file_diff_app_bag_a_data_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_app_bag_a_data_bag_proto_goTypes,
		DependencyIndexes: file_diff_app_bag_a_data_bag_proto_depIdxs,
		MessageInfos:      file_diff_app_bag_a_data_bag_proto_msgTypes,
	}.Build()
	File_diff_app_bag_a_data_bag_proto = out.File
	file_diff_app_bag_a_data_bag_proto_goTypes = nil
	file_diff_app_bag_a_data_bag_proto_depIdxs = nil
}
