//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package player

import (
	bag "github.com/2comjie/nova/examples/diff_app/bag"

	diff "github.com/2comjie/nova/diff"

	logdef "github.com/2comjie/nova/logx/logdef"

	pbData "github.com/2comjie/nova/examples/pb/player"

	pbbag "github.com/2comjie/nova/examples/pb/bag"
)

type Player struct {
	logdef.ILogger `diff:"-"`

	diff.Object

	uid diff.Primitive[uint64] `diff:"1"`

	level diff.Primitive[int32] `diff:"2"`

	name diff.Primitive[string] `diff:"3"`

	bag diff.Pointer[*bag.Bag] `diff:"4"`

	scores diff.PrimitiveMap[uint64, int32] `diff:"5"`

	recentLevels diff.PrimitiveSlice[int32] `diff:"6"`
}

func (value *Player) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}

	value.Object.Init(writer)

	value.uid.Init(&value.Object, 1)

	value.level.Init(&value.Object, 2)

	value.name.Init(&value.Object, 3)

	value.bag.Init(&value.Object, 4)

	value.scores.Init(&value.Object, 5)

	value.recentLevels.Init(&value.Object, 6)

}

func (value *Player) GetUid() uint64 {
	return value.uid.GetValue()
}

func (value *Player) SetUid(fieldValue uint64) bool {
	value.InitLink(nil)
	return value.uid.SetValue(fieldValue)
}

func (value *Player) GetLevel() int32 {
	return value.level.GetValue()
}

func (value *Player) SetLevel(fieldValue int32) bool {
	value.InitLink(nil)
	return value.level.SetValue(fieldValue)
}

func (value *Player) GetName() string {
	return value.name.GetValue()
}

func (value *Player) SetName(fieldValue string) bool {
	value.InitLink(nil)
	return value.name.SetValue(fieldValue)
}

func (value *Player) GetBag() *bag.Bag {
	return value.bag.GetValue()
}

func (value *Player) SetBag(fieldValue *bag.Bag) bool {
	value.InitLink(nil)
	return value.bag.SetValue(fieldValue)
}

func (value *Player) Scores() *diff.PrimitiveMap[uint64, int32] {
	value.InitLink(nil)
	return &value.scores
}

func (value *Player) RecentLevels() *diff.PrimitiveSlice[int32] {
	value.InitLink(nil)
	return &value.recentLevels
}

// Snapshot 导出独立的全量 Proto，不修改对象和变更记录。
func (value *Player) Snapshot() *pbData.Player {
	snapshot := &pbData.Player{

		Uid: value.uid.GetValue(),

		Level: value.level.GetValue(),

		Name: value.name.GetValue(),
	}

	if child := value.bag.GetValue(); child != nil {
		snapshot.Bag = child.Snapshot()
	}

	if value.scores.Len() != 0 {
		snapshot.Scores = make(map[uint64]int32, value.scores.Len())
		value.scores.Range(func(key uint64, fieldValue int32) bool {
			snapshot.Scores[key] = fieldValue
			return true
		})
	}

	if value.recentLevels.Len() != 0 {
		snapshot.RecentLevels = make([]int32, value.recentLevels.Len())
		for index := range snapshot.RecentLevels {
			fieldValue := value.recentLevels.GetValue(index)
			snapshot.RecentLevels[index] = fieldValue
		}
	}

	return snapshot
}

// LoadSnapshot 加载全量基线并恢复父子链接，不记录增量。
// snapshot 必须非空；已有待提交变化由调用方在重置基线前处理。
func (value *Player) LoadSnapshot(snapshot *pbData.Player) {
	value.InitLink(nil)

	value.uid.LoadSnapshot(snapshot.Uid)

	value.level.LoadSnapshot(snapshot.Level)

	value.name.LoadSnapshot(snapshot.Name)

	{
		var child *bag.Bag
		if snapshot.Bag != nil {
			child = new(bag.Bag)
			child.LoadSnapshot(snapshot.Bag)
		}
		value.bag.LoadSnapshot(child)
	}

	{
		var values map[uint64]int32
		if len(snapshot.Scores) != 0 {
			values = make(map[uint64]int32, len(snapshot.Scores))
			for key, fieldValue := range snapshot.Scores {
				values[key] = fieldValue
			}
		}
		value.scores.LoadSnapshot(values)
	}

	{
		var values []int32
		if len(snapshot.RecentLevels) != 0 {
			values = make([]int32, len(snapshot.RecentLevels))
			for index, fieldValue := range snapshot.RecentLevels {
				values[index] = fieldValue
			}
		}
		value.recentLevels.LoadSnapshot(values)
	}

}

// Commit 导出本轮增量并清空 Writer；返回值独立于运行时对象。
func (value *Player) Commit() *pbData.Player {
	return value.Object.Commit(new(pbData.Player), value.WriteUpdate)
}

// WriteUpdate 将 Writer 的内部变更转换为有类型的 Proto 字段。
func (value *Player) WriteUpdate(update *pbData.Player, path diff.Path, operation diff.Operation, data any) {
	node := path[0]
	switch node.FieldIndex {

	case 1:
		fieldValue := data.(uint64)
		update.UidUpdate = &fieldValue

	case 2:
		fieldValue := data.(int32)
		update.LevelUpdate = &fieldValue

	case 3:
		fieldValue := data.(string)
		update.NameUpdate = &fieldValue

	case 4:
		if len(path) == 1 {
			if operation == diff.PointerSet {
				update.BagDiff = &pbData.Player_BagSet{BagSet: data.(*bag.Bag).Snapshot()}
			} else {
				update.BagDiff = &pbData.Player_BagClear{BagClear: true}
			}
			return
		}
		childUpdate := update.GetBagUpdate()
		if childUpdate == nil {
			childUpdate = new(pbbag.Bag)
			update.BagDiff = &pbData.Player_BagUpdate{BagUpdate: childUpdate}
		}
		value.bag.GetValue().WriteUpdate(childUpdate, path[1:], operation, data)

	case 5:
		if node.KeyType == diff.PathField {
			update.ScoresClear = true
			return
		}
		key := node.MapKey.(uint64)
		if operation == diff.MapSet {
			diff.SetMap(&update.ScoresSet, key, data.(int32))
		} else {
			update.ScoresDelete = append(update.ScoresDelete, key)
		}

	case 6:
		update.RecentLevelsUpdated = true
		values := data.([]int32)
		update.RecentLevelsUpdate = make([]int32, len(values))
		for index, fieldValue := range values {
			update.RecentLevelsUpdate[index] = fieldValue
		}

	}
}

// Merge 按序应用增量。对象必须已加载对应基线；绑定 Writer 时会记录本地变化。
func (value *Player) Merge(update *pbData.Player) {
	value.InitLink(nil)

	if update.UidUpdate != nil {
		value.uid.SetValue(*update.UidUpdate)
	}

	if update.LevelUpdate != nil {
		value.level.SetValue(*update.LevelUpdate)
	}

	if update.NameUpdate != nil {
		value.name.SetValue(*update.NameUpdate)
	}

	switch fieldValue := update.BagDiff.(type) {
	case *pbData.Player_BagSet:
		child := new(bag.Bag)
		child.LoadSnapshot(fieldValue.BagSet)
		value.bag.SetValue(child)
	case *pbData.Player_BagClear:
		value.bag.SetValue(nil)
	case *pbData.Player_BagUpdate:
		value.bag.GetValue().Merge(fieldValue.BagUpdate)
	}

	if update.ScoresClear {
		value.scores.Clear()
	}
	for key, fieldValue := range update.ScoresSet {
		value.scores.Store(key, fieldValue)
	}
	for _, key := range update.ScoresDelete {
		value.scores.Delete(key)
	}

	if update.RecentLevelsUpdated {
		value.recentLevels.Clear()
		for _, fieldValue := range update.RecentLevelsUpdate {
			value.recentLevels.Append(fieldValue)
		}
	}

}
