//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package player

import (
	"github.com/2comjie/nova/diff"
	bag "github.com/2comjie/nova/examples/diff_app/bag"
	_pbData "github.com/2comjie/nova/examples/diff_app/player/pb"
	logdef "github.com/2comjie/nova/logx/logdef"
)

type Player struct {
	logdef.ILogger `diff:"-"`
	diff.Object
	uid          diff.Primitive[uint64]
	level        diff.Primitive[int32]
	name         diff.Primitive[string]
	bag          diff.Pointer[*bag.Bag]
	scores       diff.PrimitiveMap[uint64, int32]
	recentLevels diff.PrimitiveSlice[int32]
}

func (value *Player) GetUid() uint64 {
	return value.uid.GetValue()
}

func (value *Player) SetUid(fieldValue uint64) bool {
	value.InitLink(nil)
	return value.uid.SetValue(fieldValue)
}

func (value *Player) GetLevel() int32 {
	return value.level.GetValue()
}

func (value *Player) SetLevel(fieldValue int32) bool {
	value.InitLink(nil)
	return value.level.SetValue(fieldValue)
}

func (value *Player) GetName() string {
	return value.name.GetValue()
}

func (value *Player) SetName(fieldValue string) bool {
	value.InitLink(nil)
	return value.name.SetValue(fieldValue)
}

func (value *Player) GetBag() *bag.Bag {
	return value.bag.GetValue()
}

func (value *Player) SetBag(fieldValue *bag.Bag) bool {
	value.InitLink(nil)
	return value.bag.SetValue(fieldValue)
}

func (value *Player) ClearBag() bool {
	value.InitLink(nil)
	return value.bag.SetValue(nil)
}

func (value *Player) Scores() *diff.PrimitiveMap[uint64, int32] {
	value.InitLink(nil)
	return &value.scores
}

func (value *Player) RecentLevels() *diff.PrimitiveSlice[int32] {
	value.InitLink(nil)
	return &value.recentLevels
}

func (value *Player) InitLink(writer *diff.Writer) {
	if value.Object.Initialized() {
		if writer != nil {
			value.Object.Init(writer)
		}
		return
	}
	value.Object.Init(writer)
	value.uid.Init(&value.Object, 1)
	value.level.Init(&value.Object, 2)
	value.name.Init(&value.Object, 3)
	value.bag.Init(&value.Object, 4)
	value.scores.Init(&value.Object, 5)
	value.recentLevels.Init(&value.Object, 6)
}

func (value *Player) Snapshot() *_pbData.Player {
	snapshot := new(_pbData.Player)
	snapshot.Uid = value.uid.GetValue()
	snapshot.Level = value.level.GetValue()
	snapshot.Name = value.name.GetValue()
	if child := value.bag.GetValue(); child != nil {
		snapshot.Bag = child.Snapshot()
	}
	value.scores.Range(func(key uint64, fieldValue int32) bool {
		diff.SetMap(&snapshot.Scores, key, fieldValue)
		return true
	})
	value.recentLevels.Range(func(_ int, fieldValue int32) bool {
		snapshot.RecentLevels = append(snapshot.RecentLevels, fieldValue)
		return true
	})
	return snapshot
}

func (value *Player) LoadSnapshot(snapshot *_pbData.Player) {
	value.InitLink(nil)
	value.uid.SetValue(snapshot.GetUid())
	value.level.SetValue(snapshot.GetLevel())
	value.name.SetValue(snapshot.GetName())
	if fieldValue := snapshot.GetBag(); fieldValue == nil {
		value.bag.SetValue(nil)
	} else {
		child := new(bag.Bag)
		child.LoadSnapshot(fieldValue)
		value.bag.SetValue(child)
	}
	value.scores.Clear()
	for key, fieldValue := range snapshot.GetScores() {
		value.scores.Store(key, fieldValue)
	}
	value.recentLevels.Clear()
	for _, fieldValue := range snapshot.GetRecentLevels() {
		value.recentLevels.Append(fieldValue)
	}
}

func (value *Player) NewUpdate() *_pbData.Player {
	return new(_pbData.Player)
}

func (value *Player) Commit() *_pbData.Player {
	return value.Object.Commit(value.NewUpdate(), value.WriteUpdate)
}

func (value *Player) WriteUpdate(update *_pbData.Player, path diff.Path, operation diff.Operation, data any) {
	node := path[0]
	switch node.FieldIndex {
	case 1:
		fieldValue := data.(uint64)
		update.UidUpdate = &fieldValue
		return

	case 2:
		fieldValue := data.(int32)
		update.LevelUpdate = &fieldValue
		return

	case 3:
		fieldValue := data.(string)
		update.NameUpdate = &fieldValue
		return

	case 4:
		if len(path) == 1 {
			if operation == diff.PointerSet {
				update.BagDiff = &_pbData.Player_BagSet{BagSet: data.(*bag.Bag).Snapshot()}
			} else {
				update.BagDiff = &_pbData.Player_BagClear{BagClear: true}
			}
			return
		}
		child := value.bag.GetValue()
		childUpdate := update.GetBagUpdate()
		if childUpdate == nil {
			childUpdate = child.NewUpdate()
			update.BagDiff = &_pbData.Player_BagUpdate{BagUpdate: childUpdate}
		}
		child.WriteUpdate(childUpdate, path[1:], operation, data)
		return

	case 5:
		if node.KeyType == diff.PathField {
			update.ScoresClear = true
			return
		}
		key := node.MapKey.(uint64)
		if operation == diff.MapSet {
			diff.SetMap(&update.ScoresSet, key, data.(int32))
		} else {
			update.ScoresDelete = append(update.ScoresDelete, key)
		}
		return

	case 6:
		update.RecentLevelsUpdated = true
		update.RecentLevelsUpdate = append(update.RecentLevelsUpdate[:0], data.([]int32)...)
		return

	}
}

func (value *Player) Merge(update *_pbData.Player) {
	value.InitLink(nil)
	if update.UidUpdate != nil {
		value.uid.SetValue(update.GetUidUpdate())
	}
	if update.LevelUpdate != nil {
		value.level.SetValue(update.GetLevelUpdate())
	}
	if update.NameUpdate != nil {
		value.name.SetValue(update.GetNameUpdate())
	}
	switch fieldValue := update.BagDiff.(type) {
	case *_pbData.Player_BagSet:
		child := new(bag.Bag)
		child.LoadSnapshot(fieldValue.BagSet)
		value.bag.SetValue(child)
	case *_pbData.Player_BagClear:
		value.bag.SetValue(nil)
	case *_pbData.Player_BagUpdate:
		value.bag.GetValue().Merge(fieldValue.BagUpdate)
	}
	if update.ScoresClear {
		value.scores.Clear()
	}
	for key, fieldValue := range update.ScoresSet {
		value.scores.Store(key, fieldValue)
	}
	for _, key := range update.ScoresDelete {
		value.scores.Delete(key)
	}
	if update.RecentLevelsUpdated {
		value.recentLevels.Clear()
		for _, fieldValue := range update.RecentLevelsUpdate {
			value.recentLevels.Append(fieldValue)
		}
	}
}
