//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package player

import (
	diff "github.com/2comjie/nova/diff"
	bag "github.com/2comjie/nova/examples/diff_app/bag"
	logdef "github.com/2comjie/nova/logx/logdef"
)

type Player struct {
	logdef.ILogger `diff:"-"`
	diff.Object
	uid          diff.Primitive[uint64]
	level        diff.Primitive[int32]
	name         diff.Primitive[string]
	bag          diff.Pointer[*bag.Bag]
	scores       diff.PrimitiveMap[uint64, int32]
	recentLevels diff.PrimitiveSlice[int32]
}

func (value *Player) GetUid() uint64 {
	return value.uid.GetValue()
}

func (value *Player) SetUid(fieldValue uint64) bool {
	value.EnsureDiffLink()
	return value.uid.SetValue(fieldValue)
}

func (value *Player) GetLevel() int32 {
	return value.level.GetValue()
}

func (value *Player) SetLevel(fieldValue int32) bool {
	value.EnsureDiffLink()
	return value.level.SetValue(fieldValue)
}

func (value *Player) GetName() string {
	return value.name.GetValue()
}

func (value *Player) SetName(fieldValue string) bool {
	value.EnsureDiffLink()
	return value.name.SetValue(fieldValue)
}

func (value *Player) GetBag() *bag.Bag {
	return value.bag.GetValue()
}

func (value *Player) SetBag(fieldValue *bag.Bag) bool {
	value.EnsureDiffLink()
	return value.bag.SetValue(fieldValue)
}

func (value *Player) ClearBag() bool {
	value.EnsureDiffLink()
	return value.bag.SetValue(nil)
}

func (value *Player) Scores() *diff.PrimitiveMap[uint64, int32] {
	value.EnsureDiffLink()
	return &value.scores
}

func (value *Player) RecentLevels() *diff.PrimitiveSlice[int32] {
	value.EnsureDiffLink()
	return &value.recentLevels
}

type PlayerDiffPath[DiffRoot any] struct {
	path diff.PathBuilder[DiffRoot]
}

func NewPlayerDiffPath[DiffRoot any](path diff.PathBuilder[DiffRoot]) PlayerDiffPath[DiffRoot] {
	return PlayerDiffPath[DiffRoot]{path: path}
}

var PlayerDiff = NewPlayerDiffPath[*Player](diff.NewPathBuilder[*Player]())

func (path PlayerDiffPath[DiffRoot]) Uid() diff.ValuePath[DiffRoot, uint64] {
	return diff.NewValuePath[DiffRoot, uint64](path.path.Field(1))
}

func (path PlayerDiffPath[DiffRoot]) Level() diff.ValuePath[DiffRoot, int32] {
	return diff.NewValuePath[DiffRoot, int32](path.path.Field(2))
}

func (path PlayerDiffPath[DiffRoot]) Name() diff.ValuePath[DiffRoot, string] {
	return diff.NewValuePath[DiffRoot, string](path.path.Field(3))
}

func (path PlayerDiffPath[DiffRoot]) Bag() PlayerBagDiffPath[DiffRoot] {
	fieldPath := path.path.Field(4)
	return PlayerBagDiffPath[DiffRoot]{
		bag.NewBagDiffPath[DiffRoot](fieldPath),
		diff.NewValuePath[DiffRoot, *bag.Bag](fieldPath),
	}
}

type PlayerBagDiffPath[DiffRoot any] struct {
	bag.BagDiffPath[DiffRoot]
	value diff.ValuePath[DiffRoot, *bag.Bag]
}

func (path PlayerBagDiffPath[DiffRoot]) Changes() diff.ValuePath[DiffRoot, *bag.Bag] {
	return path.value
}

func (path PlayerDiffPath[DiffRoot]) Scores() diff.MapPath[DiffRoot, uint64, int32] {
	return diff.NewMapPath[DiffRoot, uint64, int32](path.path, 5)
}

func (path PlayerDiffPath[DiffRoot]) RecentLevels() diff.SlicePath[DiffRoot, int32] {
	return diff.NewSlicePath[DiffRoot, int32](path.path, 6)
}

func (value *Player) InitLink(writer *diff.Writer) {
	if writer != nil {
		diff.BindWriter[*Player](writer)
	}
	value.InitDiffLink(writer, make(map[*diff.Object]struct{}))
}

func (value *Player) EnsureDiffLink() {
	if value == nil {
		return
	}
	if value.uid.Initialized() {
		return
	}
	value.InitDiffLink(nil, make(map[*diff.Object]struct{}))
}

func (value *Player) InitDiffLink(writer *diff.Writer, visited map[*diff.Object]struct{}) {
	if value == nil {
		return
	}
	if visited == nil {
		visited = make(map[*diff.Object]struct{})
	}
	if _, exists := visited[&value.Object]; exists {
		return
	}
	visited[&value.Object] = struct{}{}
	value.Object.Init(writer)
	value.uid.Init(&value.Object, 1)
	value.level.Init(&value.Object, 2)
	value.name.Init(&value.Object, 3)
	if child := value.bag.GetValue(); child != nil {
		child.InitDiffLink(nil, visited)
	}
	value.bag.Init(&value.Object, 4)
	value.scores.Init(&value.Object, 5)
	value.recentLevels.Init(&value.Object, 6)
}

func (value *Player) AppendDiffValue(data []byte) []byte {
	data = value.uid.AppendValue(data, 1)
	data = value.level.AppendValue(data, 2)
	data = value.name.AppendValue(data, 3)
	data = value.bag.AppendValue(data, 4)
	data = value.scores.AppendValue(data, 5)
	data = value.recentLevels.AppendValue(data, 6)
	return data
}

func (value *Player) Commit() []byte {
	return value.Object.Commit()
}

func (value *Player) Snapshot() []byte {
	return value.AppendDiffValue(nil)
}

func (value *Player) LoadSnapshot(data []byte) error {
	value.InitLink(nil)
	var zeroUid uint64
	value.uid.SetValue(zeroUid)
	var zeroLevel int32
	value.level.SetValue(zeroLevel)
	var zeroName string
	value.name.SetValue(zeroName)
	value.bag.SetValue(nil)
	value.scores.Clear()
	value.recentLevels.Clear()
	fields, err := diff.DecodeFields(data)
	if err != nil {
		return err
	}
	for _, field := range fields {
		if err := value.loadDiffField(field); err != nil {
			return err
		}
	}
	return nil
}

func (value *Player) Merge(data []byte) error {
	value.InitLink(nil)
	patches, err := diff.DecodePatches(data)
	if err != nil {
		return err
	}
	for _, patch := range patches {
		if err := value.MergeDiffPatch(patch.Path, patch.Operation, patch.Value); err != nil {
			return err
		}
	}
	return nil
}

func (value *Player) loadDiffField(field diff.EncodedField) error {
	switch field.FieldIndex {
	case 1:
		{
			fieldValue, err := diff.DecodePrimitive[uint64](field.Value)
			if err != nil {
				return err
			}
			value.uid.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			fieldValue, err := diff.DecodePrimitive[int32](field.Value)
			if err != nil {
				return err
			}
			value.level.SetValue(fieldValue)
			return nil
		}
	case 3:
		{
			fieldValue, err := diff.DecodePrimitive[string](field.Value)
			if err != nil {
				return err
			}
			value.name.SetValue(fieldValue)
			return nil
		}
	case 4:
		{
			fieldValue := new(bag.Bag)
			if err := fieldValue.LoadSnapshot(field.Value); err != nil {
				return err
			}
			value.bag.SetValue(fieldValue)
			return nil
		}
	case 5:
		{
			entries, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			if len(entries)%2 != 0 {
				return diff.ErrInvalidData
			}
			for index := 0; index < len(entries); index += 2 {
				mapKey, err := diff.DecodePrimitive[uint64](entries[index])
				if err != nil {
					return err
				}
				mapValue, err := diff.DecodePrimitive[int32](entries[index+1])
				if err != nil {
					return err
				}
				value.scores.Store(mapKey, mapValue)
			}
			return nil
		}
	case 6:
		{
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				sliceValue, err := diff.DecodePrimitive[int32](element)
				if err != nil {
					return err
				}
				value.recentLevels.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}

func (value *Player) MergeDiffPatch(path []diff.EncodedPathNode, operation diff.Operation, data []byte) error {
	if len(path) == 0 {
		return diff.ErrInvalidData
	}
	node := path[0]
	switch node.FieldIndex {
	case 1:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[uint64](data)
			if err != nil {
				return err
			}
			value.uid.SetValue(fieldValue)
			return nil
		}
	case 2:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[int32](data)
			if err != nil {
				return err
			}
			value.level.SetValue(fieldValue)
			return nil
		}
	case 3:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.PrimitiveSet {
				return diff.ErrInvalidData
			}
			fieldValue, err := diff.DecodePrimitive[string](data)
			if err != nil {
				return err
			}
			value.name.SetValue(fieldValue)
			return nil
		}
	case 4:
		{
			if node.KeyType != diff.PathField {
				return diff.ErrInvalidData
			}
			if len(path) == 1 {
				switch operation {
				case diff.PointerSet:
					fieldValue := new(bag.Bag)
					if err := fieldValue.LoadSnapshot(data); err != nil {
						return err
					}
					value.bag.SetValue(fieldValue)
				case diff.PointerClear:
					value.bag.SetValue(nil)
				default:
					return diff.ErrInvalidData
				}
				return nil
			}
			fieldValue := value.bag.GetValue()
			if fieldValue == nil {
				return diff.ErrInvalidData
			}
			return fieldValue.MergeDiffPatch(path[1:], operation, data)
		}
	case 5:
		{
			if node.KeyType == diff.PathField {
				if len(path) != 1 || operation != diff.MapClear {
					return diff.ErrInvalidData
				}
				value.scores.Clear()
				return nil
			}
			if node.KeyType != diff.PathMap {
				return diff.ErrInvalidData
			}
			mapKey, err := diff.DecodePrimitive[uint64](node.MapKey)
			if err != nil {
				return err
			}
			if len(path) != 1 {
				return diff.ErrInvalidData
			}
			switch operation {
			case diff.MapSet:
				mapValue, err := diff.DecodePrimitive[int32](data)
				if err != nil {
					return err
				}
				value.scores.Store(mapKey, mapValue)
			case diff.MapDelete:
				value.scores.Delete(mapKey)
			default:
				return diff.ErrInvalidData
			}
			return nil
		}
	case 6:
		{
			if node.KeyType != diff.PathField || len(path) != 1 || operation != diff.SliceReplace {
				return diff.ErrInvalidData
			}
			value.recentLevels.Clear()
			field := diff.EncodedField{FieldIndex: 6, Value: data}
			elements, err := diff.DecodeValues(field.Value)
			if err != nil {
				return err
			}
			for _, element := range elements {
				sliceValue, err := diff.DecodePrimitive[int32](element)
				if err != nil {
					return err
				}
				value.recentLevels.Append(sliceValue)
			}
			return nil
		}
	}
	return nil
}
