// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: proto/chat/chat.proto

package chatpb

import (
	context "context"
	app "github.com/2comjie/wali/app"
	endpoint "github.com/2comjie/wali/core/endpoint"
	client "github.com/2comjie/wali/rpc/client"
	lx "github.com/2comjie/wali/rpc/lx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_ServiceName        = "examples.rpc.chat.ChatService"
	ChatService_Say_FullMethodName = "/examples.rpc.chat.ChatService/Say"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error)
}

type chatServiceClient struct {
	cc *client.Client
}

func NewChatServiceClient(cc *client.Client) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) conn(ctx context.Context) (*grpc.ClientConn, error) {
	if cfg := lx.FromContext(ctx); cfg != nil {
		switch cfg.Mode {
		case lx.ModeDirect:
			return c.cc.Direct(ctx, cfg.Target)
		case lx.ModeNode:
			return c.cc.Node(ctx, ChatService_ServiceName, cfg.Target)
		case lx.ModeKey:
			return c.cc.Route(ctx, cfg.Name, cfg.Key, ChatService_ServiceName)
		}
	}
	return c.cc.Service(ctx, ChatService_ServiceName)
}

func (c *chatServiceClient) Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, ChatService_Say_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	Say(context.Context, *SayRequest) (*SayResponse, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) Say(context.Context, *SayRequest) (*SayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Say not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func NewChatServiceRpcService(desc string) endpoint.RpcService {
	return endpoint.RpcService{
		Name: ChatService_ServiceName,
		Desc: desc,
	}
}

func RegisterChatServiceRpcService(app app.App, srv ChatServiceServer, host string, port int, desc string) {
	app.RegisterRpcService(host, port, NewChatServiceRpcService(desc), func(registrar grpc.ServiceRegistrar) {
		RegisterChatServiceServer(registrar, srv)
	})
}

func _ChatService_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_Say_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Say(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "examples.rpc.chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _ChatService_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chat/chat.proto",
}
