// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: transport/gate/gate.proto

package pbGate

import (
	context "context"
	app "github.com/2comjie/wali/app"
	endpoint "github.com/2comjie/wali/core/endpoint"
	client "github.com/2comjie/wali/rpc/client"
	lx "github.com/2comjie/wali/rpc/lx"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GateService_ServiceName              = "transport.gate.GateService"
	GateService_BindUid_FullMethodName   = "/transport.gate.GateService/BindUid"
	GateService_UnbindUid_FullMethodName = "/transport.gate.GateService/UnbindUid"
	GateService_Push_FullMethodName      = "/transport.gate.GateService/Push"
	GateService_BroadCast_FullMethodName = "/transport.gate.GateService/BroadCast"
	GateService_MultiCast_FullMethodName = "/transport.gate.GateService/MultiCast"
	GateService_Kick_FullMethodName      = "/transport.gate.GateService/Kick"
	GateService_Stat_FullMethodName      = "/transport.gate.GateService/Stat"
	GateService_GetIP_FullMethodName     = "/transport.gate.GateService/GetIP"
	GateService_IsOnline_FullMethodName  = "/transport.gate.GateService/IsOnline"
)

// GateServiceClient is the client API for GateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateServiceClient interface {
	BindUid(ctx context.Context, in *BindUidRequest, opts ...grpc.CallOption) (*BindUidResponse, error)
	UnbindUid(ctx context.Context, in *UnbindUidRequest, opts ...grpc.CallOption) (*UnbindUidResponse, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushMessageResponse, error)
	BroadCast(ctx context.Context, in *BroadCastRequest, opts ...grpc.CallOption) (*BroadCastResponse, error)
	MultiCast(ctx context.Context, in *MultiCastRequest, opts ...grpc.CallOption) (*MultiCastResponse, error)
	Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	GetIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error)
	IsOnline(ctx context.Context, in *IsOnlineRequest, opts ...grpc.CallOption) (*IsOnlineResponse, error)
}

type gateServiceClient struct {
	cc *client.Client
}

func NewGateServiceClient(cc *client.Client) GateServiceClient {
	return &gateServiceClient{cc}
}

func (c *gateServiceClient) conn(ctx context.Context) (*grpc.ClientConn, error) {
	if cfg := lx.FromContext(ctx); cfg != nil {
		switch cfg.Mode {
		case lx.ModeDirect:
			return c.cc.Direct(ctx, cfg.Target)
		case lx.ModeNode:
			return c.cc.Node(ctx, GateService_ServiceName, cfg.Target)
		case lx.ModeKey:
			return c.cc.Route(ctx, cfg.Name, cfg.Key, GateService_ServiceName)
		}
	}
	return c.cc.Service(ctx, GateService_ServiceName)
}

func (c *gateServiceClient) BindUid(ctx context.Context, in *BindUidRequest, opts ...grpc.CallOption) (*BindUidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindUidResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_BindUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) UnbindUid(ctx context.Context, in *UnbindUidRequest, opts ...grpc.CallOption) (*UnbindUidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindUidResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_UnbindUid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMessageResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) BroadCast(ctx context.Context, in *BroadCastRequest, opts ...grpc.CallOption) (*BroadCastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadCastResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_BroadCast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) MultiCast(ctx context.Context, in *MultiCastRequest, opts ...grpc.CallOption) (*MultiCastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiCastResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_MultiCast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) GetIP(ctx context.Context, in *GetIPRequest, opts ...grpc.CallOption) (*GetIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_GetIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateServiceClient) IsOnline(ctx context.Context, in *IsOnlineRequest, opts ...grpc.CallOption) (*IsOnlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsOnlineResponse)
	conn, err := c.conn(ctx)
	if err != nil {
		return nil, err
	}
	err = conn.Invoke(ctx, GateService_IsOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateServiceServer is the server API for GateService service.
// All implementations must embed UnimplementedGateServiceServer
// for forward compatibility.
type GateServiceServer interface {
	BindUid(context.Context, *BindUidRequest) (*BindUidResponse, error)
	UnbindUid(context.Context, *UnbindUidRequest) (*UnbindUidResponse, error)
	Push(context.Context, *PushRequest) (*PushMessageResponse, error)
	BroadCast(context.Context, *BroadCastRequest) (*BroadCastResponse, error)
	MultiCast(context.Context, *MultiCastRequest) (*MultiCastResponse, error)
	Kick(context.Context, *KickRequest) (*KickResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	GetIP(context.Context, *GetIPRequest) (*GetIPResponse, error)
	IsOnline(context.Context, *IsOnlineRequest) (*IsOnlineResponse, error)
	mustEmbedUnimplementedGateServiceServer()
}

// UnimplementedGateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateServiceServer struct{}

func (UnimplementedGateServiceServer) BindUid(context.Context, *BindUidRequest) (*BindUidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindUid not implemented")
}
func (UnimplementedGateServiceServer) UnbindUid(context.Context, *UnbindUidRequest) (*UnbindUidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindUid not implemented")
}
func (UnimplementedGateServiceServer) Push(context.Context, *PushRequest) (*PushMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGateServiceServer) BroadCast(context.Context, *BroadCastRequest) (*BroadCastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadCast not implemented")
}
func (UnimplementedGateServiceServer) MultiCast(context.Context, *MultiCastRequest) (*MultiCastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MultiCast not implemented")
}
func (UnimplementedGateServiceServer) Kick(context.Context, *KickRequest) (*KickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedGateServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedGateServiceServer) GetIP(context.Context, *GetIPRequest) (*GetIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIP not implemented")
}
func (UnimplementedGateServiceServer) IsOnline(context.Context, *IsOnlineRequest) (*IsOnlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsOnline not implemented")
}
func (UnimplementedGateServiceServer) mustEmbedUnimplementedGateServiceServer() {}
func (UnimplementedGateServiceServer) testEmbeddedByValue()                     {}

// UnsafeGateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateServiceServer will
// result in compilation errors.
type UnsafeGateServiceServer interface {
	mustEmbedUnimplementedGateServiceServer()
}

func RegisterGateServiceServer(s grpc.ServiceRegistrar, srv GateServiceServer) {
	// If the following call panics, it indicates UnimplementedGateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GateService_ServiceDesc, srv)
}

func NewGateServiceRpcService(desc string) endpoint.RpcService {
	return endpoint.RpcService{
		Name: GateService_ServiceName,
		Desc: desc,
	}
}

func RegisterGateServiceRpcService(app app.App, srv GateServiceServer, host string, port int, desc string) {
	app.RegisterRpcService(host, port, NewGateServiceRpcService(desc), func(registrar grpc.ServiceRegistrar) {
		RegisterGateServiceServer(registrar, srv)
	})
}

func _GateService_BindUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).BindUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_BindUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).BindUid(ctx, req.(*BindUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_UnbindUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindUidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).UnbindUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_UnbindUid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).UnbindUid(ctx, req.(*UnbindUidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_BroadCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadCastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).BroadCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_BroadCast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).BroadCast(ctx, req.(*BroadCastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_MultiCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiCastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).MultiCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_MultiCast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).MultiCast(ctx, req.(*MultiCastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).Kick(ctx, req.(*KickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_GetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).GetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_GetIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).GetIP(ctx, req.(*GetIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateService_IsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServiceServer).IsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateService_IsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServiceServer).IsOnline(ctx, req.(*IsOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GateService_ServiceDesc is the grpc.ServiceDesc for GateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transport.gate.GateService",
	HandlerType: (*GateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindUid",
			Handler:    _GateService_BindUid_Handler,
		},
		{
			MethodName: "UnbindUid",
			Handler:    _GateService_UnbindUid_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _GateService_Push_Handler,
		},
		{
			MethodName: "BroadCast",
			Handler:    _GateService_BroadCast_Handler,
		},
		{
			MethodName: "MultiCast",
			Handler:    _GateService_MultiCast_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _GateService_Kick_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _GateService_Stat_Handler,
		},
		{
			MethodName: "GetIP",
			Handler:    _GateService_GetIP_Handler,
		},
		{
			MethodName: "IsOnline",
			Handler:    _GateService_IsOnline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/gate/gate.proto",
}
