// Code generated by protoc-gen-go-diff. DO NOT EDIT.
// protoc-gen-go-diff v0.1.0
// source: diff/testdata/bagpkg/bag.proto

package bagpkg

import (
	diff "github.com/2comjie/nova/diff"
	proto "google.golang.org/protobuf/proto"
)

type BagItems struct {
	state *BagState
}

type bagItemsChange struct {
	key       uint64
	operation diff.Operation
	state     *ItemState
}

type bagItemsTracker struct {
	indexes map[uint64]int
	changes []bagItemsChange
	states  map[uint64]*ItemState
}

func (t *bagItemsTracker) Patch(key uint64, state *ItemState) bool {
	if index := t.indexes[key]; index != 0 {
		change := &t.changes[index-1]
		if change.operation != diff.OperationMapPatch {
			return false
		}
		change.state = state
		return false
	}
	if t.indexes == nil {
		t.indexes = make(map[uint64]int)
	}
	first := len(t.changes) == 0
	t.changes = append(t.changes, bagItemsChange{key: key, operation: diff.OperationMapPatch, state: state})
	t.indexes[key] = len(t.changes)
	return first
}

func (t *bagItemsTracker) Put(key uint64) bool {
	if index := t.indexes[key]; index != 0 {
		change := &t.changes[index-1]
		change.operation = diff.OperationMapPut
		change.state = nil
		return false
	}
	if t.indexes == nil {
		t.indexes = make(map[uint64]int)
	}
	first := len(t.changes) == 0
	t.changes = append(t.changes, bagItemsChange{key: key, operation: diff.OperationMapPut})
	t.indexes[key] = len(t.changes)
	return first
}

func (t *bagItemsTracker) Delete(key uint64) bool {
	if index := t.indexes[key]; index != 0 {
		change := &t.changes[index-1]
		change.operation = diff.OperationMapDelete
		change.state = nil
		return false
	}
	if t.indexes == nil {
		t.indexes = make(map[uint64]int)
	}
	first := len(t.changes) == 0
	t.changes = append(t.changes, bagItemsChange{key: key, operation: diff.OperationMapDelete})
	t.indexes[key] = len(t.changes)
	return first
}

func (t *bagItemsTracker) Clear() bool {
	clear(t.indexes)
	clear(t.changes)
	t.changes = append(t.changes[:0], bagItemsChange{operation: diff.OperationClear})
	return true
}

func (t *bagItemsTracker) ClearDirty() {
	clear(t.indexes)
	clear(t.changes)
	t.changes = t.changes[:0]
	for _, state := range t.states {
		state.ClearDirty()
	}
}

type BagApplyHooks struct {
	OnItemsPut          func(key uint64, oldValue, newValue *Item, replaced bool)
	OnItemsDelete       func(key uint64, oldValue *Item)
	OnItemsClear        func()
	Items               func(key uint64) *ItemApplyHooks
	OnItemsPatch        func(key uint64, oldValue, newValue *Item)
	OnItemsIdChanged    func(key uint64, oldValue, newValue uint64)
	OnItemsCountChanged func(key uint64, oldValue, newValue int32)
}

const bagStateDirtyItemsWord uint32 = 0
const bagStateDirtyItemsMask uint64 = 1

type BagState struct {
	value        *Bag
	dirty        [1]uint64
	markParent   func()
	itemsChanges bagItemsTracker
}

func NewBagState(value *Bag) *BagState {
	return newBagState(value, nil)
}

func NewBagStateWithParent(value *Bag, markParent func()) *BagState {
	return newBagState(value, markParent)
}

func newBagState(value *Bag, markParent func()) *BagState {
	state := &BagState{value: value, markParent: markParent}
	return state
}

func (s *BagState) GetRawValue() *Bag {
	return s.value
}

func (s *BagState) IsDirty() bool {
	return diff.AnyDirty(s.dirty[:])
}

func (s *BagState) markItemsDirty() {
	if diff.MarkDirty(&s.dirty[bagStateDirtyItemsWord], bagStateDirtyItemsMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *BagState) Items() BagItems {
	return BagItems{state: s}
}

func (m BagItems) GetValue(key uint64) (*ItemState, bool) {
	value, ok := m.state.value.Items[key]
	if !ok {
		return nil, false
	}
	if state := m.state.itemsChanges.states[key]; state != nil {
		return state, true
	}
	var state *ItemState
	state = newItemState(value, func() {
		if m.state.itemsChanges.states[key] != state {
			return
		}
		if m.state.itemsChanges.Patch(key, state) {
			m.state.markItemsDirty()
		}
	})
	if m.state.itemsChanges.states == nil {
		m.state.itemsChanges.states = make(map[uint64]*ItemState)
	}
	m.state.itemsChanges.states[key] = state
	return state, true
}

func (m BagItems) Store(key uint64, value *Item) {
	delete(m.state.itemsChanges.states, key)
	value = proto.Clone(value).(*Item)
	if m.state.value.Items == nil {
		m.state.value.Items = make(map[uint64]*Item)
	}
	m.state.value.Items[key] = value
	if m.state.itemsChanges.Put(key) {
		m.state.markItemsDirty()
	}
}

func (m BagItems) Clear() {
	if len(m.state.value.Items) == 0 {
		return
	}
	clear(m.state.itemsChanges.states)
	m.state.value.Items = nil
	if m.state.itemsChanges.Clear() {
		m.state.markItemsDirty()
	}
}

func (m BagItems) Len() int {
	return len(m.state.value.Items)
}

func (m BagItems) Delete(key uint64) {
	if _, ok := m.state.value.Items[key]; !ok {
		return
	}
	delete(m.state.itemsChanges.states, key)
	delete(m.state.value.Items, key)
	if m.state.itemsChanges.Delete(key) {
		m.state.markItemsDirty()
	}
}

func (m BagItems) Range(yield func(uint64, *ItemState) bool) {
	for key := range m.state.value.Items {
		state, _ := m.GetValue(key)
		if !yield(key, state) {
			return
		}
	}
}

func (s *BagState) WriteDiff(writer *diff.Writer) {
	if diff.HasDirty(s.dirty[bagStateDirtyItemsWord], bagStateDirtyItemsMask) {
		for index := range s.itemsChanges.changes {
			change := &s.itemsChanges.changes[index]
			switch change.operation {
			case diff.OperationClear:
				writer.Clear(1)
			case diff.OperationMapPut:
				data, err := proto.Marshal(s.value.Items[change.key])
				if err != nil {
					panic(err)
				}
				writer.MapPut(1, func(writer *diff.Writer) {
					writer.AppendUint64(change.key)
				}, func(writer *diff.Writer) {
					writer.AppendBytes(data)
				})
			case diff.OperationMapDelete:
				writer.MapDelete(1, func(writer *diff.Writer) {
					writer.AppendUint64(change.key)
				})
			case diff.OperationMapPatch:
				writer.MapPatch(1, func(writer *diff.Writer) {
					writer.AppendUint64(change.key)
				}, func(writer *diff.Writer) {
					change.state.WriteDiff(writer)
				})
			}
		}
	}
}

func ApplyBagDiff(value *Bag, data []byte) error {
	return applyBagDiff(value, data, nil)
}

func ApplyBagDiffWithHooks(value *Bag, data []byte, hooks *BagApplyHooks) error {
	return applyBagDiff(value, data, hooks)
}

func applyBagDiff(value *Bag, data []byte, hooks *BagApplyHooks) error {
	reader := diff.NewReader(data)
	for {
		fieldNumber, operation, payload, ok, err := reader.Next()
		if err != nil || !ok {
			return err
		}
		switch fieldNumber {
		case 1:
			if operation == diff.OperationClear {
				if len(payload) != 0 {
					return diff.ErrInvalidData
				}
				value.Items = nil
				if hooks != nil && hooks.OnItemsClear != nil {
					hooks.OnItemsClear()
				}
				break
			}
			valueReader := diff.NewValueReader(payload)
			key := valueReader.Uint64()
			switch operation {
			case diff.OperationMapPut:
				itemData := valueReader.Bytes()
				item := &Item{}
				if err := proto.Unmarshal(itemData, item); err != nil {
					return err
				}
				if valueReader.Err() != nil || !valueReader.Done() {
					return diff.ErrInvalidData
				}
				oldItem, replaced := value.Items[key]
				if value.Items == nil {
					value.Items = make(map[uint64]*Item)
				}
				value.Items[key] = item
				if hooks != nil && hooks.OnItemsPut != nil {
					var oldHookValue *Item
					if oldItem != nil {
						oldHookValue = proto.Clone(oldItem).(*Item)
					}
					hooks.OnItemsPut(key, oldHookValue, proto.Clone(item).(*Item), replaced)
				}
			case diff.OperationMapDelete:
				if valueReader.Err() != nil || !valueReader.Done() {
					return diff.ErrInvalidData
				}
				oldItem, existed := value.Items[key]
				delete(value.Items, key)
				if existed && hooks != nil && hooks.OnItemsDelete != nil {
					hooks.OnItemsDelete(key, proto.Clone(oldItem).(*Item))
				}
			case diff.OperationMapPatch:
				patch := valueReader.Remaining()
				if valueReader.Err() != nil {
					return diff.ErrInvalidData
				}
				item := value.Items[key]
				var oldItem *Item
				if hooks != nil && (hooks.OnItemsPatch != nil || hooks.OnItemsIdChanged != nil || hooks.OnItemsCountChanged != nil) && item != nil {
					oldItem = proto.Clone(item).(*Item)
				}
				if item == nil {
					item = &Item{}
					if value.Items == nil {
						value.Items = make(map[uint64]*Item)
					}
					value.Items[key] = item
				}
				var childHooks *ItemApplyHooks
				if hooks != nil && hooks.Items != nil {
					childHooks = hooks.Items(key)
				}
				if err := ApplyItemDiffWithHooks(item, patch, childHooks); err != nil {
					return err
				}
				if hooks != nil {
					if hooks.OnItemsPatch != nil {
						hooks.OnItemsPatch(key, oldItem, proto.Clone(item).(*Item))
					}
					if hooks.OnItemsIdChanged != nil && oldItem.GetId() != item.GetId() {
						hooks.OnItemsIdChanged(key, oldItem.GetId(), item.GetId())
					}
					if hooks.OnItemsCountChanged != nil && oldItem.GetCount() != item.GetCount() {
						hooks.OnItemsCountChanged(key, oldItem.GetCount(), item.GetCount())
					}
				}
			default:
				return diff.ErrInvalidData
			}
		}
	}
}

func (s *BagState) ClearDirty() {
	diff.ClearDirty(s.dirty[:])
	s.itemsChanges.ClearDirty()
}

type ItemApplyHooks struct {
	OnIdChanged    func(oldValue, newValue uint64)
	OnCountChanged func(oldValue, newValue int32)
}

const itemStateDirtyIdWord uint32 = 0
const itemStateDirtyIdMask uint64 = 1
const itemStateDirtyCountWord uint32 = 0
const itemStateDirtyCountMask uint64 = 2

type ItemState struct {
	value      *Item
	dirty      [1]uint64
	markParent func()
}

func NewItemState(value *Item) *ItemState {
	return newItemState(value, nil)
}

func NewItemStateWithParent(value *Item, markParent func()) *ItemState {
	return newItemState(value, markParent)
}

func newItemState(value *Item, markParent func()) *ItemState {
	state := &ItemState{value: value, markParent: markParent}
	return state
}

func (s *ItemState) GetRawValue() *Item {
	return s.value
}

func (s *ItemState) IsDirty() bool {
	return diff.AnyDirty(s.dirty[:])
}

func (s *ItemState) GetId() uint64 {
	return s.value.Id
}

func (s *ItemState) SetId(value uint64) {
	if s.value.Id == value {
		return
	}
	s.value.Id = value
	if diff.MarkDirty(&s.dirty[itemStateDirtyIdWord], itemStateDirtyIdMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *ItemState) GetCount() int32 {
	return s.value.Count
}

func (s *ItemState) SetCount(value int32) {
	if s.value.Count == value {
		return
	}
	s.value.Count = value
	if diff.MarkDirty(&s.dirty[itemStateDirtyCountWord], itemStateDirtyCountMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *ItemState) WriteDiff(writer *diff.Writer) {
	if diff.HasDirty(s.dirty[itemStateDirtyIdWord], itemStateDirtyIdMask) {
		writer.Uint64(1, s.value.Id)
	}
	if diff.HasDirty(s.dirty[itemStateDirtyCountWord], itemStateDirtyCountMask) {
		writer.Int32(2, s.value.Count)
	}
}

func ApplyItemDiff(value *Item, data []byte) error {
	return applyItemDiff(value, data, nil)
}

func ApplyItemDiffWithHooks(value *Item, data []byte, hooks *ItemApplyHooks) error {
	return applyItemDiff(value, data, hooks)
}

func applyItemDiff(value *Item, data []byte, hooks *ItemApplyHooks) error {
	reader := diff.NewReader(data)
	for {
		fieldNumber, operation, payload, ok, err := reader.Next()
		if err != nil || !ok {
			return err
		}
		switch fieldNumber {
		case 1:
			if operation != diff.OperationSetVarint {
				return diff.ErrInvalidData
			}
			oldValue := value.Id
			value.Id = diff.DecodeUint64(payload)
			if hooks != nil && hooks.OnIdChanged != nil {
				hooks.OnIdChanged(oldValue, value.Id)
			}
		case 2:
			if operation != diff.OperationSetVarint {
				return diff.ErrInvalidData
			}
			oldValue := value.Count
			value.Count = diff.DecodeInt32(payload)
			if hooks != nil && hooks.OnCountChanged != nil {
				hooks.OnCountChanged(oldValue, value.Count)
			}
		}
	}
}

func (s *ItemState) ClearDirty() {
	diff.ClearDirty(s.dirty[:])
}
