// Code generated by diff-gen. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: player/a_data_player.proto

package player

import (
	bag "github.com/2comjie/nova/examples/pb/bag"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Uid          uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Level        int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bag          *bag.Bag               `protobuf:"bytes,4,opt,name=bag,proto3" json:"bag,omitempty"`
	Scores       map[uint64]int32       `protobuf:"bytes,5,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RecentLevels []int32                `protobuf:"varint,6,rep,packed,name=recent_levels,json=recentLevels,proto3" json:"recent_levels,omitempty"`
	UidUpdate    *uint64                `protobuf:"varint,1001,opt,name=uid_update,json=uidUpdate,proto3,oneof" json:"uid_update,omitempty"`
	LevelUpdate  *int32                 `protobuf:"varint,1002,opt,name=level_update,json=levelUpdate,proto3,oneof" json:"level_update,omitempty"`
	NameUpdate   *string                `protobuf:"bytes,1003,opt,name=name_update,json=nameUpdate,proto3,oneof" json:"name_update,omitempty"`
	// Types that are valid to be assigned to BagDiff:
	//
	//	*Player_BagSet
	//	*Player_BagClear
	//	*Player_BagUpdate
	BagDiff             isPlayer_BagDiff `protobuf_oneof:"bag_diff"`
	ScoresClear         bool             `protobuf:"varint,1005,opt,name=scores_clear,json=scoresClear,proto3" json:"scores_clear,omitempty"`
	ScoresSet           map[uint64]int32 `protobuf:"bytes,2005,rep,name=scores_set,json=scoresSet,proto3" json:"scores_set,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ScoresDelete        []uint64         `protobuf:"varint,3005,rep,packed,name=scores_delete,json=scoresDelete,proto3" json:"scores_delete,omitempty"`
	RecentLevelsUpdated bool             `protobuf:"varint,1006,opt,name=recent_levels_updated,json=recentLevelsUpdated,proto3" json:"recent_levels_updated,omitempty"`
	RecentLevelsUpdate  []int32          `protobuf:"varint,2006,rep,packed,name=recent_levels_update,json=recentLevelsUpdate,proto3" json:"recent_levels_update,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_player_a_data_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_a_data_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_a_data_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetBag() *bag.Bag {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *Player) GetScores() map[uint64]int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Player) GetRecentLevels() []int32 {
	if x != nil {
		return x.RecentLevels
	}
	return nil
}

func (x *Player) GetUidUpdate() uint64 {
	if x != nil && x.UidUpdate != nil {
		return *x.UidUpdate
	}
	return 0
}

func (x *Player) GetLevelUpdate() int32 {
	if x != nil && x.LevelUpdate != nil {
		return *x.LevelUpdate
	}
	return 0
}

func (x *Player) GetNameUpdate() string {
	if x != nil && x.NameUpdate != nil {
		return *x.NameUpdate
	}
	return ""
}

func (x *Player) GetBagDiff() isPlayer_BagDiff {
	if x != nil {
		return x.BagDiff
	}
	return nil
}

func (x *Player) GetBagSet() *bag.Bag {
	if x != nil {
		if x, ok := x.BagDiff.(*Player_BagSet); ok {
			return x.BagSet
		}
	}
	return nil
}

func (x *Player) GetBagClear() bool {
	if x != nil {
		if x, ok := x.BagDiff.(*Player_BagClear); ok {
			return x.BagClear
		}
	}
	return false
}

func (x *Player) GetBagUpdate() *bag.Bag {
	if x != nil {
		if x, ok := x.BagDiff.(*Player_BagUpdate); ok {
			return x.BagUpdate
		}
	}
	return nil
}

func (x *Player) GetScoresClear() bool {
	if x != nil {
		return x.ScoresClear
	}
	return false
}

func (x *Player) GetScoresSet() map[uint64]int32 {
	if x != nil {
		return x.ScoresSet
	}
	return nil
}

func (x *Player) GetScoresDelete() []uint64 {
	if x != nil {
		return x.ScoresDelete
	}
	return nil
}

func (x *Player) GetRecentLevelsUpdated() bool {
	if x != nil {
		return x.RecentLevelsUpdated
	}
	return false
}

func (x *Player) GetRecentLevelsUpdate() []int32 {
	if x != nil {
		return x.RecentLevelsUpdate
	}
	return nil
}

type isPlayer_BagDiff interface {
	isPlayer_BagDiff()
}

type Player_BagSet struct {
	BagSet *bag.Bag `protobuf:"bytes,1004,opt,name=bag_set,json=bagSet,proto3,oneof"`
}

type Player_BagClear struct {
	BagClear bool `protobuf:"varint,2004,opt,name=bag_clear,json=bagClear,proto3,oneof"`
}

type Player_BagUpdate struct {
	BagUpdate *bag.Bag `protobuf:"bytes,3004,opt,name=bag_update,json=bagUpdate,proto3,oneof"`
}

func (*Player_BagSet) isPlayer_BagDiff() {}

func (*Player_BagClear) isPlayer_BagDiff() {}

func (*Player_BagUpdate) isPlayer_BagDiff() {}

var File_player_a_data_player_proto protoreflect.FileDescriptor

const file_player_a_data_player_proto_rawDesc = "" +
	"\n" +
	"\x1aplayer/a_data_player.proto\x12\x06player\x1a\x14bag/a_data_bag.proto\"\xc6\x06\n" +
	"\x06Player\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\x03bag\x18\x04 \x01(\v2\b.bag.BagR\x03bag\x122\n" +
	"\x06scores\x18\x05 \x03(\v2\x1a.player.Player.ScoresEntryR\x06scores\x12#\n" +
	"\rrecent_levels\x18\x06 \x03(\x05R\frecentLevels\x12#\n" +
	"\n" +
	"uid_update\x18\xe9\a \x01(\x04H\x01R\tuidUpdate\x88\x01\x01\x12'\n" +
	"\flevel_update\x18\xea\a \x01(\x05H\x02R\vlevelUpdate\x88\x01\x01\x12%\n" +
	"\vname_update\x18\xeb\a \x01(\tH\x03R\n" +
	"nameUpdate\x88\x01\x01\x12$\n" +
	"\abag_set\x18\xec\a \x01(\v2\b.bag.BagH\x00R\x06bagSet\x12\x1e\n" +
	"\tbag_clear\x18\xd4\x0f \x01(\bH\x00R\bbagClear\x12*\n" +
	"\n" +
	"bag_update\x18\xbc\x17 \x01(\v2\b.bag.BagH\x00R\tbagUpdate\x12\"\n" +
	"\fscores_clear\x18\xed\a \x01(\bR\vscoresClear\x12=\n" +
	"\n" +
	"scores_set\x18\xd5\x0f \x03(\v2\x1d.player.Player.ScoresSetEntryR\tscoresSet\x12$\n" +
	"\rscores_delete\x18\xbd\x17 \x03(\x04R\fscoresDelete\x123\n" +
	"\x15recent_levels_updated\x18\xee\a \x01(\bR\x13recentLevelsUpdated\x121\n" +
	"\x14recent_levels_update\x18\xd6\x0f \x03(\x05R\x12recentLevelsUpdate\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eScoresSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\n" +
	"\n" +
	"\bbag_diffB\r\n" +
	"\v_uid_updateB\x0f\n" +
	"\r_level_updateB\x0e\n" +
	"\f_name_updateBDZ*github.com/2comjie/nova/examples/pb/player\xaa\x02\x15Nova.Generated.Playerb\x06proto3"

var (
	file_player_a_data_player_proto_rawDescOnce sync.Once
	file_player_a_data_player_proto_rawDescData []byte
)

func file_player_a_data_player_proto_rawDescGZIP() []byte {
	file_player_a_data_player_proto_rawDescOnce.Do(func() {
		file_player_a_data_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_a_data_player_proto_rawDesc), len(file_player_a_data_player_proto_rawDesc)))
	})
	return file_player_a_data_player_proto_rawDescData
}

var file_player_a_data_player_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_player_a_data_player_proto_goTypes = []any{
	(*Player)(nil),  // 0: player.Player
	nil,             // 1: player.Player.ScoresEntry
	nil,             // 2: player.Player.ScoresSetEntry
	(*bag.Bag)(nil), // 3: bag.Bag
}
var file_player_a_data_player_proto_depIdxs = []int32{
	3, // 0: player.Player.bag:type_name -> bag.Bag
	1, // 1: player.Player.scores:type_name -> player.Player.ScoresEntry
	3, // 2: player.Player.bag_set:type_name -> bag.Bag
	3, // 3: player.Player.bag_update:type_name -> bag.Bag
	2, // 4: player.Player.scores_set:type_name -> player.Player.ScoresSetEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_player_a_data_player_proto_init() }
func file_player_a_data_player_proto_init() {
	if File_player_a_data_player_proto != nil {
		return
	}
	file_player_a_data_player_proto_msgTypes[0].OneofWrappers = []any{
		(*Player_BagSet)(nil),
		(*Player_BagClear)(nil),
		(*Player_BagUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_a_data_player_proto_rawDesc), len(file_player_a_data_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_a_data_player_proto_goTypes,
		DependencyIndexes: file_player_a_data_player_proto_depIdxs,
		MessageInfos:      file_player_a_data_player_proto_msgTypes,
	}.Build()
	File_player_a_data_player_proto = out.File
	file_player_a_data_player_proto_goTypes = nil
	file_player_a_data_player_proto_depIdxs = nil
}
