// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: transport/gate/gate.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Route           uint32                 `protobuf:"varint,2,opt,name=route,proto3" json:"route,omitempty"`
	Body            []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,4,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,5,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PushRequest) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *PushRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *PushRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

type KickRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,2,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	SessionId       uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{1}
}

func (x *KickRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KickRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *KickRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *KickRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_transport_gate_gate_proto protoreflect.FileDescriptor

const file_transport_gate_gate_proto_rawDesc = "" +
	"\n" +
	"\x19transport/gate/gate.proto\x12\x13wali.transport.gate\x1a\x1bgoogle/protobuf/empty.proto\"\x9f\x01\n" +
	"\vPushRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05route\x18\x02 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12*\n" +
	"\x11node_service_name\x18\x04 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x05 \x01(\tR\x0enodeInstanceId\"\x94\x01\n" +
	"\vKickRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12*\n" +
	"\x11node_service_name\x18\x02 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId2\x8a\x01\n" +
	"\x04Gate\x12@\n" +
	"\x04Push\x12 .wali.transport.gate.PushRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x04Kick\x12 .wali.transport.gate.KickRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/2comjie/wali/internal/pb/transport/gate;gateb\x06proto3"

var (
	file_transport_gate_gate_proto_rawDescOnce sync.Once
	file_transport_gate_gate_proto_rawDescData []byte
)

func file_transport_gate_gate_proto_rawDescGZIP() []byte {
	file_transport_gate_gate_proto_rawDescOnce.Do(func() {
		file_transport_gate_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_gate_gate_proto_rawDesc), len(file_transport_gate_gate_proto_rawDesc)))
	})
	return file_transport_gate_gate_proto_rawDescData
}

var file_transport_gate_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_gate_gate_proto_goTypes = []any{
	(*PushRequest)(nil),   // 0: wali.transport.gate.PushRequest
	(*KickRequest)(nil),   // 1: wali.transport.gate.KickRequest
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_transport_gate_gate_proto_depIdxs = []int32{
	0, // 0: wali.transport.gate.Gate.Push:input_type -> wali.transport.gate.PushRequest
	1, // 1: wali.transport.gate.Gate.Kick:input_type -> wali.transport.gate.KickRequest
	2, // 2: wali.transport.gate.Gate.Push:output_type -> google.protobuf.Empty
	2, // 3: wali.transport.gate.Gate.Kick:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_gate_gate_proto_init() }
func file_transport_gate_gate_proto_init() {
	if File_transport_gate_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_gate_gate_proto_rawDesc), len(file_transport_gate_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_gate_gate_proto_goTypes,
		DependencyIndexes: file_transport_gate_gate_proto_depIdxs,
		MessageInfos:      file_transport_gate_gate_proto_msgTypes,
	}.Build()
	File_transport_gate_gate_proto = out.File
	file_transport_gate_gate_proto_goTypes = nil
	file_transport_gate_gate_proto_depIdxs = nil
}
