// Code generated by protoc-gen-go-grpc-locator. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-locator v1.0.0
// - protoc             v5.28.2
// source: transport/gate/gate.proto

package gate

import (
	context "context"
	client "github.com/2comjie/wali/rpc/client"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gate_Push_FullMethodName = "/wali.transport.gate.Gate/Push"
	Gate_Kick_FullMethodName = "/wali.transport.gate.Gate/Kick"
)

// GateClient is the client API for Gate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gateClient struct {
	cc *client.Client
}

func NewGateClient(cc *client.Client) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, err
	}
	out := new(emptypb.Empty)
	err = conn.Invoke(ctx, Gate_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, err
	}
	out := new(emptypb.Empty)
	err = conn.Invoke(ctx, Gate_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateServer is the server API for Gate service.
// All implementations must embed UnimplementedGateServer
// for forward compatibility.
type GateServer interface {
	Push(context.Context, *PushRequest) (*emptypb.Empty, error)
	Kick(context.Context, *KickRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGateServer()
}

// UnimplementedGateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateServer struct{}

func (UnimplementedGateServer) Push(context.Context, *PushRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedGateServer) Kick(context.Context, *KickRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedGateServer) mustEmbedUnimplementedGateServer() {}
func (UnimplementedGateServer) testEmbeddedByValue()              {}

// UnsafeGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateServer will
// result in compilation errors.
type UnsafeGateServer interface {
	mustEmbedUnimplementedGateServer()
}

func RegisterGateServer(s grpc.ServiceRegistrar, srv GateServer) {
	// If the following call panics, it indicates UnimplementedGateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gate_ServiceDesc, srv)
}

func _Gate_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Kick(ctx, req.(*KickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gate_ServiceDesc is the grpc.ServiceDesc for Gate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wali.transport.gate.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Gate_Push_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _Gate_Kick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/gate/gate.proto",
}
