// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: transport/gate/gate.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Route           uint32                 `protobuf:"varint,2,opt,name=route,proto3" json:"route,omitempty"`
	Body            []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,4,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,5,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PushRequest) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *PushRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PushRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *PushRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

type KickRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,2,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	SessionId       uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{1}
}

func (x *KickRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *KickRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *KickRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *KickRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type BroadcastRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Route           uint32                 `protobuf:"varint,1,opt,name=route,proto3" json:"route,omitempty"`
	Body            []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,3,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,4,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *BroadcastRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BroadcastRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *BroadcastRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_transport_gate_gate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MultiPushRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UidList         []uint64               `protobuf:"varint,1,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	Route           uint32                 `protobuf:"varint,2,opt,name=route,proto3" json:"route,omitempty"`
	Body            []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,4,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,5,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MultiPushRequest) Reset() {
	*x = MultiPushRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPushRequest) ProtoMessage() {}

func (x *MultiPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPushRequest.ProtoReflect.Descriptor instead.
func (*MultiPushRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{4}
}

func (x *MultiPushRequest) GetUidList() []uint64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *MultiPushRequest) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *MultiPushRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MultiPushRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *MultiPushRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

type MultiPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPushResponse) Reset() {
	*x = MultiPushResponse{}
	mi := &file_transport_gate_gate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPushResponse) ProtoMessage() {}

func (x *MultiPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPushResponse.ProtoReflect.Descriptor instead.
func (*MultiPushResponse) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{5}
}

func (x *MultiPushResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MockCallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Route           uint32                 `protobuf:"varint,2,opt,name=route,proto3" json:"route,omitempty"`
	Body            []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	NodeServiceName string                 `protobuf:"bytes,4,opt,name=node_service_name,json=nodeServiceName,proto3" json:"node_service_name,omitempty"`
	NodeInstanceId  string                 `protobuf:"bytes,5,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MockCallRequest) Reset() {
	*x = MockCallRequest{}
	mi := &file_transport_gate_gate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockCallRequest) ProtoMessage() {}

func (x *MockCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockCallRequest.ProtoReflect.Descriptor instead.
func (*MockCallRequest) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{6}
}

func (x *MockCallRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MockCallRequest) GetRoute() uint32 {
	if x != nil {
		return x.Route
	}
	return 0
}

func (x *MockCallRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MockCallRequest) GetNodeServiceName() string {
	if x != nil {
		return x.NodeServiceName
	}
	return ""
}

func (x *MockCallRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

type MockCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replied       bool                   `protobuf:"varint,1,opt,name=replied,proto3" json:"replied,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockCallResponse) Reset() {
	*x = MockCallResponse{}
	mi := &file_transport_gate_gate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockCallResponse) ProtoMessage() {}

func (x *MockCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_gate_gate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockCallResponse.ProtoReflect.Descriptor instead.
func (*MockCallResponse) Descriptor() ([]byte, []int) {
	return file_transport_gate_gate_proto_rawDescGZIP(), []int{7}
}

func (x *MockCallResponse) GetReplied() bool {
	if x != nil {
		return x.Replied
	}
	return false
}

func (x *MockCallResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_transport_gate_gate_proto protoreflect.FileDescriptor

const file_transport_gate_gate_proto_rawDesc = "" +
	"\n" +
	"\x19transport/gate/gate.proto\x12\x13nova.transport.gate\x1a\x1bgoogle/protobuf/empty.proto\"\x9f\x01\n" +
	"\vPushRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05route\x18\x02 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12*\n" +
	"\x11node_service_name\x18\x04 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x05 \x01(\tR\x0enodeInstanceId\"\x94\x01\n" +
	"\vKickRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12*\n" +
	"\x11node_service_name\x18\x02 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId\"\x92\x01\n" +
	"\x10BroadcastRequest\x12\x14\n" +
	"\x05route\x18\x01 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12*\n" +
	"\x11node_service_name\x18\x03 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x04 \x01(\tR\x0enodeInstanceId\")\n" +
	"\x11BroadcastResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"\xad\x01\n" +
	"\x10MultiPushRequest\x12\x19\n" +
	"\buid_list\x18\x01 \x03(\x04R\auidList\x12\x14\n" +
	"\x05route\x18\x02 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12*\n" +
	"\x11node_service_name\x18\x04 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x05 \x01(\tR\x0enodeInstanceId\")\n" +
	"\x11MultiPushResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"\xa3\x01\n" +
	"\x0fMockCallRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05route\x18\x02 \x01(\rR\x05route\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12*\n" +
	"\x11node_service_name\x18\x04 \x01(\tR\x0fnodeServiceName\x12(\n" +
	"\x10node_instance_id\x18\x05 \x01(\tR\x0enodeInstanceId\"@\n" +
	"\x10MockCallResponse\x12\x18\n" +
	"\areplied\x18\x01 \x01(\bR\areplied\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body2\x9b\x03\n" +
	"\x04Gate\x12@\n" +
	"\x04Push\x12 .nova.transport.gate.PushRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x04Kick\x12 .nova.transport.gate.KickRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\tBroadcast\x12%.nova.transport.gate.BroadcastRequest\x1a&.nova.transport.gate.BroadcastResponse\x12Z\n" +
	"\tMultiPush\x12%.nova.transport.gate.MultiPushRequest\x1a&.nova.transport.gate.MultiPushResponse\x12W\n" +
	"\bMockCall\x12$.nova.transport.gate.MockCallRequest\x1a%.nova.transport.gate.MockCallResponseB9Z7github.com/2comjie/nova/internal/pb/transport/gate;gateb\x06proto3"

var (
	file_transport_gate_gate_proto_rawDescOnce sync.Once
	file_transport_gate_gate_proto_rawDescData []byte
)

func file_transport_gate_gate_proto_rawDescGZIP() []byte {
	file_transport_gate_gate_proto_rawDescOnce.Do(func() {
		file_transport_gate_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_gate_gate_proto_rawDesc), len(file_transport_gate_gate_proto_rawDesc)))
	})
	return file_transport_gate_gate_proto_rawDescData
}

var file_transport_gate_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transport_gate_gate_proto_goTypes = []any{
	(*PushRequest)(nil),       // 0: nova.transport.gate.PushRequest
	(*KickRequest)(nil),       // 1: nova.transport.gate.KickRequest
	(*BroadcastRequest)(nil),  // 2: nova.transport.gate.BroadcastRequest
	(*BroadcastResponse)(nil), // 3: nova.transport.gate.BroadcastResponse
	(*MultiPushRequest)(nil),  // 4: nova.transport.gate.MultiPushRequest
	(*MultiPushResponse)(nil), // 5: nova.transport.gate.MultiPushResponse
	(*MockCallRequest)(nil),   // 6: nova.transport.gate.MockCallRequest
	(*MockCallResponse)(nil),  // 7: nova.transport.gate.MockCallResponse
	(*emptypb.Empty)(nil),     // 8: google.protobuf.Empty
}
var file_transport_gate_gate_proto_depIdxs = []int32{
	0, // 0: nova.transport.gate.Gate.Push:input_type -> nova.transport.gate.PushRequest
	1, // 1: nova.transport.gate.Gate.Kick:input_type -> nova.transport.gate.KickRequest
	2, // 2: nova.transport.gate.Gate.Broadcast:input_type -> nova.transport.gate.BroadcastRequest
	4, // 3: nova.transport.gate.Gate.MultiPush:input_type -> nova.transport.gate.MultiPushRequest
	6, // 4: nova.transport.gate.Gate.MockCall:input_type -> nova.transport.gate.MockCallRequest
	8, // 5: nova.transport.gate.Gate.Push:output_type -> google.protobuf.Empty
	8, // 6: nova.transport.gate.Gate.Kick:output_type -> google.protobuf.Empty
	3, // 7: nova.transport.gate.Gate.Broadcast:output_type -> nova.transport.gate.BroadcastResponse
	5, // 8: nova.transport.gate.Gate.MultiPush:output_type -> nova.transport.gate.MultiPushResponse
	7, // 9: nova.transport.gate.Gate.MockCall:output_type -> nova.transport.gate.MockCallResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_gate_gate_proto_init() }
func file_transport_gate_gate_proto_init() {
	if File_transport_gate_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_gate_gate_proto_rawDesc), len(file_transport_gate_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_gate_gate_proto_goTypes,
		DependencyIndexes: file_transport_gate_gate_proto_depIdxs,
		MessageInfos:      file_transport_gate_gate_proto_msgTypes,
	}.Build()
	File_transport_gate_gate_proto = out.File
	file_transport_gate_gate_proto_goTypes = nil
	file_transport_gate_gate_proto_depIdxs = nil
}
