// Code generated by protoc-gen-go-grpc-locator. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc-locator v1.2.0
// - protoc             v5.28.2
// source: transport/node/node.proto

package node

import (
	context "context"
	rpc "github.com/2comjie/wali/rpc"
	client "github.com/2comjie/wali/rpc/client"
	rpcerr "github.com/2comjie/wali/rpc/rpcerr"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_Call_FullMethodName = "/wali.transport.node.Node/Call"
	Node_Tell_FullMethodName = "/wali.transport.node.Node/Tell"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err)
	Tell(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err)
}

type nodeClient struct {
	cc *client.Client
}

func NewNodeClient(cc *client.Client) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	out := new(Response)
	err = conn.Invoke(ctx, Node_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	return out, nil
}

func (c *nodeClient) Tell(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, rpcerr.Err) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	conn, err := c.cc.Conn(ctx)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	out := new(Response)
	err = conn.Invoke(ctx, Node_Tell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, rpc.DecodeErr(err)
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
type NodeServer interface {
	Call(context.Context, *Request) (*Response, error)
	Tell(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) Call(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedNodeServer) Tell(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Tell not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call panics, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		response, err := srv.(NodeServer).Call(ctx, in)
		return response, rpc.EncodeError(err)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Call(ctx, req.(*Request))
	}
	response, err := interceptor(ctx, in, info, handler)
	return response, rpc.EncodeError(err)
}

func _Node_Tell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		response, err := srv.(NodeServer).Tell(ctx, in)
		return response, rpc.EncodeError(err)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_Tell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Tell(ctx, req.(*Request))
	}
	response, err := interceptor(ctx, in, info, handler)
	return response, rpc.EncodeError(err)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wali.transport.node.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Node_Call_Handler,
		},
		{
			MethodName: "Tell",
			Handler:    _Node_Tell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/node/node.proto",
}
