// Code generated by protoc-gen-go-diff. DO NOT EDIT.
// protoc-gen-go-diff v0.1.0
// source: diff/testdata/playerpkg/player.proto

package playerpkg

import (
	diff "github.com/2comjie/nova/diff"
	bagpkg "github.com/2comjie/nova/diff/testdata/bagpkg"
	proto "google.golang.org/protobuf/proto"
)

type PlayerApplyHooks struct {
	OnIdChanged  func(oldValue, newValue uint64)
	Bag          *bagpkg.BagApplyHooks
	OnBagPatch   func(oldValue, newValue *bagpkg.Bag)
	OnBagReplace func(oldValue, newValue *bagpkg.Bag)
	OnBagClear   func(oldValue *bagpkg.Bag)
}

const playerStateDirtyIdWord uint32 = 0
const playerStateDirtyIdMask uint64 = 1
const playerStateDirtyBagWord uint32 = 0
const playerStateDirtyBagMask uint64 = 2

type PlayerState struct {
	value        *Player
	dirty        [1]uint64
	markParent   func()
	bag          *bagpkg.BagState
	bagOperation diff.Operation
}

func NewPlayerState(value *Player) *PlayerState {
	return newPlayerState(value, nil)
}

func NewPlayerStateWithParent(value *Player, markParent func()) *PlayerState {
	return newPlayerState(value, markParent)
}

func newPlayerState(value *Player, markParent func()) *PlayerState {
	state := &PlayerState{value: value, markParent: markParent}
	if value.Bag != nil {
		state.bag = bagpkg.NewBagStateWithParent(value.Bag, state.markBagDirty)
	}
	return state
}

func (s *PlayerState) GetRawValue() *Player {
	return s.value
}

func (s *PlayerState) IsDirty() bool {
	return diff.AnyDirty(s.dirty[:])
}

func (s *PlayerState) GetId() uint64 {
	return s.value.Id
}

func (s *PlayerState) SetId(value uint64) {
	if s.value.Id == value {
		return
	}
	s.value.Id = value
	if diff.MarkDirty(&s.dirty[playerStateDirtyIdWord], playerStateDirtyIdMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *PlayerState) markBagDirty() {
	if diff.MarkDirty(&s.dirty[playerStateDirtyBagWord], playerStateDirtyBagMask) {
		s.bagOperation = diff.OperationPatch
		if s.markParent != nil {
			s.markParent()
		}
	}
}

func (s *PlayerState) GetBag() *bagpkg.BagState {
	return s.bag
}

func (s *PlayerState) SetBag(value *bagpkg.Bag) {
	value = proto.Clone(value).(*bagpkg.Bag)
	s.value.Bag = value
	s.bag = bagpkg.NewBagStateWithParent(value, s.markBagDirty)
	s.bagOperation = diff.OperationReplace
	if diff.MarkDirty(&s.dirty[playerStateDirtyBagWord], playerStateDirtyBagMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *PlayerState) ClearBag() {
	if s.bag == nil {
		return
	}
	s.value.Bag = nil
	s.bag = nil
	s.bagOperation = diff.OperationClear
	if diff.MarkDirty(&s.dirty[playerStateDirtyBagWord], playerStateDirtyBagMask) && s.markParent != nil {
		s.markParent()
	}
}

func (s *PlayerState) WriteDiff(writer *diff.Writer) {
	if diff.HasDirty(s.dirty[playerStateDirtyIdWord], playerStateDirtyIdMask) {
		writer.Uint64(1, s.value.Id)
	}
	if diff.HasDirty(s.dirty[playerStateDirtyBagWord], playerStateDirtyBagMask) {
		switch s.bagOperation {
		case diff.OperationPatch:
			writer.Patch(2, s.bag.WriteDiff)
		case diff.OperationReplace:
			data, err := proto.Marshal(s.value.Bag)
			if err != nil {
				panic(err)
			}
			writer.Replace(2, func(writer *diff.Writer) {
				writer.AppendRaw(data)
			})
		case diff.OperationClear:
			writer.Clear(2)
		}
	}
}

func ApplyPlayerDiff(value *Player, data []byte) error {
	return applyPlayerDiff(value, data, nil)
}

func ApplyPlayerDiffWithHooks(value *Player, data []byte, hooks *PlayerApplyHooks) error {
	return applyPlayerDiff(value, data, hooks)
}

func applyPlayerDiff(value *Player, data []byte, hooks *PlayerApplyHooks) error {
	reader := diff.NewReader(data)
	for {
		fieldNumber, operation, payload, ok, err := reader.Next()
		if err != nil || !ok {
			return err
		}
		switch fieldNumber {
		case 1:
			if operation != diff.OperationSetVarint {
				return diff.ErrInvalidData
			}
			oldValue := value.Id
			value.Id = diff.DecodeUint64(payload)
			if hooks != nil && hooks.OnIdChanged != nil {
				hooks.OnIdChanged(oldValue, value.Id)
			}
		case 2:
			switch operation {
			case diff.OperationPatch:
				var oldValue *bagpkg.Bag
				if hooks != nil && (hooks.OnBagPatch != nil) && value.Bag != nil {
					oldValue = proto.Clone(value.Bag).(*bagpkg.Bag)
				}
				var childHooks *bagpkg.BagApplyHooks
				if hooks != nil {
					childHooks = hooks.Bag
				}
				if value.Bag == nil {
					value.Bag = &bagpkg.Bag{}
				}
				if err := bagpkg.ApplyBagDiffWithHooks(value.Bag, payload, childHooks); err != nil {
					return err
				}
				if hooks != nil {
					if hooks.OnBagPatch != nil {
						hooks.OnBagPatch(oldValue, proto.Clone(value.Bag).(*bagpkg.Bag))
					}
				}
			case diff.OperationReplace:
				var oldValue *bagpkg.Bag
				if hooks != nil && (hooks.OnBagReplace != nil) && value.Bag != nil {
					oldValue = proto.Clone(value.Bag).(*bagpkg.Bag)
				}
				value.Bag = &bagpkg.Bag{}
				if err := proto.Unmarshal(payload, value.Bag); err != nil {
					return err
				}
				if hooks != nil && hooks.OnBagReplace != nil {
					hooks.OnBagReplace(oldValue, proto.Clone(value.Bag).(*bagpkg.Bag))
				}
			case diff.OperationClear:
				var oldValue *bagpkg.Bag
				if hooks != nil && (hooks.OnBagClear != nil) && value.Bag != nil {
					oldValue = proto.Clone(value.Bag).(*bagpkg.Bag)
				}
				value.Bag = nil
				if hooks != nil && hooks.OnBagClear != nil {
					hooks.OnBagClear(oldValue)
				}
			default:
				return diff.ErrInvalidData
			}
		}
	}
}

func (s *PlayerState) ClearDirty() {
	diff.ClearDirty(s.dirty[:])
	s.bagOperation = 0
	if s.bag != nil {
		s.bag.ClearDirty()
	}
}
