// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: diff/testdata/playerpkg/player.proto

package playerpkg

import (
	bagpkg "github.com/2comjie/nova/diff/testdata/bagpkg"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bag           *bagpkg.Bag            `protobuf:"bytes,2,opt,name=bag,proto3" json:"bag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_diff_testdata_playerpkg_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_diff_testdata_playerpkg_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_diff_testdata_playerpkg_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetBag() *bagpkg.Bag {
	if x != nil {
		return x.Bag
	}
	return nil
}

var File_diff_testdata_playerpkg_player_proto protoreflect.FileDescriptor

const file_diff_testdata_playerpkg_player_proto_rawDesc = "" +
	"\n" +
	"$diff/testdata/playerpkg/player.proto\x12\x1cnova.diff.testdata.playerpkg\x1a\x1ediff/testdata/bagpkg/bag.proto\"J\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x120\n" +
	"\x03bag\x18\x02 \x01(\v2\x1e.nova.diff.testdata.bagpkg.BagR\x03bagB;Z9github.com/2comjie/nova/diff/testdata/playerpkg;playerpkgb\x06proto3"

var (
	file_diff_testdata_playerpkg_player_proto_rawDescOnce sync.Once
	file_diff_testdata_playerpkg_player_proto_rawDescData []byte
)

func file_diff_testdata_playerpkg_player_proto_rawDescGZIP() []byte {
	file_diff_testdata_playerpkg_player_proto_rawDescOnce.Do(func() {
		file_diff_testdata_playerpkg_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diff_testdata_playerpkg_player_proto_rawDesc), len(file_diff_testdata_playerpkg_player_proto_rawDesc)))
	})
	return file_diff_testdata_playerpkg_player_proto_rawDescData
}

var file_diff_testdata_playerpkg_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_diff_testdata_playerpkg_player_proto_goTypes = []any{
	(*Player)(nil),     // 0: nova.diff.testdata.playerpkg.Player
	(*bagpkg.Bag)(nil), // 1: nova.diff.testdata.bagpkg.Bag
}
var file_diff_testdata_playerpkg_player_proto_depIdxs = []int32{
	1, // 0: nova.diff.testdata.playerpkg.Player.bag:type_name -> nova.diff.testdata.bagpkg.Bag
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_diff_testdata_playerpkg_player_proto_init() }
func file_diff_testdata_playerpkg_player_proto_init() {
	if File_diff_testdata_playerpkg_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_testdata_playerpkg_player_proto_rawDesc), len(file_diff_testdata_playerpkg_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_testdata_playerpkg_player_proto_goTypes,
		DependencyIndexes: file_diff_testdata_playerpkg_player_proto_depIdxs,
		MessageInfos:      file_diff_testdata_playerpkg_player_proto_msgTypes,
	}.Build()
	File_diff_testdata_playerpkg_player_proto = out.File
	file_diff_testdata_playerpkg_player_proto_goTypes = nil
	file_diff_testdata_playerpkg_player_proto_depIdxs = nil
}
