//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package {{.PackageName}}

import (
{{range .Imports}}
    {{.Alias}} "{{.Path}}"
{{end}}
)

{{range .Types}}
type {{.Name}} struct {
{{range .RuntimeFields}}
    {{.}}
{{end}}
    diff.Object
{{range .Fields}}
    {{.RuntimeName}} {{.RuntimeType}}{{if .Tag}} `{{.Tag}}`{{end}}
{{end}}
}

func (value *{{.Name}}) InitLink(writer *diff.Writer) {
    if value.Object.Initialized() {
        if writer != nil {
            value.Object.Init(writer)
        }
        return
    }

    value.Object.Init(writer)
{{range .Fields}}
    value.{{.RuntimeName}}.Init(&value.Object, {{.DiffIndex}})
{{end}}
}

{{$typeName := .Name}}
{{range .Fields}}
{{if or (eq .Kind "primitive") (eq .Kind "pointer")}}
func (value *{{$typeName}}) Get{{.Name}}() {{.ValueType}} {
    return value.{{.RuntimeName}}.GetValue()
}

func (value *{{$typeName}}) Set{{.Name}}(fieldValue {{.ValueType}}) bool {
    value.InitLink(nil)
    return value.{{.RuntimeName}}.SetValue(fieldValue)
}
{{else}}
func (value *{{$typeName}}) {{.Name}}() *{{.RuntimeType}} {
    value.InitLink(nil)
    return &value.{{.RuntimeName}}
}
{{end}}
{{end}}
{{end}}