//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package {{.PackageName}}

import (
{{range .Imports}}
    {{.Alias}} "{{.Path}}"
{{end}}
)

{{range .Declarations}}
{{.}}
{{end}}

{{range .Types}}
type {{.Name}} struct {
{{range .RuntimeFields}}
    {{.}}
{{end}}
    diff.Object
{{range .Fields}}
    {{.RuntimeName}} {{.RuntimeType}}{{if .Tag}} `{{.Tag}}`{{end}}
{{end}}
}

func (value *{{.Name}}) InitLink(writer *diff.Writer) {
    if value.Object.Initialized() {
        if writer != nil {
            value.Object.Init(writer)
        }
        return
    }

    value.Object.Init(writer)
{{range .Fields}}
    value.{{.RuntimeName}}.Init(&value.Object, {{.DiffIndex}})
{{end}}
}

{{$typeName := .Name}}
{{range .Fields}}
{{if or (eq .Kind "primitive") (eq .Kind "pointer")}}
func (value *{{$typeName}}) Get{{.Name}}() {{.ValueType}} {
    return value.{{.RuntimeName}}.GetValue()
}

func (value *{{$typeName}}) Set{{.Name}}(fieldValue {{.ValueType}}) bool {
    value.InitLink(nil)
    return value.{{.RuntimeName}}.SetValue(fieldValue)
}
{{else}}
func (value *{{$typeName}}) {{.Name}}() *{{.RuntimeType}} {
    value.InitLink(nil)
    return &value.{{.RuntimeName}}
}
{{end}}
{{end}}
// Snapshot 导出独立的全量 Proto，不修改对象和变更记录。
func (value *{{.Name}}) Snapshot() *pbData.{{.Name}} {
    snapshot := &pbData.{{.Name}}{
{{range .Fields}}
{{- if eq .Kind "primitive"}}
        {{.ProtoGoName}}: {{.Encode (printf "value.%s.GetValue()" .RuntimeName)}},
{{- end}}
{{end}}
    }
{{range .Fields}}
{{- if eq .Kind "pointer"}}
    if child := value.{{.RuntimeName}}.GetValue(); child != nil {
        snapshot.{{.ProtoGoName}} = child.Snapshot()
    }
{{- else if or (eq .Kind "primitiveMap") (eq .Kind "pointerMap")}}
    if value.{{.RuntimeName}}.Len() != 0 {
        snapshot.{{.ProtoGoName}} = make(map[{{.ProtoKeyType}}]{{.ProtoGoType}}, value.{{.RuntimeName}}.Len())
        value.{{.RuntimeName}}.Range(func(key {{.KeyType}}, fieldValue {{.ValueType}}) bool {
{{- if eq .Kind "pointerMap"}}
            snapshot.{{.ProtoGoName}}[{{if ne .KeyType .ProtoKeyType}}{{.ProtoKeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = fieldValue.Snapshot()
{{- else}}
            snapshot.{{.ProtoGoName}}[{{if ne .KeyType .ProtoKeyType}}{{.ProtoKeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = {{.Encode "fieldValue"}}
{{- end}}
            return true
        })
    }
{{- else if or (eq .Kind "primitiveSlice") (eq .Kind "pointerSlice")}}
    if value.{{.RuntimeName}}.Len() != 0 {
        snapshot.{{.ProtoGoName}} = make([]{{.ProtoGoType}}, value.{{.RuntimeName}}.Len())
        for index := range snapshot.{{.ProtoGoName}} {
            fieldValue := value.{{.RuntimeName}}.GetValue(index)
{{- if eq .Kind "pointerSlice"}}
            if fieldValue != nil {
                snapshot.{{.ProtoGoName}}[index] = fieldValue.Snapshot()
            }
{{- else}}
            snapshot.{{.ProtoGoName}}[index] = {{.Encode "fieldValue"}}
{{- end}}
        }
    }
{{- end}}
{{end}}
    return snapshot
}

// LoadSnapshot 加载全量基线并恢复父子链接，不记录增量。
// snapshot 必须非空；已有待提交变化由调用方在重置基线前处理。
func (value *{{.Name}}) LoadSnapshot(snapshot *pbData.{{.Name}}) {
    value.InitLink(nil)
{{range .Fields}}
{{- if eq .Kind "primitive"}}
    value.{{.RuntimeName}}.LoadSnapshot({{.Decode (printf "snapshot.%s" .ProtoGoName)}})
{{- else if eq .Kind "pointer"}}
    {
        var child {{.ValueType}}
        if snapshot.{{.ProtoGoName}} != nil {
            child = new({{.ElementType}})
            child.LoadSnapshot(snapshot.{{.ProtoGoName}})
        }
        value.{{.RuntimeName}}.LoadSnapshot(child)
    }
{{- else if or (eq .Kind "primitiveMap") (eq .Kind "pointerMap")}}
    {
        var values map[{{.KeyType}}]{{.ValueType}}
        if len(snapshot.{{.ProtoGoName}}) != 0 {
            values = make(map[{{.KeyType}}]{{.ValueType}}, len(snapshot.{{.ProtoGoName}}))
            for key, fieldValue := range snapshot.{{.ProtoGoName}} {
{{- if eq .Kind "pointerMap"}}
                child := new({{.ElementType}})
                if fieldValue != nil {
                    child.LoadSnapshot(fieldValue)
                }
                values[{{if ne .KeyType .ProtoKeyType}}{{.KeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = child
{{- else}}
                values[{{if ne .KeyType .ProtoKeyType}}{{.KeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = {{.Decode "fieldValue"}}
{{- end}}
            }
        }
        value.{{.RuntimeName}}.LoadSnapshot(values)
    }
{{- else if or (eq .Kind "primitiveSlice") (eq .Kind "pointerSlice")}}
    {
        var values []{{.ValueType}}
        if len(snapshot.{{.ProtoGoName}}) != 0 {
            values = make([]{{.ValueType}}, len(snapshot.{{.ProtoGoName}}))
            for index, fieldValue := range snapshot.{{.ProtoGoName}} {
{{- if eq .Kind "pointerSlice"}}
                if fieldValue != nil {
                    child := new({{.ElementType}})
                    child.LoadSnapshot(fieldValue)
                    values[index] = child
                }
{{- else}}
                values[index] = {{.Decode "fieldValue"}}
{{- end}}
            }
        }
        value.{{.RuntimeName}}.LoadSnapshot(values)
    }
{{- end}}
{{end}}
}
{{template "updates" .}}
{{template "codecs" .}}
{{end}}
