//go:build !diff_fast

// Code generated by diff-gen. DO NOT EDIT.

package {{.PackageName}}

import (
{{range .Imports}}
    {{.Alias}} "{{.Path}}"
{{end}}
)

{{range .Types}}
type {{.Name}} struct {
{{range .RuntimeFields}}
    {{.}}
{{end}}
    diff.Object
{{range .Fields}}
    {{.RuntimeName}} {{.RuntimeType}}{{if .Tag}} `{{.Tag}}`{{end}}
{{end}}
}

func (value *{{.Name}}) InitLink(writer *diff.Writer) {
    if value.Object.Initialized() {
        if writer != nil {
            value.Object.Init(writer)
        }
        return
    }

    value.Object.Init(writer)
{{range .Fields}}
    value.{{.RuntimeName}}.Init(&value.Object, {{.DiffIndex}})
{{end}}
}

{{$typeName := .Name}}
{{range .Fields}}
{{if or (eq .Kind "primitive") (eq .Kind "pointer")}}
func (value *{{$typeName}}) Get{{.Name}}() {{.ValueType}} {
    return value.{{.RuntimeName}}.GetValue()
}

func (value *{{$typeName}}) Set{{.Name}}(fieldValue {{.ValueType}}) bool {
    value.InitLink(nil)
    return value.{{.RuntimeName}}.SetValue(fieldValue)
}
{{else}}
func (value *{{$typeName}}) {{.Name}}() *{{.RuntimeType}} {
    value.InitLink(nil)
    return &value.{{.RuntimeName}}
}
{{end}}
{{end}}
// Snapshot 导出独立的全量 Proto，不修改对象和变更记录。
func (value *{{.Name}}) Snapshot() *pbData.{{.Name}} {
    snapshot := &pbData.{{.Name}}{
{{range .Fields}}
{{- if eq .Kind "primitive"}}
        {{.ProtoGoName}}: {{if ne .ValueType .ProtoGoType}}{{.ProtoGoType}}({{end}}value.{{.RuntimeName}}.GetValue(){{if ne .ValueType .ProtoGoType}}){{end}},
{{- end}}
{{end}}
    }
{{range .Fields}}
{{- if eq .Kind "pointer"}}
    if child := value.{{.RuntimeName}}.GetValue(); child != nil {
        snapshot.{{.ProtoGoName}} = child.Snapshot()
    }
{{- else if or (eq .Kind "primitiveMap") (eq .Kind "pointerMap")}}
    if value.{{.RuntimeName}}.Len() != 0 {
        snapshot.{{.ProtoGoName}} = make(map[{{.ProtoKeyType}}]{{.ProtoGoType}}, value.{{.RuntimeName}}.Len())
        value.{{.RuntimeName}}.Range(func(key {{.KeyType}}, fieldValue {{.ValueType}}) bool {
{{- if eq .Kind "pointerMap"}}
            snapshot.{{.ProtoGoName}}[{{if ne .KeyType .ProtoKeyType}}{{.ProtoKeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = fieldValue.Snapshot()
{{- else}}
            snapshot.{{.ProtoGoName}}[{{if ne .KeyType .ProtoKeyType}}{{.ProtoKeyType}}({{end}}key{{if ne .KeyType .ProtoKeyType}}){{end}}] = {{if ne .ValueType .ProtoGoType}}{{.ProtoGoType}}({{end}}fieldValue{{if ne .ValueType .ProtoGoType}}){{end}}
{{- end}}
            return true
        })
    }
{{- else if or (eq .Kind "primitiveSlice") (eq .Kind "pointerSlice")}}
    if value.{{.RuntimeName}}.Len() != 0 {
        snapshot.{{.ProtoGoName}} = make([]{{.ProtoGoType}}, value.{{.RuntimeName}}.Len())
        for index := range snapshot.{{.ProtoGoName}} {
            fieldValue := value.{{.RuntimeName}}.GetValue(index)
{{- if eq .Kind "pointerSlice"}}
            if fieldValue != nil {
                snapshot.{{.ProtoGoName}}[index] = fieldValue.Snapshot()
            }
{{- else}}
            snapshot.{{.ProtoGoName}}[index] = {{if ne .ValueType .ProtoGoType}}{{.ProtoGoType}}({{end}}fieldValue{{if ne .ValueType .ProtoGoType}}){{end}}
{{- end}}
        }
    }
{{- end}}
{{end}}
    return snapshot
}
{{end}}
